import type { NavigatorScreenParams } from "@react-navigation/native";
import type { MarketStackParamList } from "./MarketStackNavigator";
import type { LearnStackParamList } from "./LearnStackNavigator";

export type MainTabParamList = {
  Home: undefined;
  Search: undefined;
  Market: NavigatorScreenParams<MarketStackParamList>;
  Learn: NavigatorScreenParams<LearnStackParamList>;
  Services: undefined;
  Messages: undefined;
  Profile: undefined;
};

export type RootStackParamList = {
  Splash: undefined;
  InitialSetup: undefined;
  AuthChoice: { initialMode?: "register" | "login"; passwordResetSuccess?: boolean; loginPhone?: string } | undefined;
  OtpVerify: { phone: string };
  ForgotPassword: undefined;
  ForgotPasswordOtp: { phone: string };
  PersonalInfo: undefined;
  RoleSelection: undefined;
  BuyerInterests: undefined;
  BuyerDelivery: undefined;
  BuyerWalkthrough: undefined;
  SellerFarm: undefined;
  SellerKYC: undefined;
  SellerBank: undefined;
  ExpertDomain: undefined;
  ExpertCredentials: undefined;
  ExpertVerification: undefined;
  SecurityVerification: undefined;
  Main: NavigatorScreenParams<MainTabParamList> | undefined;
  ProviderMain: undefined;
  ProviderNewListing: undefined;
  InstructorStudio: undefined;
  EditProfile: undefined;
  PublicProfile: { userId?: number; userName: string; userKey?: string; avatarUrl?: string | null };
  DirectChat: {
    peerUserId: number;
    peerName: string;
    peerKey?: string;
    peerUsername?: string;
    peerAvatarUrl?: string | null;
    autoStartCall?: "voice" | "video";
    incomingCall?: { roomName: string; mode: "voice" | "video"; callerId: number; autoAccept?: boolean };
  };
  SettingsMenu: undefined;
  ProviderOnboarding: undefined;
  ProviderTerms: undefined;
  ProviderOfferRole: undefined;
  ProviderPersonalDetails: { track?: "rental" | "service" | "both" } | undefined;
  ProviderBankDetails: { track?: "rental" | "service" | "both" } | undefined;
  ProviderKycVerification: { track?: "rental" | "service" | "both" } | undefined;
  ProviderVerification: { track?: "rental" | "service" | "both" } | undefined;
  SavedSettings: undefined;
  YourActivity: undefined;
  YourActivityLikes: undefined;
  YourActivityComments: undefined;
  YourActivityMentionsTags: undefined;
  YourActivityRecentlyDeleted: undefined;
  YourActivityPosts: undefined;
  YourActivityDrops: undefined;
  YourActivityInterested: undefined;
  YourActivityNotInterested: undefined;
  YourActivityRecentSearches: undefined;
  YourActivityWatchHistory: undefined;
  YourActivityShares: undefined;
  YourActivityHighlights: undefined;
  YourActivityArchived: undefined;
  YourActivityTimeManagement: undefined;
  YourActivityLinkHistory: undefined;
  YourActivityAccountHistory: undefined;
  LanguageTranslations: undefined;
  NotificationsSettings: undefined;
  AccountCenter: undefined;
  ProfilesPersonalDetails: undefined;
  PasswordSecurity: undefined;
  ChangePassword: undefined;
  TwoFactorAuth: undefined;
  EmailVerification: undefined;
  VerificationSelfie: undefined;
  SaveLogin: undefined;
  WhereLoggedIn: undefined;
  LoginActivity: { accountName?: string; userId?: number } | undefined;
  LoginDeviceDetail: { sessionId: string };
  SecurityCheckup: undefined;
  ConnectedExperiences: undefined;
  SharingAcrossProfiles: undefined;
  MemoriesFromInstagram: undefined;
  ShowingProfileLinks: undefined;
  SyncingProfilePictures: undefined;
  ManagingAvatars: undefined;
  YourInformationPermissions: undefined;
  AboutAccountsCentre: undefined;
  SearchHistory: undefined;
  AutoClearSearchHistory: undefined;
  HowAutoClearingWorks: undefined;
  ActivityOffCropvibe: undefined;
  ManageAccounts: undefined;
  ManageAccountOptions: undefined;
  DeactivateDeleteChoice: undefined;
  DeactivateDeleteContinue: undefined;
  ActivityAcrossPartners: undefined;
  ConfirmItsYou: {
    title?: string;
    description?: string;
    action?: "clearOffCropvibeActivity" | "managePartnerActivity" | "disconnectFutureActivity";
    profileId?: string;
  };
  ClearPreviousActivity: undefined;
  WhatYouShouldKnow: undefined;
  UploadContacts: undefined;
  ConnectedApps: undefined;
  Privacy: undefined;
  BlockedAccounts: undefined;
  About: undefined;
};
