import "./PrivacyPolicy.css";

export function PrivacyPolicy() {
  return (
    <div className="privacy-policy">
      <header className="privacy-policy__header">
        <h1>Privacy Policy for CropVibe</h1>
        <p>
          <strong>Effective Date:</strong> June 22, 2026
        </p>
        <p>
          <strong>Last Updated:</strong> June 24, 2026
        </p>
      </header>

      <section>
        <h2>1. Introduction</h2>
        <p>Welcome to CropVibe (&quot;CropVibe&quot;, &quot;we&quot;, &quot;our&quot;, or &quot;us&quot;).</p>
        <p>
          CropVibe is a social networking platform for the farming community that allows users to create profiles,
          share posts, images, videos, and reels, follow other users, interact through comments and likes, receive
          notifications, and engage with agricultural content and discussions.
        </p>
        <p>
          This Privacy Policy describes how we collect, use, disclose, and safeguard your information when you use
          the CropVibe mobile application and related services.
        </p>
        <p>
          By accessing or using CropVibe, you agree to the collection and use of information in accordance with this
          Privacy Policy.
        </p>
      </section>

      <section>
        <h2>2. Information We Collect</h2>
        <h3>Personal Information</h3>
        <p>When you create an account, we may collect:</p>
        <ul>
          <li>Full Name</li>
          <li>Mobile Number</li>
          <li>Email Address</li>
          <li>Username</li>
          <li>Profile Photo</li>
        </ul>

        <h3>User Generated Content</h3>
        <p>We collect content that you create and upload, including:</p>
        <ul>
          <li>Posts</li>
          <li>Images</li>
          <li>Videos</li>
          <li>Reels</li>
          <li>Comments</li>
          <li>Profile Information</li>
        </ul>

        <h3>Device Information</h3>
        <p>We may automatically collect:</p>
        <ul>
          <li>Device Type</li>
          <li>Device Model</li>
          <li>Operating System</li>
          <li>Application Version</li>
          <li>IP Address</li>
          <li>Device Identifiers</li>
          <li>Log Information</li>
        </ul>

        <h3>Notification Information</h3>
        <p>To provide push notifications, we may collect notification tokens generated by your device.</p>
      </section>

      <section>
        <h2>3. App Permissions</h2>
        <p>CropVibe may request access to certain device permissions to provide platform functionality.</p>

        <h3>Camera Permission</h3>
        <p>Used to capture photos and videos for posts, reels, profile photos, and other content.</p>

        <h3>Photos and Storage Permission</h3>
        <p>Used to upload, store, and share images, videos, reels, and profile photos.</p>

        <h3>Notification Permission</h3>
        <p>Used to deliver account activity alerts, content interaction notifications, and important updates.</p>

        <h3>Internet Permission</h3>
        <p>Used to connect to CropVibe services and synchronize content.</p>

        <p>
          These permissions are requested only when necessary for application functionality and may be managed
          through device settings.
        </p>
      </section>

      <section>
        <h2>4. How We Use Your Information</h2>
        <p>We use collected information to:</p>
        <ul>
          <li>Create and manage user accounts</li>
          <li>Authenticate users</li>
          <li>Provide platform functionality</li>
          <li>Display profiles, posts, and reels</li>
          <li>Enable likes, comments, followers, and interactions</li>
          <li>Send notifications and updates</li>
          <li>Improve platform performance</li>
          <li>Prevent fraud, abuse, and unauthorized access</li>
          <li>Provide customer support</li>
          <li>Comply with legal obligations</li>
        </ul>

        <h3>Legal Basis for Processing Information</h3>
        <p>We process information for legitimate business purposes, including:</p>
        <ul>
          <li>Providing and maintaining services</li>
          <li>Managing user accounts</li>
          <li>Enabling social interactions</li>
          <li>Improving user experience</li>
          <li>Protecting platform security</li>
          <li>Meeting legal and regulatory requirements</li>
        </ul>
      </section>

      <section>
        <h2>5. Media and Content Storage</h2>
        <p>
          Photos, videos, reels, profile images, and other content uploaded to CropVibe may be securely stored using
          cloud storage services.
        </p>
        <p>
          Content shared on CropVibe may be visible to other users depending on platform functionality and privacy
          settings.
        </p>
        <p>
          Users are responsible for ensuring that content they upload complies with applicable laws and platform
          policies.
        </p>
      </section>

      <section>
        <h2>6. Notifications</h2>
        <p>CropVibe may send notifications related to:</p>
        <ul>
          <li>Likes and comments</li>
          <li>New followers</li>
          <li>Content interactions</li>
          <li>Account activity</li>
          <li>Application updates</li>
          <li>Important announcements</li>
        </ul>
        <p>Users may manage notification preferences through their device settings.</p>
      </section>

      <section>
        <h2>7. Information Sharing</h2>
        <p>We do not sell or rent personal information.</p>
        <p>We may share information with trusted service providers that help operate our platform, including:</p>
        <ul>
          <li>Cloud hosting providers</li>
          <li>Cloud storage providers</li>
          <li>Notification service providers</li>
          <li>Analytics providers</li>
          <li>Security and monitoring providers</li>
        </ul>
        <p>
          We may also disclose information when required by law, court order, governmental request, or to protect
          our legal rights.
        </p>

        <h3>Third-Party Service Providers</h3>
        <p>CropVibe may use trusted providers such as:</p>
        <ul>
          <li>Amazon Web Services (AWS)</li>
          <li>Push Notification Service Providers</li>
          <li>Analytics and Monitoring Providers</li>
        </ul>
        <p>These providers process information only as necessary to provide services on our behalf.</p>

        <h3>International Data Transfers</h3>
        <p>
          Your information may be stored and processed on servers located outside your state, province, or country
          of residence where our service providers operate.
        </p>
        <p>By using CropVibe, you consent to such transfers and processing.</p>
      </section>

      <section>
        <h2>8. Data Retention</h2>
        <p>CropVibe retains personal information only as long as necessary to:</p>
        <ul>
          <li>Provide services</li>
          <li>Maintain platform functionality</li>
          <li>Comply with legal obligations</li>
          <li>Resolve disputes</li>
          <li>Enforce agreements</li>
          <li>Prevent fraud and abuse</li>
        </ul>
        <p>
          When information is no longer required, it will be securely deleted, anonymized, or otherwise disposed of in
          accordance with applicable laws.
        </p>
      </section>

      <section>
        <h2>9. Data Security</h2>
        <p>
          We implement reasonable administrative, technical, and organizational safeguards to protect personal
          information.
        </p>
        <p>
          While we strive to use commercially acceptable means to protect information, no method of electronic
          storage or transmission over the Internet is completely secure. Therefore, we cannot guarantee absolute
          security.
        </p>

        <h3>Data Protection Commitment</h3>
        <p>CropVibe does not sell, rent, or trade personal information to third parties.</p>
        <p>
          We use industry-standard security measures to help protect information against unauthorized access,
          disclosure, alteration, or destruction.
        </p>
      </section>

      <section>
        <h2>10. User Rights</h2>
        <p>Subject to applicable laws, users may have the right to:</p>
        <ul>
          <li>Access their personal information</li>
          <li>Correct inaccurate information</li>
          <li>Request deletion of personal information</li>
          <li>Withdraw consent where applicable</li>
          <li>Request information about how their data is used</li>
        </ul>
        <p>Users may exercise these rights by contacting CropVibe Support.</p>
      </section>

      <section>
        <h2>11. Account Deletion</h2>
        <p>Users may request deletion of their CropVibe account through the application.</p>
        <p>
          <strong>Settings → Account → Delete Account</strong>
        </p>
        <p>When a deletion request is submitted:</p>
        <ul>
          <li>Users may be asked to provide a reason for deletion</li>
          <li>Verification may be performed through the registered mobile number or email address</li>
          <li>Confirmation may be sent through email or SMS</li>
          <li>Requests may take up to 7 business days to process</li>
        </ul>
        <p>
          Upon deletion, profile information, posts, reels, comments, likes, and associated content may be
          permanently removed, except where retention is required for legal, regulatory, fraud prevention, security,
          or compliance purposes.
        </p>
        <p>Users may also contact CropVibe Support regarding account deletion requests.</p>
      </section>

      <section>
        <h2>12. Content Moderation and User Safety</h2>
        <p>CropVibe is committed to maintaining a safe and respectful community.</p>
        <p>
          Users may report content, comments, posts, reels, accounts, or other activity that violates laws, community
          standards, or platform policies.
        </p>
        <p>
          CropVibe reserves the right to review, restrict, suspend, remove, or otherwise take action against content or
          accounts that violate platform rules.
        </p>
      </section>

      <section>
        <h2>13. Children&apos;s Privacy</h2>
        <p>CropVibe is not intended for children under 13 years of age.</p>
        <p>We do not knowingly collect personal information from children under 13 years of age.</p>
        <p>If we become aware that such information has been collected, we will take appropriate steps to remove it.</p>
      </section>

      <section>
        <h2>14. Third-Party Services</h2>
        <p>CropVibe may use third-party services to support platform operations, including:</p>
        <ul>
          <li>Cloud Hosting Services</li>
          <li>Cloud Storage Services</li>
          <li>Push Notification Services</li>
          <li>Analytics Services</li>
        </ul>
        <p>These providers may process information only as necessary to provide their services.</p>
      </section>

      <section>
        <h2>15. Changes to This Privacy Policy</h2>
        <p>We reserve the right to update this Privacy Policy at any time.</p>
        <p>Changes become effective immediately upon publication of the updated Privacy Policy.</p>
        <p>
          Continued use of CropVibe after changes are posted constitutes acceptance of the updated Privacy Policy.
        </p>
      </section>

      <section>
        <h2>16. Contact Us</h2>
        <p>If you have questions regarding this Privacy Policy or your personal information, please contact us:</p>
        <p>
          <strong>CropVibe Support</strong>
          <br />
          Email: <a href="mailto:info@cropvibe.com">info@cropvibe.com</a>
          <br />
          Website: <a href="https://cropvibe.com" target="_blank" rel="noopener noreferrer">https://cropvibe.com</a>
          <br />
          Address: Andhra Pradesh, India
        </p>
      </section>

      <footer className="privacy-policy__footer">
        <p>By using CropVibe, you acknowledge that you have read, understood, and agreed to this Privacy Policy.</p>
      </footer>
    </div>
  );
}
