/** App-wide UI strings (merged into each language in translations.ts). */
export const APP_STRINGS_EN = {
  tabMarket: "Market",
  tabCreate: "Create",
  tabCommunity: "Community",
  tabProfile: "Profile",
  tabFeed: "Feed",
  tabFriends: "Friends",
  tabLive: "Live",
  follow: "Follow",
  following: "Following",
  followBack: "Follow back",
  requested: "Requested",
  followBusy: "...",
  followFailed: "Follow failed",
  followFailedMessage: "Could not send follow request.",
  emptyFriendsTitle: "No reels from people you follow",
  emptyFriendsSub: "Follow more creators to see their reels here.",
  emptyReelsTitle: "No reels yet",
  emptyReelsSub: "Create a reel to get started.",
  emptyLiveTitle: "Live streaming is coming soon",
  emptyLiveSub: "We're building live broadcasts. Stay tuned!",
  emptyFeedTitle: "No feed posts yet",
  emptyNothingTitle: "Nothing here yet",
  emptyDefaultSub: "Create a reel to start filling this section.",
  noLikesYet: "No likes yet",
  noComments: "No Comments",
  communityTitle: "Community",
  communitySub: "Q and A, groups and saved learning",
  qaFeed: "Q and A Feed",
  upvotes: "Upvotes",
  answers: "Answers",
  resolved: "Resolved",
  groups: "Groups",
  groupWomenCircle: "Women Circle",
  groupYoungFarmers: "Young Farmers",
  groupCropGroups: "Crop Groups",
  groupFpoNetwork: "FPO Network",
  myCommunity: "My Community",
  myCommunityDesc: "Saved questions, followed groups and notification settings.",
  ask: "Ask",
  servicesTitle: "Services",
  servicesSub: "Machinery, logistics, experts and advisories",
  serviceMachineryTitle: "Machinery Booking",
  serviceMachineryDesc: "Filter, schedule, 30% advance escrow, completion release.",
  serviceLogisticsTitle: "Logistics Booking",
  serviceLogisticsDesc: "Pickup, estimate, GPS tracking, escrow auto release.",
  serviceExpertTitle: "Expert Consultation",
  serviceExpertDesc: "Browse experts, slots, call summary, optional rating.",
  serviceWeatherTitle: "Weather and Advisory",
  serviceWeatherDesc: "Quick weather view and AI pest alert feed.",
  open: "Open",
  posts: "Posts",
  followers: "Followers",
  profileFollowing: "Following",
  welcome: "Welcome",
  welcomeSub: "Start from the launch screens to create your account.",
  kycVerified: "KYC Verified",
  unavailable: "Unavailable",
  chatUnavailable: "Chat is available only for synced users.",
  registerHelper: "Already registered users can switch to login.",
  loginHelper: "Use the same mobile number used while registering.",
  learnTitle: "Learn & Community",
  learnSub: "Courses, expert guidance, Q&A and farmer groups",
  coursesComingSoon: "This section is coming next. Courses are ready now.",
  loadingCourses: "Loading courses…",
  noCoursesYet: "No courses yet.",
  failedLoadCourses: "Failed to load courses",
  featuredCourse: "FEATURED COURSE",
  marketTitle: "Agri Market",
  marketSearchPlaceholder: "Search produce, farmers, equipment...",
  chooseLanguageTitle: "Choose\nYour Language",
  chooseLanguageSub: "Select your preferred language to personalize your app experience.",
  selectLanguage: "Select Language",
  editProfileTitle: "Edit Profile",
  profileNavTitle: "Profile",
  search: "Search",
  searchUsers: "Search users",
  noUsersFound: "No users found.",
  messagesTitle: "Messages",
  noMessagesTitle: "No messages yet",
  noMessagesSub: "When someone reaches out, you will see it here.",
  sharedReel: "Shared a reel",
  sharedProfile: "Shared a profile",
  yourStory: "Your story",
  messagePlaceholder: "Message...",
  notifications: "Notifications",
  noNotifications: "No notifications yet.",
  accept: "Accept",
  decline: "Decline",
  notifFollowRequest: "{{name}} sent a follow request",
  notifNowFollowing: "{{name}} is now following you.",
  notifAcceptedRequest: "{{name}} accepted your follow request.",
  notifDeclinedRequest: "{{name}} declined your follow request.",
  nameRequired: "Name required",
  nameRequiredMessage: "Please enter your name.",
  profileSaved: "Saved",
  profileUpdated: "Profile updated.",
  saveFailed: "Save failed",
  saveFailedProfile: "Could not update profile.",
  permissionNeeded: "Permission needed",
  photoLibraryPermission: "Please allow photo library access.",
  profilePhotoUpdated: "Profile picture uploaded.",
  photoSavedLocal: "Photo saved locally",
  photoSavedLocalMessage: "Could not upload to server, using local preview.",
  changeProfilePhoto: "Change profile photo",
  uploading: "Uploading…",
  saving: "Saving…",
  done: "Done",
  website: "Website",
  bio: "Bio",
  bioPlaceholder: "Tell people about your farm or work",
  location: "Location",
  locationPlaceholder: "District or region",
  usernamePlaceholder: "username",
  websitePlaceholder: "https://",
  galleryPosts: "Posts",
  galleryReels: "Reels",
  gallerySaved: "Saved",
  galleryTagged: "Tagged",
  savedReelsEmpty: "Saved reels will appear here.",
  addToStory: "Add to story",
  copyLink: "Copy Link",
  shareTo: "Share To..",
  whatsapp: "Whatsapp",
  messenger: "Messenger",
  snapchat: "Snapchat",
  shared: "Shared",
  shareFailed: "Share failed",
  shareFailedProfile: "Could not send profile right now.",
  profileSharedTo: "Profile sent to {{name}}",
  removeFromSaved: "Remove from saved",
  savePost: "Save",
  savedPostsHint: "Saved posts appear in your profile.",
  sendFailed: "Send failed",
  sendFailedReel: "Could not send this reel. Try again.",
  cancel: "Cancel",
  send: "Send",
  savePostFailed: "Could not update saved reels. Please try again.",
  likes: "Likes",
  comments: "Comments",
  addCommentPlaceholder: "Add a comment…",
  replyCancel: "Cancel",
  viewAllComments: "View all {{count}} comments",
  copied: "Copied",
  profileLinkCopied: "Profile link copied.",
  noRecipients: "No recipients",
  shareProfileNoRecipients: "Follow users or get followers to share your profile in chat.",
  noTaggedPosts: "No tagged posts yet.",
  noChatsFound: "No chats found.",
  followBackCapital: "Follow Back",
  notifRepliedComment: "{{name}} replied to your comment{{excerpt}}",
  notifCommentedOn: "{{name}} commented on your {{kind}}{{excerpt}}",
  notifLikedYour: "{{name}} liked your {{kind}}.",
  postKindReel: "reel",
  postKindPost: "post",
  photoUpdatedTitle: "Updated",
  writeReply: "Write a reply…"
} as const;

export const APP_STRINGS_HI: typeof APP_STRINGS_EN = {
  tabMarket: "बाज़ार",
  tabCreate: "बनाएं",
  tabCommunity: "समुदाय",
  tabProfile: "प्रोफाइल",
  tabFeed: "फ़ीड",
  tabFriends: "मित्र",
  tabLive: "लाइव",
  follow: "फ़ॉलो",
  following: "फ़ॉलो कर रहे",
  followBack: "वापस फ़ॉलो",
  requested: "अनुरोधित",
  followBusy: "...",
  followFailed: "फ़ॉलो विफल",
  followFailedMessage: "फ़ॉलो अनुरोध नहीं भेजा जा सका।",
  emptyFriendsTitle: "जिन्हें आप फ़ॉलो करते हैं उनके रील नहीं",
  emptyFriendsSub: "और क्रिएटर्स को फ़ॉलो करें और यहाँ रील देखें।",
  emptyReelsTitle: "अभी कोई रील नहीं",
  emptyReelsSub: "शुरू करने के लिए एक रील बनाएं।",
  emptyLiveTitle: "लाइव स्ट्रीमिंग जल्द आ रही है",
  emptyLiveSub: "हम लाइव प्रसारण बना रहे हैं। बने रहें!",
  emptyFeedTitle: "अभी कोई फ़ीड पोस्ट नहीं",
  emptyNothingTitle: "यहाँ अभी कुछ नहीं",
  emptyDefaultSub: "इस अनुभाग को भरने के लिए एक रील बनाएं।",
  noLikesYet: "अभी कोई लाइक नहीं",
  noComments: "कोई टिप्पणी नहीं",
  communityTitle: "समुदाय",
  communitySub: "प्रश्नोत्तर, समूह और सहेजी गई सीख",
  qaFeed: "प्रश्नोत्तर फ़ीड",
  upvotes: "अपवोट",
  answers: "उत्तर",
  resolved: "हल किया",
  groups: "समूह",
  groupWomenCircle: "महिला मंडली",
  groupYoungFarmers: "युवा किसान",
  groupCropGroups: "फसल समूह",
  groupFpoNetwork: "FPO नेटवर्क",
  myCommunity: "मेरा समुदाय",
  myCommunityDesc: "सहेजे प्रश्न, फ़ॉलो किए समूह और सूचना सेटिंग्स।",
  ask: "पूछें",
  servicesTitle: "सेवाएं",
  servicesSub: "मशीनरी, लॉजिस्टिक्स, विशेषज्ञ और सलाह",
  serviceMachineryTitle: "मशीनरी बुकिंग",
  serviceMachineryDesc: "फ़िल्टर, शेड्यूल, एस्क्रो और पूर्णता पर रिलीज़।",
  serviceLogisticsTitle: "लॉजिस्टिक्स बुकिंग",
  serviceLogisticsDesc: "पिकअप, अनुमान, GPS ट्रैकिंग, ऑटो रिलीज़।",
  serviceExpertTitle: "विशेषज्ञ परामर्श",
  serviceExpertDesc: "विशेषज्ञ, स्लॉट, कॉल सारांश, रेटिंग।",
  serviceWeatherTitle: "मौसम और सलाह",
  serviceWeatherDesc: "मौसम दृश्य और कीट अलर्ट फ़ीड।",
  open: "खोलें",
  posts: "पोस्ट",
  followers: "फ़ॉलोअर्स",
  profileFollowing: "फ़ॉलो कर रहे",
  welcome: "स्वागत है",
  welcomeSub: "खाता बनाने के लिए लॉन्च स्क्रीन से शुरू करें।",
  kycVerified: "KYC सत्यापित",
  unavailable: "उपलब्ध नहीं",
  chatUnavailable: "चैट केवल सिंक उपयोगकर्ताओं के लिए।",
  registerHelper: "पंजीकृत उपयोगकर्ता लॉगिन पर जा सकते हैं।",
  loginHelper: "पंजीकरण में उपयोग किया गया मोबाइल नंबर दर्ज करें।",
  learnTitle: "सीखें और समुदाय",
  learnSub: "कोर्स, मार्गदर्शन, प्रश्नोत्तर और किसान समूह",
  coursesComingSoon: "यह अनुभाग जल्द आएगा। कोर्स तैयार हैं।",
  loadingCourses: "कोर्स लोड हो रहे हैं…",
  noCoursesYet: "अभी कोई कोर्स नहीं।",
  failedLoadCourses: "कोर्स लोड विफल",
  featuredCourse: "विशेष कोर्स",
  marketTitle: "कृषि बाज़ार",
  marketSearchPlaceholder: "उत्पाद, किसान, उपकरण खोजें...",
  chooseLanguageTitle: "अपनी\nभाषा चुनें",
  chooseLanguageSub: "ऐप अनुभव के लिए अपनी पसंदीदा भाषा चुनें।",
  selectLanguage: "भाषा चुनें",
  editProfileTitle: "प्रोफाइल संपादित करें",
  profileNavTitle: "प्रोफाइल",
  search: "खोजें",
  searchUsers: "उपयोगकर्ता खोजें",
  noUsersFound: "कोई उपयोगकर्ता नहीं मिला।",
  messagesTitle: "संदेश",
  noMessagesTitle: "अभी कोई संदेश नहीं",
  noMessagesSub: "जब कोई संपर्क करेगा, यहाँ दिखेगा।",
  sharedReel: "एक रील साझा की",
  sharedProfile: "प्रोफाइल साझा की",
  yourStory: "आपकी स्टोरी",
  messagePlaceholder: "संदेश...",
  notifications: "सूचनाएं",
  noNotifications: "अभी कोई सूचना नहीं।",
  accept: "स्वीकारें",
  decline: "अस्वीकार",
  notifFollowRequest: "{{name}} ने फ़ॉलो अनुरोध भेजा",
  notifNowFollowing: "{{name}} अब आपको फ़ॉलो कर रहे हैं।",
  notifAcceptedRequest: "{{name}} ने आपका फ़ॉलो अनुरोध स्वीकार किया।",
  notifDeclinedRequest: "{{name}} ने आपका फ़ॉलो अनुरोध अस्वीकार किया।",
  nameRequired: "नाम आवश्यक",
  nameRequiredMessage: "कृपया अपना नाम दर्ज करें।",
  profileSaved: "सहेजा गया",
  profileUpdated: "प्रोफाइल अपडेट हुई।",
  saveFailed: "सहेजना विफल",
  saveFailedProfile: "प्रोफाइल अपडेट नहीं हो सकी।",
  permissionNeeded: "अनुमति चाहिए",
  photoLibraryPermission: "कृपया फ़ोटो लाइब्रेरी की अनुमति दें।",
  profilePhotoUpdated: "प्रोफाइल फ़ोटो अपलोड हुई।",
  photoSavedLocal: "फ़ोटो स्थानीय रूप से सहेजी",
  photoSavedLocalMessage: "सर्वर पर अपलोड नहीं हुआ, स्थानीय पूर्वावलोकन।",
  changeProfilePhoto: "प्रोफाइल फ़ोटो बदलें",
  uploading: "अपलोड हो रहा है…",
  saving: "सहेजा जा रहा है…",
  done: "पूर्ण",
  website: "वेबसाइट",
  bio: "बायो",
  bioPlaceholder: "अपने खेत या काम के बारे में बताएं",
  location: "स्थान",
  locationPlaceholder: "जिला या क्षेत्र",
  usernamePlaceholder: "यूज़रनेम",
  websitePlaceholder: "https://",
  galleryPosts: "पोस्ट",
  galleryReels: "रील",
  gallerySaved: "सहेजे",
  galleryTagged: "टैग",
  savedReelsEmpty: "सहेजी रील यहाँ दिखेंगी।",
  addToStory: "स्टोरी में जोड़ें",
  copyLink: "लिंक कॉपी करें",
  shareTo: "साझा करें..",
  whatsapp: "व्हाट्सऐप",
  messenger: "मैसेंजर",
  snapchat: "स्नैपचैट",
  shared: "साझा किया",
  shareFailed: "साझा विफल",
  shareFailedProfile: "प्रोफाइल अभी नहीं भेजी जा सकी।",
  profileSharedTo: "प्रोफाइल {{name}} को भेजी",
  removeFromSaved: "सहेजे से हटाएं",
  savePost: "सहेजें",
  savedPostsHint: "सहेजी पोस्ट आपकी प्रोफाइल में दिखती हैं।",
  sendFailed: "भेजना विफल",
  sendFailedReel: "रील नहीं भेजी जा सकी। पुनः प्रयास करें।",
  cancel: "रद्द करें",
  send: "भेजें",
  savePostFailed: "सहेजी रील अपडेट नहीं हो सकी।",
  likes: "लाइक",
  comments: "टिप्पणियाँ",
  addCommentPlaceholder: "टिप्पणी जोड़ें…",
  replyCancel: "रद्द करें",
  viewAllComments: "सभी {{count}} टिप्पणियाँ देखें",
  copied: "कॉपी हो गया",
  profileLinkCopied: "प्रोफाइल लिंक कॉपी हो गई।",
  noRecipients: "कोई प्राप्तकर्ता नहीं",
  shareProfileNoRecipients: "चैट में प्रोफाइल साझा करने के लिए उपयोगकर्ताओं को फ़ॉलो करें।",
  noTaggedPosts: "अभी कोई टैग पोस्ट नहीं।",
  noChatsFound: "कोई चैट नहीं मिली।",
  followBackCapital: "वापस फ़ॉलो करें",
  notifRepliedComment: "{{name}} ने आपकी टिप्पणी का जवाब दिया{{excerpt}}",
  notifCommentedOn: "{{name}} ने आपके {{kind}} पर टिप्पणी की{{excerpt}}",
  notifLikedYour: "{{name}} ने आपके {{kind}} को लाइक किया।",
  postKindReel: "रील",
  postKindPost: "पोस्ट",
  photoUpdatedTitle: "अपडेट",
  writeReply: "जवाब लिखें…"
};

export const APP_STRINGS_TE: typeof APP_STRINGS_EN = {
  tabMarket: "మార్కెట్",
  tabCreate: "సృష్టించు",
  tabCommunity: "సమూహం",
  tabProfile: "ప్రొఫైల్",
  tabFeed: "ఫీడ్",
  tabFriends: "స్నేహితులు",
  tabLive: "లైవ్",
  follow: "ఫాలో",
  following: "ఫాలో అవుతున్నారు",
  followBack: "తిరిగి ఫాలో",
  requested: "అభ్యర్థించబడింది",
  followBusy: "...",
  followFailed: "ఫాలో విఫలమైంది",
  followFailedMessage: "ఫాలో అభ్యర్థన పంపలేకపోయాము.",
  emptyFriendsTitle: "మీరు ఫాలో చేసిన వారి రీల్స్ లేవు",
  emptyFriendsSub: "మరిన్ని క్రియేటర్లను ఫాలో చేసి ఇక్కడ చూడండి.",
  emptyReelsTitle: "ఇంకా రీల్స్ లేవు",
  emptyReelsSub: "ప్రారంభించడానికి రీల్ సృష్టించండి.",
  emptyLiveTitle: "లైవ్ స్ట్రీమింగ్ త్వరలో",
  emptyLiveSub: "లైవ్ ప్రసారాలు తయారవుతున్నాయి. వేచి ఉండండి!",
  emptyFeedTitle: "ఇంకా ఫీడ్ పోస్టులు లేవు",
  emptyNothingTitle: "ఇక్కడ ఇంకా ఏమీ లేదు",
  emptyDefaultSub: "ఈ విభాగాన్ని నింపడానికి రీల్ సృష్టించండి.",
  noLikesYet: "ఇంకా లైక్‌లు లేవు",
  noComments: "కామెంట్‌లు లేవు",
  communityTitle: "సమూహం",
  communitySub: "ప్రశ్నోత్తరం, గ్రూపులు మరియు నేర్చుకోవడం",
  qaFeed: "ప్రశ్నోత్తర ఫీడ్",
  upvotes: "అప్‌వోట్లు",
  answers: "సమాధానాలు",
  resolved: "పరిష్కరించబడింది",
  groups: "గ్రూపులు",
  groupWomenCircle: "మహిళా వృత్తం",
  groupYoungFarmers: "యువ రైతులు",
  groupCropGroups: "పంట గ్రూపులు",
  groupFpoNetwork: "FPO నెట్‌వర్క్",
  myCommunity: "నా సమూహం",
  myCommunityDesc: "సేవ్ చేసిన ప్రశ్నలు, గ్రూపులు మరియు నోటిఫికేషన్ సెట్టింగ్‌లు.",
  ask: "అడగండి",
  servicesTitle: "సేవలు",
  servicesSub: "మెషినరీ, లాజిస్టిక్స్, నిపుణులు మరియు సలహాలు",
  serviceMachineryTitle: "మెషినరీ బుకింగ్",
  serviceMachineryDesc: "ఫిల్టర్, షెడ్యూల్, ఎస్క్రో మరియు పూర్తి రిలీజ్.",
  serviceLogisticsTitle: "లాజిస్టిక్స్ బుకింగ్",
  serviceLogisticsDesc: "పికప్, అంచనా, GPS ట్రాకింగ్, ఆటో రిలీజ్.",
  serviceExpertTitle: "నిపుణుల సంప్రదింపు",
  serviceExpertDesc: "నిపుణులు, స్లాట్లు, కాల్ సారాంశం, రేటింగ్.",
  serviceWeatherTitle: "వాతావరణం మరియు సలహా",
  serviceWeatherDesc: "వాతావరణ వీక్షణ మరియు తెగులు అలర్ట్ ఫీడ్.",
  open: "తెరవండి",
  posts: "పోస్టులు",
  followers: "ఫాలోవర్లు",
  profileFollowing: "ఫాలో అవుతున్నారు",
  welcome: "స్వాగతం",
  welcomeSub: "ఖాతా సృష్టించడానికి లాంచ్ స్క్రీన్ల నుండి ప్రారంభించండి.",
  kycVerified: "KYC ధృవీకరించబడింది",
  unavailable: "అందుబాటులో లేదు",
  chatUnavailable: "చాట్ సింక్ చేసిన వినియోగదారులకు మాత్రమే.",
  registerHelper: "నమోదు చేసిన వారు లాగిన్‌కు మారవచ్చు.",
  loginHelper: "నమోదు సమయంలో ఉపయోగించిన మొబైల్ నంబర్ ఉపయోగించండి.",
  learnTitle: "నేర్చుకోండి & సమూహం",
  learnSub: "కోర్సులు, మార్గదర్శకత్వం, ప్రశ్నోత్తరం మరియు రైతు గ్రూపులు",
  coursesComingSoon: "ఈ విభాగం త్వరలో. కోర్సులు సిద్ధంగా ఉన్నాయి.",
  loadingCourses: "కోర్సులు లోడ్ అవుతున్నాయి…",
  noCoursesYet: "ఇంకా కోర్సులు లేవు.",
  failedLoadCourses: "కోర్సులు లోడ్ చేయడం విఫలమైంది",
  featuredCourse: "ఫీచర్ కోర్స్",
  marketTitle: "వ్యవసాయ మార్కెట్",
  marketSearchPlaceholder: "ఉత్పత్తి, రైతులు, పరికరాలు శోధించండి...",
  chooseLanguageTitle: "మీ\nభాష ఎంచుకోండి",
  chooseLanguageSub: "అనువర్తన అనుభవానికి మీ ఇష్టమైన భాష ఎంచుకోండి.",
  selectLanguage: "భాష ఎంచుకోండి",
  editProfileTitle: "ప్రొఫైల్ ఎడిట్",
  profileNavTitle: "ప్రొఫైల్",
  search: "శోధించండి",
  searchUsers: "వినియోగదారులను శోధించండి",
  noUsersFound: "వినియోగదారులు కనుగొనబడలేదు.",
  messagesTitle: "సందేశాలు",
  noMessagesTitle: "ఇంకా సందేశాలు లేవు",
  noMessagesSub: "ఎవరైనా సంప్రదించినప్పుడు ఇక్కడ కనిపిస్తుంది.",
  sharedReel: "రీల్ షేర్ చేశారు",
  sharedProfile: "ప్రొఫైల్ షేర్ చేశారు",
  yourStory: "మీ స్టోరీ",
  messagePlaceholder: "సందేశం...",
  notifications: "నోటిఫికేషన్లు",
  noNotifications: "ఇంకా నోటిఫికేషన్లు లేవు.",
  accept: "అంగీకరించు",
  decline: "తిరస్కరించు",
  notifFollowRequest: "{{name}} ఫాలో అభ్యర్థన పంపారు",
  notifNowFollowing: "{{name}} ఇప్పుడు మిమ్మల్ని ఫాలో అవుతున్నారు.",
  notifAcceptedRequest: "{{name}} మీ ఫాలో అభ్యర్థనను అంగీకరించారు.",
  notifDeclinedRequest: "{{name}} మీ ఫాలో అభ్యర్థనను తిరస్కరించారు.",
  nameRequired: "పేరు అవసరం",
  nameRequiredMessage: "దయచేసి మీ పేరు నమోదు చేయండి.",
  profileSaved: "సేవ్ చేయబడింది",
  profileUpdated: "ప్రొఫైల్ నవీకరించబడింది.",
  saveFailed: "సేవ్ విఫలమైంది",
  saveFailedProfile: "ప్రొఫైల్ నవీకరించలేకపోయాము.",
  permissionNeeded: "అనుమతి అవసరం",
  photoLibraryPermission: "ఫోటో లైబ్రరీ అనుమతి ఇవ్వండి.",
  profilePhotoUpdated: "ప్రొఫైల్ ఫోటో అప్‌లోడ్ అయింది.",
  photoSavedLocal: "ఫోటో స్థానికంగా సేవ్",
  photoSavedLocalMessage: "సర్వర్‌కు అప్‌లోడ్ కాలేదు, స్థానిక ప్రివ్యూ.",
  changeProfilePhoto: "ప్రొఫైల్ ఫోటో మార్చండి",
  uploading: "అప్‌లోడ్ అవుతోంది…",
  saving: "సేవ్ అవుతోంది…",
  done: "పూర్తి",
  website: "వెబ్‌సైట్",
  bio: "బయో",
  bioPlaceholder: "మీ పొలం లేదా పని గురించి చెప్పండి",
  location: "స్థానం",
  locationPlaceholder: "జిల్లా లేదా ప్రాంతం",
  usernamePlaceholder: "యూజర్‌నేమ్",
  websitePlaceholder: "https://",
  galleryPosts: "పోస్టులు",
  galleryReels: "రీల్స్",
  gallerySaved: "సేవ్",
  galleryTagged: "ట్యాగ్",
  savedReelsEmpty: "సేవ్ చేసిన రీల్స్ ఇక్కడ కనిపిస్తాయి.",
  addToStory: "స్టోరీకి జోడించు",
  copyLink: "లింక్ కాపీ",
  shareTo: "షేర్ చేయండి..",
  whatsapp: "వాట్సాప్",
  messenger: "మెసెంజర్",
  snapchat: "స్నాప్‌చాట్",
  shared: "షేర్ చేయబడింది",
  shareFailed: "షేర్ విఫలమైంది",
  shareFailedProfile: "ప్రొఫైల్ ఇప్పుడు పంపలేకపోయాము.",
  profileSharedTo: "ప్రొఫైల్ {{name}} కు పంపబడింది",
  removeFromSaved: "సేవ్ నుండి తీసివేయి",
  savePost: "సేవ్",
  savedPostsHint: "సేవ్ పోస్టులు మీ ప్రొఫైల్‌లో కనిపిస్తాయి.",
  sendFailed: "పంపడం విఫలమైంది",
  sendFailedReel: "రీల్ పంపలేకపోయాము. మళ్లీ ప్రయత్నించండి.",
  cancel: "రద్దు",
  send: "పంపు",
  savePostFailed: "సేవ్ రీల్స్ నవీకరించలేకపోయాము.",
  likes: "లైక్‌లు",
  comments: "కామెంట్‌లు",
  addCommentPlaceholder: "కామెంట్ జోడించండి…",
  replyCancel: "రద్దు",
  viewAllComments: "అన్ని {{count}} కామెంట్‌లు చూడండి",
  copied: "కాపీ అయింది",
  profileLinkCopied: "ప్రొఫైల్ లింక్ కాపీ అయింది.",
  noRecipients: "గ్రహీతలు లేరు",
  shareProfileNoRecipients: "చాట్‌లో ప్రొఫైల్ షేర్ చేయడానికి వినియోగదారులను ఫాలో చేయండి.",
  noTaggedPosts: "ఇంకా ట్యాగ్ పోస్టులు లేవు.",
  noChatsFound: "చాట్‌లు కనుగొనబడలేదు.",
  followBackCapital: "తిరిగి ఫాలో",
  notifRepliedComment: "{{name}} మీ కామెంట్‌కు సమాధానం ఇచ్చారు{{excerpt}}",
  notifCommentedOn: "{{name}} మీ {{kind}}పై కామెంట్ చేశారు{{excerpt}}",
  notifLikedYour: "{{name}} మీ {{kind}}ను లైక్ చేశారు.",
  postKindReel: "రీల్",
  postKindPost: "పోస్ట్",
  photoUpdatedTitle: "నవీకరించబడింది",
  writeReply: "సమాధానం రాయండి…"
};
