/** Home top tab — product name "Drops" in each script (not English in every locale). */
const TAB_FEED_LABEL = {
  en: "Drops",
  hi: "ड्रॉप्स",
  te: "డ్రాప్స్",
  kn: "ಡ್ರಾಪ್ಸ್",
  ml: "ഡ്രോപ്സ്",
  ta: "ட்ராப்ஸ்",
  mr: "ड्रॉप्स",
  bn: "ড্রপস"
} as const;

const EMPTY_DROPS_TITLE = {
  en: "No drops yet",
  hi: "अभी कोई ड्रॉप्स पोस्ट नहीं",
  te: "ఇంకా డ్రాప్స్ పోస్టులు లేవు",
  kn: "ಇನ್ನೂ ಡ್ರಾಪ್ಸ್ ಪೋಸ್ಟ್‌ಗಳಿಲ್ಲ",
  ml: "ഇതുവരെ ഡ്രോപ്സ് പോസ്റ്റുകൾ ഇല്ല",
  ta: "இதுவரை ட்ராப்ஸ் பதிவுகள் இல்லை",
  mr: "अजून ड्रॉप्स पोस्ट नाहीत",
  bn: "এখনও কোনো ড্রপস পোস্ট নেই"
} as const;

/** App-wide UI strings (merged into each language in translations.ts). */
export const APP_STRINGS_EN = {
  tabMarket: "Market",
  tabCreate: "Create",
  tabCommunity: "Community",
  tabProfile: "Profile",
  tabFeed: TAB_FEED_LABEL.en,
  tabFriends: "Friends",
  tabLive: "Live",
  follow: "Follow",
  following: "Following",
  followBack: "Follow back",
  requested: "Requested",
  followBusy: "...",
  followFailed: "Follow failed",
  followFailedMessage: "Could not send follow request.",
  emptyFriendsTitle: "No reels from people you follow",
  emptyFriendsSub: "Follow more creators to see their reels here.",
  emptyReelsTitle: "No reels yet",
  emptyReelsSub: "Create a reel to get started.",
  emptyLiveTitle: "Live streaming is coming soon",
  emptyLiveSub: "We're building live broadcasts. Stay tuned!",
  emptyFeedTitle: EMPTY_DROPS_TITLE.en,
  emptyNothingTitle: "Nothing here yet",
  emptyDefaultSub: "Create a reel to start filling this section.",
  noLikesYet: "No likes yet",
  noComments: "No Comments",
  communityTitle: "Community",
  communitySub: "Q and A, groups and saved learning",
  qaFeed: "Q and A Feed",
  upvotes: "Upvotes",
  answers: "Answers",
  resolved: "Resolved",
  groups: "Groups",
  groupWomenCircle: "Women Circle",
  groupYoungFarmers: "Young Farmers",
  groupCropGroups: "Crop Groups",
  groupFpoNetwork: "FPO Network",
  myCommunity: "My Community",
  myCommunityDesc: "Saved questions, followed groups and notification settings.",
  ask: "Ask",
  servicesTitle: "Services",
  servicesSub: "Machinery, logistics, experts and advisories",
  serviceMachineryTitle: "Machinery Booking",
  serviceMachineryDesc: "Filter, schedule, 30% advance escrow, completion release.",
  serviceLogisticsTitle: "Logistics Booking",
  serviceLogisticsDesc: "Pickup, estimate, GPS tracking, escrow auto release.",
  serviceExpertTitle: "Expert Consultation",
  serviceExpertDesc: "Browse experts, slots, call summary, optional rating.",
  serviceWeatherTitle: "Weather and Advisory",
  serviceWeatherDesc: "Quick weather view and AI pest alert feed.",
  open: "Open",
  posts: "Posts",
  followers: "Followers",
  profileFollowing: "Following",
  welcome: "Welcome",
  welcomeSub: "Start from the launch screens to create your account.",
  kycVerified: "KYC Verified",
  unavailable: "Unavailable",
  chatUnavailable: "Chat is available only for synced users.",
  registerHelper: "Already registered users can switch to login.",
  loginHelper: "Use the same mobile number used while registering.",
  learnTitle: "Learn & Community",
  learnSub: "Courses, expert guidance, Q&A and farmer groups",
  coursesComingSoon: "This section is coming next. Courses are ready now.",
  loadingCourses: "Loading courses…",
  noCoursesYet: "No courses yet.",
  failedLoadCourses: "Failed to load courses",
  featuredCourse: "FEATURED COURSE",
  marketTitle: "Agri Market",
  marketSearchPlaceholder: "Search produce, farmers, equipment...",
  chooseLanguageTitle: "Choose\nYour Language",
  chooseLanguageSub: "Select your preferred language to personalize your app experience.",
  selectLanguage: "Select Language",
  editProfileTitle: "Edit Profile",
  profileNavTitle: "Profile",
  search: "Search",
  searchUsers: "Search users",
  noUsersFound: "No users found.",
  messagesTitle: "Messages",
  noMessagesTitle: "No messages yet",
  noMessagesSub: "When someone reaches out, you will see it here.",
  sharedReel: "Shared a reel",
  sharedMedia: "Photo",
  voiceMessage: "Voice message",
  recordingVoice: "Recording...",
  galleryPermissionMsg: "Allow photo library access to send images.",
  cameraPermissionMsg: "Allow camera access to take photos.",
  micPermissionMsg: "Allow microphone access to send voice notes.",
  voiceNoteWebUnavailable: "Voice notes are available in the mobile app.",
  voiceRecordFailed: "Could not record voice note.",
  sharedLive: "Shared a live",
  sharedProfile: "Shared a profile",
  yourStory: "Your story",
  messagePlaceholder: "Message...",
  notifications: "Notifications",
  noNotifications: "No notifications yet.",
  accept: "Accept",
  decline: "Decline",
  notifFollowRequest: "{{name}} sent a follow request",
  notifNowFollowing: "{{name}} is now following you.",
  notifAcceptedRequest: "{{name}} accepted your follow request.",
  notifDeclinedRequest: "{{name}} declined your follow request.",
  nameRequired: "Name required",
  nameRequiredMessage: "Please enter your name.",
  profileSaved: "Saved",
  profileUpdated: "Profile updated.",
  saveFailed: "Save failed",
  saveFailedProfile: "Could not update profile.",
  permissionNeeded: "Permission needed",
  photoLibraryPermission: "Please allow photo library access.",
  profilePhotoUpdated: "Profile picture uploaded.",
  photoSavedLocal: "Photo saved locally",
  photoSavedLocalMessage: "Could not upload to server, using local preview.",
  changeProfilePhoto: "Change profile photo",
  uploading: "Uploading…",
  saving: "Saving…",
  done: "Done",
  website: "Website",
  bio: "Bio",
  bioPlaceholder: "Tell people about your farm or work",
  location: "Location",
  locationPlaceholder: "District or region",
  usernamePlaceholder: "username",
  websitePlaceholder: "https://",
  galleryPosts: "Posts",
  galleryReels: "Reels",
  gallerySaved: "Saved",
  galleryTagged: "Tagged",
  savedReelsEmpty: "Saved reels will appear here.",
  addToStory: "Add to story",
  copyLink: "Copy Link",
  shareTo: "Share To..",
  whatsapp: "Whatsapp",
  messenger: "Messenger",
  snapchat: "Snapchat",
  telegram: "Telegram",
  x: "X",
  shared: "Shared",
  shareFailed: "Share failed",
  shareFailedProfile: "Could not send profile right now.",
  profileSharedTo: "Profile sent to {{name}}",
  removeFromSaved: "Remove from saved",
  savePost: "Save",
  savedPostsHint: "Saved posts appear in your profile.",
  sendFailed: "Send failed",
  sendFailedReel: "Could not send this reel. Try again.",
  cancel: "Cancel",
  send: "Send",
  savePostFailed: "Could not update saved reels. Please try again.",
  likes: "Likes",
  comments: "Comments",
  addCommentPlaceholder: "Add a comment…",
  replyCancel: "Cancel",
  viewAllComments: "View all {{count}} comments",
  copied: "Copied",
  profileLinkCopied: "Profile link copied.",
  noRecipients: "No recipients",
  shareProfileNoRecipients: "Follow users or get followers to share your profile in chat.",
  noTaggedPosts: "No tagged posts yet.",
  noChatsFound: "No chats found.",
  followBackCapital: "Follow Back",
  notifRepliedComment: "{{name}} replied to your comment{{excerpt}}",
  notifCommentedOn: "{{name}} commented on your {{kind}}{{excerpt}}",
  notifLikedYour: "{{name}} liked your {{kind}}.",
  postKindReel: "reel",
  postKindPost: "post",
  photoUpdatedTitle: "Updated",
  writeReply: "Write a reply…",
  you: "You",
  userWithId: "User {{id}}",
  originalAudio: "Original audio",
  feedDemoTest: "Test",
  feedDemoTestVideoCapture: "Test video capture",
  feedTestingFromCamera: "Testing from mobile app camera",
  farmerDefaultName: "Farmer",
  likesCountLabel: "{{count}} likes",
  shareReelMessage: "{{name}} shared a reel on Cropvibe",
  reportUserPrompt: "Why are you reporting {{name}}?"
} as const;

export const APP_STRINGS_HI: typeof APP_STRINGS_EN = {
  tabMarket: "बाज़ार",
  tabCreate: "बनाएं",
  tabCommunity: "समुदाय",
  tabProfile: "प्रोफाइल",
  tabFeed: TAB_FEED_LABEL.hi,
  tabFriends: "मित्र",
  tabLive: "लाइव",
  follow: "फ़ॉलो",
  following: "फ़ॉलो कर रहे",
  followBack: "वापस फ़ॉलो",
  requested: "अनुरोधित",
  followBusy: "...",
  followFailed: "फ़ॉलो विफल",
  followFailedMessage: "फ़ॉलो अनुरोध नहीं भेजा जा सका।",
  emptyFriendsTitle: "जिन्हें आप फ़ॉलो करते हैं उनके रील नहीं",
  emptyFriendsSub: "और क्रिएटर्स को फ़ॉलो करें और यहाँ रील देखें।",
  emptyReelsTitle: "अभी कोई रील नहीं",
  emptyReelsSub: "शुरू करने के लिए एक रील बनाएं।",
  emptyLiveTitle: "लाइव स्ट्रीमिंग जल्द आ रही है",
  emptyLiveSub: "हम लाइव प्रसारण बना रहे हैं। बने रहें!",
  emptyFeedTitle: EMPTY_DROPS_TITLE.hi,
  emptyNothingTitle: "यहाँ अभी कुछ नहीं",
  emptyDefaultSub: "इस अनुभाग को भरने के लिए एक रील बनाएं।",
  noLikesYet: "अभी कोई लाइक नहीं",
  noComments: "कोई टिप्पणी नहीं",
  communityTitle: "समुदाय",
  communitySub: "प्रश्नोत्तर, समूह और सहेजी गई सीख",
  qaFeed: "प्रश्नोत्तर फ़ीड",
  upvotes: "अपवोट",
  answers: "उत्तर",
  resolved: "हल किया",
  groups: "समूह",
  groupWomenCircle: "महिला मंडली",
  groupYoungFarmers: "युवा किसान",
  groupCropGroups: "फसल समूह",
  groupFpoNetwork: "FPO नेटवर्क",
  myCommunity: "मेरा समुदाय",
  myCommunityDesc: "सहेजे प्रश्न, फ़ॉलो किए समूह और सूचना सेटिंग्स।",
  ask: "पूछें",
  servicesTitle: "सेवाएं",
  servicesSub: "मशीनरी, लॉजिस्टिक्स, विशेषज्ञ और सलाह",
  serviceMachineryTitle: "मशीनरी बुकिंग",
  serviceMachineryDesc: "फ़िल्टर, शेड्यूल, एस्क्रो और पूर्णता पर रिलीज़।",
  serviceLogisticsTitle: "लॉजिस्टिक्स बुकिंग",
  serviceLogisticsDesc: "पिकअप, अनुमान, GPS ट्रैकिंग, ऑटो रिलीज़।",
  serviceExpertTitle: "विशेषज्ञ परामर्श",
  serviceExpertDesc: "विशेषज्ञ, स्लॉट, कॉल सारांश, रेटिंग।",
  serviceWeatherTitle: "मौसम और सलाह",
  serviceWeatherDesc: "मौसम दृश्य और कीट अलर्ट फ़ीड।",
  open: "खोलें",
  posts: "पोस्ट",
  followers: "फ़ॉलोअर्स",
  profileFollowing: "फ़ॉलो कर रहे",
  welcome: "स्वागत है",
  welcomeSub: "खाता बनाने के लिए लॉन्च स्क्रीन से शुरू करें।",
  kycVerified: "KYC सत्यापित",
  unavailable: "उपलब्ध नहीं",
  chatUnavailable: "चैट केवल सिंक उपयोगकर्ताओं के लिए।",
  registerHelper: "पंजीकृत उपयोगकर्ता लॉगिन पर जा सकते हैं।",
  loginHelper: "पंजीकरण में उपयोग किया गया मोबाइल नंबर दर्ज करें।",
  learnTitle: "सीखें और समुदाय",
  learnSub: "कोर्स, मार्गदर्शन, प्रश्नोत्तर और किसान समूह",
  coursesComingSoon: "यह अनुभाग जल्द आएगा। कोर्स तैयार हैं।",
  loadingCourses: "कोर्स लोड हो रहे हैं…",
  noCoursesYet: "अभी कोई कोर्स नहीं।",
  failedLoadCourses: "कोर्स लोड विफल",
  featuredCourse: "विशेष कोर्स",
  marketTitle: "कृषि बाज़ार",
  marketSearchPlaceholder: "उत्पाद, किसान, उपकरण खोजें...",
  chooseLanguageTitle: "अपनी\nभाषा चुनें",
  chooseLanguageSub: "ऐप अनुभव के लिए अपनी पसंदीदा भाषा चुनें।",
  selectLanguage: "भाषा चुनें",
  editProfileTitle: "प्रोफाइल संपादित करें",
  profileNavTitle: "प्रोफाइल",
  search: "खोजें",
  searchUsers: "उपयोगकर्ता खोजें",
  noUsersFound: "कोई उपयोगकर्ता नहीं मिला।",
  messagesTitle: "संदेश",
  noMessagesTitle: "अभी कोई संदेश नहीं",
  noMessagesSub: "जब कोई संपर्क करेगा, यहाँ दिखेगा।",
  sharedReel: "एक रील साझा की",
  sharedMedia: "फ़ोटो",
  voiceMessage: "वॉइस संदेश",
  recordingVoice: "रिकॉर्ड हो रहा है...",
  galleryPermissionMsg: "छवियाँ भेजने के लिए गैलरी की अनुमति दें।",
  cameraPermissionMsg: "फ़ोटो लेने के लिए कैमरा की अनुमति दें।",
  micPermissionMsg: "वॉइस नोट भेजने के लिए माइक की अनुमति दें।",
  voiceNoteWebUnavailable: "वॉइस नोट मोबाइल ऐप में उपलब्ध हैं।",
  voiceRecordFailed: "वॉइस नोट रिकॉर्ड नहीं हो सका।",
  sharedProfile: "प्रोफाइल साझा की",
  yourStory: "आपकी स्टोरी",
  messagePlaceholder: "संदेश...",
  notifications: "सूचनाएं",
  noNotifications: "अभी कोई सूचना नहीं।",
  accept: "स्वीकारें",
  decline: "अस्वीकार",
  notifFollowRequest: "{{name}} ने फ़ॉलो अनुरोध भेजा",
  notifNowFollowing: "{{name}} अब आपको फ़ॉलो कर रहे हैं।",
  notifAcceptedRequest: "{{name}} ने आपका फ़ॉलो अनुरोध स्वीकार किया।",
  notifDeclinedRequest: "{{name}} ने आपका फ़ॉलो अनुरोध अस्वीकार किया।",
  nameRequired: "नाम आवश्यक",
  nameRequiredMessage: "कृपया अपना नाम दर्ज करें।",
  profileSaved: "सहेजा गया",
  profileUpdated: "प्रोफाइल अपडेट हुई।",
  saveFailed: "सहेजना विफल",
  saveFailedProfile: "प्रोफाइल अपडेट नहीं हो सकी।",
  permissionNeeded: "अनुमति चाहिए",
  photoLibraryPermission: "कृपया फ़ोटो लाइब्रेरी की अनुमति दें।",
  profilePhotoUpdated: "प्रोफाइल फ़ोटो अपलोड हुई।",
  photoSavedLocal: "फ़ोटो स्थानीय रूप से सहेजी",
  photoSavedLocalMessage: "सर्वर पर अपलोड नहीं हुआ, स्थानीय पूर्वावलोकन।",
  changeProfilePhoto: "प्रोफाइल फ़ोटो बदलें",
  uploading: "अपलोड हो रहा है…",
  saving: "सहेजा जा रहा है…",
  done: "पूर्ण",
  website: "वेबसाइट",
  bio: "बायो",
  bioPlaceholder: "अपने खेत या काम के बारे में बताएं",
  location: "स्थान",
  locationPlaceholder: "जिला या क्षेत्र",
  usernamePlaceholder: "यूज़रनेम",
  websitePlaceholder: "https://",
  galleryPosts: "पोस्ट",
  galleryReels: "रील",
  gallerySaved: "सहेजे",
  galleryTagged: "टैग",
  savedReelsEmpty: "सहेजी रील यहाँ दिखेंगी।",
  addToStory: "स्टोरी में जोड़ें",
  copyLink: "लिंक कॉपी करें",
  shareTo: "साझा करें..",
  whatsapp: "व्हाट्सऐप",
  messenger: "मैसेंजर",
  snapchat: "स्नैपचैट",
  telegram: "टेलीग्राम",
  x: "X",
  shared: "साझा किया",
  shareFailed: "साझा विफल",
  shareFailedProfile: "प्रोफाइल अभी नहीं भेजी जा सकी।",
  profileSharedTo: "प्रोफाइल {{name}} को भेजी",
  removeFromSaved: "सहेजे से हटाएं",
  savePost: "सहेजें",
  savedPostsHint: "सहेजी पोस्ट आपकी प्रोफाइल में दिखती हैं।",
  sendFailed: "भेजना विफल",
  sendFailedReel: "रील नहीं भेजी जा सकी। पुनः प्रयास करें।",
  cancel: "रद्द करें",
  send: "भेजें",
  savePostFailed: "सहेजी रील अपडेट नहीं हो सकी।",
  likes: "लाइक",
  comments: "टिप्पणियाँ",
  addCommentPlaceholder: "टिप्पणी जोड़ें…",
  replyCancel: "रद्द करें",
  viewAllComments: "सभी {{count}} टिप्पणियाँ देखें",
  copied: "कॉपी हो गया",
  profileLinkCopied: "प्रोफाइल लिंक कॉपी हो गई।",
  noRecipients: "कोई प्राप्तकर्ता नहीं",
  shareProfileNoRecipients: "चैट में प्रोफाइल साझा करने के लिए उपयोगकर्ताओं को फ़ॉलो करें।",
  noTaggedPosts: "अभी कोई टैग पोस्ट नहीं।",
  noChatsFound: "कोई चैट नहीं मिली।",
  followBackCapital: "वापस फ़ॉलो करें",
  notifRepliedComment: "{{name}} ने आपकी टिप्पणी का जवाब दिया{{excerpt}}",
  notifCommentedOn: "{{name}} ने आपके {{kind}} पर टिप्पणी की{{excerpt}}",
  notifLikedYour: "{{name}} ने आपके {{kind}} को लाइक किया।",
  postKindReel: "रील",
  postKindPost: "पोस्ट",
  photoUpdatedTitle: "अपडेट",
  writeReply: "जवाब लिखें…",
  you: "आप",
  userWithId: "उपयोगकर्ता {{id}}",
  originalAudio: "मूल ऑडियो",
  feedDemoTest: "टेस्ट",
  feedDemoTestVideoCapture: "टेस्ट वीडियो कैप्चर",
  feedTestingFromCamera: "मोबाइल ऐप कैमरा से परीक्षण",
  farmerDefaultName: "किसान",
  likesCountLabel: "{{count}} लाइक",
  shareReelMessage: "{{name}} ने Cropvibe पर एक रील साझा की",
  reportUserPrompt: "आप {{name}} की रिपोर्ट क्यों कर रहे हैं?"
};

export const APP_STRINGS_TE: typeof APP_STRINGS_EN = {
  tabMarket: "మార్కెట్",
  tabCreate: "సృష్టించు",
  tabCommunity: "సమూహం",
  tabProfile: "ప్రొఫైల్",
  tabFeed: TAB_FEED_LABEL.te,
  tabFriends: "స్నేహితులు",
  tabLive: "లైవ్",
  follow: "ఫాలో",
  following: "ఫాలో అవుతున్నారు",
  followBack: "తిరిగి ఫాలో",
  requested: "అభ్యర్థించబడింది",
  followBusy: "...",
  followFailed: "ఫాలో విఫలమైంది",
  followFailedMessage: "ఫాలో అభ్యర్థన పంపలేకపోయాము.",
  emptyFriendsTitle: "మీరు ఫాలో చేసిన వారి రీల్స్ లేవు",
  emptyFriendsSub: "మరిన్ని క్రియేటర్లను ఫాలో చేసి ఇక్కడ చూడండి.",
  emptyReelsTitle: "ఇంకా రీల్స్ లేవు",
  emptyReelsSub: "ప్రారంభించడానికి రీల్ సృష్టించండి.",
  emptyLiveTitle: "లైవ్ స్ట్రీమింగ్ త్వరలో",
  emptyLiveSub: "లైవ్ ప్రసారాలు తయారవుతున్నాయి. వేచి ఉండండి!",
  emptyFeedTitle: EMPTY_DROPS_TITLE.te,
  emptyNothingTitle: "ఇక్కడ ఇంకా ఏమీ లేదు",
  emptyDefaultSub: "ఈ విభాగాన్ని నింపడానికి రీల్ సృష్టించండి.",
  noLikesYet: "ఇంకా లైక్‌లు లేవు",
  noComments: "కామెంట్‌లు లేవు",
  communityTitle: "సమూహం",
  communitySub: "ప్రశ్నోత్తరం, గ్రూపులు మరియు నేర్చుకోవడం",
  qaFeed: "ప్రశ్నోత్తర ఫీడ్",
  upvotes: "అప్‌వోట్లు",
  answers: "సమాధానాలు",
  resolved: "పరిష్కరించబడింది",
  groups: "గ్రూపులు",
  groupWomenCircle: "మహిళా వృత్తం",
  groupYoungFarmers: "యువ రైతులు",
  groupCropGroups: "పంట గ్రూపులు",
  groupFpoNetwork: "FPO నెట్‌వర్క్",
  myCommunity: "నా సమూహం",
  myCommunityDesc: "సేవ్ చేసిన ప్రశ్నలు, గ్రూపులు మరియు నోటిఫికేషన్ సెట్టింగ్‌లు.",
  ask: "అడగండి",
  servicesTitle: "సేవలు",
  servicesSub: "మెషినరీ, లాజిస్టిక్స్, నిపుణులు మరియు సలహాలు",
  serviceMachineryTitle: "మెషినరీ బుకింగ్",
  serviceMachineryDesc: "ఫిల్టర్, షెడ్యూల్, ఎస్క్రో మరియు పూర్తి రిలీజ్.",
  serviceLogisticsTitle: "లాజిస్టిక్స్ బుకింగ్",
  serviceLogisticsDesc: "పికప్, అంచనా, GPS ట్రాకింగ్, ఆటో రిలీజ్.",
  serviceExpertTitle: "నిపుణుల సంప్రదింపు",
  serviceExpertDesc: "నిపుణులు, స్లాట్లు, కాల్ సారాంశం, రేటింగ్.",
  serviceWeatherTitle: "వాతావరణం మరియు సలహా",
  serviceWeatherDesc: "వాతావరణ వీక్షణ మరియు తెగులు అలర్ట్ ఫీడ్.",
  open: "తెరవండి",
  posts: "పోస్టులు",
  followers: "ఫాలోవర్లు",
  profileFollowing: "ఫాలో అవుతున్నారు",
  welcome: "స్వాగతం",
  welcomeSub: "ఖాతా సృష్టించడానికి లాంచ్ స్క్రీన్ల నుండి ప్రారంభించండి.",
  kycVerified: "KYC ధృవీకరించబడింది",
  unavailable: "అందుబాటులో లేదు",
  chatUnavailable: "చాట్ సింక్ చేసిన వినియోగదారులకు మాత్రమే.",
  registerHelper: "నమోదు చేసిన వారు లాగిన్‌కు మారవచ్చు.",
  loginHelper: "నమోదు సమయంలో ఉపయోగించిన మొబైల్ నంబర్ ఉపయోగించండి.",
  learnTitle: "నేర్చుకోండి & సమూహం",
  learnSub: "కోర్సులు, మార్గదర్శకత్వం, ప్రశ్నోత్తరం మరియు రైతు గ్రూపులు",
  coursesComingSoon: "ఈ విభాగం త్వరలో. కోర్సులు సిద్ధంగా ఉన్నాయి.",
  loadingCourses: "కోర్సులు లోడ్ అవుతున్నాయి…",
  noCoursesYet: "ఇంకా కోర్సులు లేవు.",
  failedLoadCourses: "కోర్సులు లోడ్ చేయడం విఫలమైంది",
  featuredCourse: "ఫీచర్ కోర్స్",
  marketTitle: "వ్యవసాయ మార్కెట్",
  marketSearchPlaceholder: "ఉత్పత్తి, రైతులు, పరికరాలు శోధించండి...",
  chooseLanguageTitle: "మీ\nభాష ఎంచుకోండి",
  chooseLanguageSub: "అనువర్తన అనుభవానికి మీ ఇష్టమైన భాష ఎంచుకోండి.",
  selectLanguage: "భాష ఎంచుకోండి",
  editProfileTitle: "ప్రొఫైల్ ఎడిట్",
  profileNavTitle: "ప్రొఫైల్",
  search: "శోధించండి",
  searchUsers: "వినియోగదారులను శోధించండి",
  noUsersFound: "వినియోగదారులు కనుగొనబడలేదు.",
  messagesTitle: "సందేశాలు",
  noMessagesTitle: "ఇంకా సందేశాలు లేవు",
  noMessagesSub: "ఎవరైనా సంప్రదించినప్పుడు ఇక్కడ కనిపిస్తుంది.",
  sharedReel: "రీల్ షేర్ చేశారు",
  sharedMedia: "ఫోటో",
  voiceMessage: "వాయిస్ సందేశం",
  recordingVoice: "రికార్డ్ అవుతోంది...",
  galleryPermissionMsg: "చిత్రాలు పంపడానికి గ్యాలరీ అనుమతి ఇవ్వండి.",
  cameraPermissionMsg: "ఫోటో తీయడానికి కెమెరా అనుమతి ఇవ్వండి.",
  micPermissionMsg: "వాయిస్ నోట్ పంపడానికి మైక్ అనుమతి ఇవ్వండి.",
  voiceNoteWebUnavailable: "వాయిస్ నోట్‌లు మొబైల్ యాప్‌లో అందుబాటులో ఉన్నాయి.",
  voiceRecordFailed: "వాయిస్ నోట్ రికార్డ్ కాలేదు.",
  sharedProfile: "ప్రొఫైల్ షేర్ చేశారు",
  yourStory: "మీ స్టోరీ",
  messagePlaceholder: "సందేశం...",
  notifications: "నోటిఫికేషన్లు",
  noNotifications: "ఇంకా నోటిఫికేషన్లు లేవు.",
  accept: "అంగీకరించు",
  decline: "తిరస్కరించు",
  notifFollowRequest: "{{name}} ఫాలో అభ్యర్థన పంపారు",
  notifNowFollowing: "{{name}} ఇప్పుడు మిమ్మల్ని ఫాలో అవుతున్నారు.",
  notifAcceptedRequest: "{{name}} మీ ఫాలో అభ్యర్థనను అంగీకరించారు.",
  notifDeclinedRequest: "{{name}} మీ ఫాలో అభ్యర్థనను తిరస్కరించారు.",
  nameRequired: "పేరు అవసరం",
  nameRequiredMessage: "దయచేసి మీ పేరు నమోదు చేయండి.",
  profileSaved: "సేవ్ చేయబడింది",
  profileUpdated: "ప్రొఫైల్ నవీకరించబడింది.",
  saveFailed: "సేవ్ విఫలమైంది",
  saveFailedProfile: "ప్రొఫైల్ నవీకరించలేకపోయాము.",
  permissionNeeded: "అనుమతి అవసరం",
  photoLibraryPermission: "ఫోటో లైబ్రరీ అనుమతి ఇవ్వండి.",
  profilePhotoUpdated: "ప్రొఫైల్ ఫోటో అప్‌లోడ్ అయింది.",
  photoSavedLocal: "ఫోటో స్థానికంగా సేవ్",
  photoSavedLocalMessage: "సర్వర్‌కు అప్‌లోడ్ కాలేదు, స్థానిక ప్రివ్యూ.",
  changeProfilePhoto: "ప్రొఫైల్ ఫోటో మార్చండి",
  uploading: "అప్‌లోడ్ అవుతోంది…",
  saving: "సేవ్ అవుతోంది…",
  done: "పూర్తి",
  website: "వెబ్‌సైట్",
  bio: "బయో",
  bioPlaceholder: "మీ పొలం లేదా పని గురించి చెప్పండి",
  location: "స్థానం",
  locationPlaceholder: "జిల్లా లేదా ప్రాంతం",
  usernamePlaceholder: "యూజర్‌నేమ్",
  websitePlaceholder: "https://",
  galleryPosts: "పోస్టులు",
  galleryReels: "రీల్స్",
  gallerySaved: "సేవ్",
  galleryTagged: "ట్యాగ్",
  savedReelsEmpty: "సేవ్ చేసిన రీల్స్ ఇక్కడ కనిపిస్తాయి.",
  addToStory: "స్టోరీకి జోడించు",
  copyLink: "లింక్ కాపీ",
  shareTo: "షేర్ చేయండి..",
  whatsapp: "వాట్సాప్",
  messenger: "మెసెంజర్",
  snapchat: "స్నాప్‌చాట్",
  telegram: "టెలిగ్రామ్",
  x: "X",
  shared: "షేర్ చేయబడింది",
  shareFailed: "షేర్ విఫలమైంది",
  shareFailedProfile: "ప్రొఫైల్ ఇప్పుడు పంపలేకపోయాము.",
  profileSharedTo: "ప్రొఫైల్ {{name}} కు పంపబడింది",
  removeFromSaved: "సేవ్ నుండి తీసివేయి",
  savePost: "సేవ్",
  savedPostsHint: "సేవ్ పోస్టులు మీ ప్రొఫైల్‌లో కనిపిస్తాయి.",
  sendFailed: "పంపడం విఫలమైంది",
  sendFailedReel: "రీల్ పంపలేకపోయాము. మళ్లీ ప్రయత్నించండి.",
  cancel: "రద్దు",
  send: "పంపు",
  savePostFailed: "సేవ్ రీల్స్ నవీకరించలేకపోయాము.",
  likes: "లైక్‌లు",
  comments: "కామెంట్‌లు",
  addCommentPlaceholder: "కామెంట్ జోడించండి…",
  replyCancel: "రద్దు",
  viewAllComments: "అన్ని {{count}} కామెంట్‌లు చూడండి",
  copied: "కాపీ అయింది",
  profileLinkCopied: "ప్రొఫైల్ లింక్ కాపీ అయింది.",
  noRecipients: "గ్రహీతలు లేరు",
  shareProfileNoRecipients: "చాట్‌లో ప్రొఫైల్ షేర్ చేయడానికి వినియోగదారులను ఫాలో చేయండి.",
  noTaggedPosts: "ఇంకా ట్యాగ్ పోస్టులు లేవు.",
  noChatsFound: "చాట్‌లు కనుగొనబడలేదు.",
  followBackCapital: "తిరిగి ఫాలో",
  notifRepliedComment: "{{name}} మీ కామెంట్‌కు సమాధానం ఇచ్చారు{{excerpt}}",
  notifCommentedOn: "{{name}} మీ {{kind}}పై కామెంట్ చేశారు{{excerpt}}",
  notifLikedYour: "{{name}} మీ {{kind}}ను లైక్ చేశారు.",
  postKindReel: "రీల్",
  postKindPost: "పోస్ట్",
  photoUpdatedTitle: "నవీకరించబడింది",
  writeReply: "సమాధానం రాయండి…",
  you: "మీరు",
  userWithId: "వినియోగదారు {{id}}",
  originalAudio: "అసలు ఆడియో",
  feedDemoTest: "టెస్ట్",
  feedDemoTestVideoCapture: "టెస్ట్ వీడియో క్యాప్చర్",
  feedTestingFromCamera: "మొబైల్ యాప్ కెమెరా నుండి పరీక్ష",
  farmerDefaultName: "రైతు",
  likesCountLabel: "{{count}} లైక్‌లు",
  shareReelMessage: "{{name}} Cropvibeలో రీల్ షేర్ చేశారు",
  reportUserPrompt: "{{name}}ని ఎందుకు రిపోర్ట్ చేస్తున్నారు?"
};

export const APP_STRINGS_KN: typeof APP_STRINGS_EN = {
  tabMarket: "ಮಾರುಕಟ್ಟೆ",
  tabCreate: "ರಚಿಸಿ",
  tabCommunity: "ಸಮುದಾಯ",
  tabProfile: "ಪ್ರೊಫೈಲ್",
  tabFeed: TAB_FEED_LABEL.kn,
  tabFriends: "ಸ್ನೇಹಿತರು",
  tabLive: "ಲೈವ್",
  follow: "ಫಾಲೋ",
  following: "ಫಾಲೋ ಆಗುತ್ತಿದೆ",
  followBack: "ಮರಳಿ ಫಾಲೋ",
  requested: "ವಿನಂತಿಸಲಾಗಿದೆ",
  followBusy: "...",
  followFailed: "ಫಾಲೋ ವಿಫಲ",
  followFailedMessage: "ಫಾಲೋ ವಿನಂತಿ ಕಳುಹಿಸಲಾಗಲಿಲ್ಲ.",
  emptyFriendsTitle: "ನೀವು ಫಾಲೋ ಮಾಡುವವರ ರೀಲ್‌ಗಳಿಲ್ಲ",
  emptyFriendsSub: "ಹೆಚ್ಚಿನ ಕ್ರಿಯೇಟರ್‌ಗಳನ್ನು ಫಾಲೋ ಮಾಡಿ ಇಲ್ಲಿ ನೋಡಿ.",
  emptyReelsTitle: "ಇನ್ನೂ ರೀಲ್‌ಗಳಿಲ್ಲ",
  emptyReelsSub: "ಪ್ರಾರಂಭಿಸಲು ರೀಲ್ ರಚಿಸಿ.",
  emptyLiveTitle: "ಲೈವ್ ಸ್ಟ್ರೀಮಿಂಗ್ ಶೀಘ್ರದಲ್ಲೇ ಬರುತ್ತಿದೆ",
  emptyLiveSub: "ನಾವು ಲೈವ್ ಪ್ರಸಾರಗಳನ್ನು ನಿರ್ಮಿಸುತ್ತಿದ್ದೇವೆ. ಕಾಯಿರಿ!",
  emptyFeedTitle: EMPTY_DROPS_TITLE.kn,
  emptyNothingTitle: "ಇಲ್ಲಿ ಇನ್ನೂ ಏನೂ ಇಲ್ಲ",
  emptyDefaultSub: "ಈ ವಿಭಾಗವನ್ನು ತುಂಬಲು ರೀಲ್ ರಚಿಸಿ.",
  noLikesYet: "ಇನ್ನೂ ಲೈಕ್‌ಗಳಿಲ್ಲ",
  noComments: "ಕಾಮೆಂಟ್‌ಗಳಿಲ್ಲ",
  communityTitle: "ಸಮುದಾಯ",
  communitySub: "ಪ್ರಶ್ನೋತ್ತರ, ಗುಂಪುಗಳು ಮತ್ತು ಕಲಿಕೆ",
  qaFeed: "ಪ್ರಶ್ನೋತ್ತರ ಫೀಡ್",
  upvotes: "ಅಪ್‌ವೋಟ್‌ಗಳು",
  answers: "ಉತ್ತರಗಳು",
  resolved: "ಪರಿಹರಿಸಲಾಗಿದೆ",
  groups: "ಗುಂಪುಗಳು",
  groupWomenCircle: "ಮಹಿಳಾ ವೃತ್ತ",
  groupYoungFarmers: "ಯುವ ರೈತರು",
  groupCropGroups: "ಬೆಳೆ ಗುಂಪುಗಳು",
  groupFpoNetwork: "FPO ನೆಟ್‌ವರ್ಕ್",
  myCommunity: "ನನ್ನ ಸಮುದಾಯ",
  myCommunityDesc: "ಉಳಿಸಿದ ಪ್ರಶ್ನೆಗಳು, ಗುಂಪುಗಳು ಮತ್ತು ಅಧಿಸೂಚನೆ ಸೆಟ್ಟಿಂಗ್‌ಗಳು.",
  ask: "ಕೇಳಿ",
  servicesTitle: "ಸೇವೆಗಳು",
  servicesSub: "ಯಂತ್ರೋಪಕರಣ, ಲಾಜಿಸ್ಟಿಕ್ಸ್, ತಜ್ಞರು ಮತ್ತು ಸಲಹೆ",
  serviceMachineryTitle: "ಯಂತ್ರೋಪಕರಣ ಬುಕಿಂಗ್",
  serviceMachineryDesc: "ಫಿಲ್ಟರ್, ಶೆಡ್ಯೂಲ್, ಎಸ್ಕ್ರೋ ಮತ್ತು ಪೂರ್ಣ ಬಿಡುಗಡೆ.",
  serviceLogisticsTitle: "ಲಾಜಿಸ್ಟಿಕ್ಸ್ ಬುಕಿಂಗ್",
  serviceLogisticsDesc: "ಪಿಕಪ್, ಅಂದಾಜು, GPS ಟ್ರ್ಯಾಕಿಂಗ್, ಆಟೋ ಬಿಡುಗಡೆ.",
  serviceExpertTitle: "ತಜ್ಞರ ಸಮಾಲೋಚನೆ",
  serviceExpertDesc: "ತಜ್ಞರು, ಸ್ಲಾಟ್‌ಗಳು, ಕಾಲ್ ಸಾರಾಂಶ, ರೇಟಿಂಗ್.",
  serviceWeatherTitle: "ಹವಾಮಾನ ಮತ್ತು ಸಲಹೆ",
  serviceWeatherDesc: "ಹವಾಮಾನ ವೀಕ್ಷಣೆ ಮತ್ತು ಕೀಟ ಎಚ್ಚರಿಕೆ ಫೀಡ್.",
  open: "ತೆರೆಯಿರಿ",
  posts: "ಪೋಸ್ಟ್‌ಗಳು",
  followers: "ಫಾಲೋವರ್‌ಗಳು",
  profileFollowing: "ಫಾಲೋ ಆಗುತ್ತಿದೆ",
  welcome: "ಸ್ವಾಗತ",
  welcomeSub: "ಖಾತೆ ರಚಿಸಲು ಲಾಂಚ್ ಸ್ಕ್ರೀನ್‌ಗಳಿಂದ ಪ್ರಾರಂಭಿಸಿ.",
  kycVerified: "KYC ಪರಿಶೀಲಿಸಲಾಗಿದೆ",
  unavailable: "ಲಭ್ಯವಿಲ್ಲ",
  chatUnavailable: "ಸಿಂಕ್ ಬಳಕೆದಾರರಿಗೆ ಮಾತ್ರ ಚಾಟ್.",
  registerHelper: "ನೋಂದಾಯಿತ ಬಳಕೆದಾರರು ಲಾಗಿನ್‌ಗೆ ಬದಲಾಯಿಸಬಹುದು.",
  loginHelper: "ನೋಂದಣಿಯಲ್ಲಿ ಬಳಸಿದ ಮೊಬೈಲ್ ಸಂಖ್ಯೆ ಬಳಸಿ.",
  learnTitle: "ಕಲಿಯಿರಿ & ಸಮುದಾಯ",
  learnSub: "ಕೋರ್ಸ್‌ಗಳು, ಮಾರ್ಗದರ್ಶನ, ಪ್ರಶ್ನೋತ್ತರ ಮತ್ತು ರೈತ ಗುಂಪುಗಳು",
  coursesComingSoon: "ಈ ವಿಭಾಗ ಶೀಘ್ರದಲ್ಲೇ. ಕೋರ್ಸ್‌ಗಳು ಸಿದ್ಧವಿವೆ.",
  loadingCourses: "ಕೋರ್ಸ್‌ಗಳನ್ನು ಲೋಡ್ ಮಾಡಲಾಗುತ್ತಿದೆ…",
  noCoursesYet: "ಇನ್ನೂ ಕೋರ್ಸ್‌ಗಳಿಲ್ಲ.",
  failedLoadCourses: "ಕೋರ್ಸ್‌ಗಳ ಲೋಡ್ ವಿಫಲ",
  featuredCourse: "ವಿಶೇಷ ಕೋರ್ಸ್",
  marketTitle: "ಕೃಷಿ ಮಾರುಕಟ್ಟೆ",
  marketSearchPlaceholder: "ಉತ್ಪನ್ನ, ರೈತರು, ಉಪಕರಣ ಹುಡುಕಿ...",
  chooseLanguageTitle: "ನಿಮ್ಮ\nಭಾಷೆ ಆಯ್ಕೆಮಾಡಿ",
  chooseLanguageSub: "ಅಪ್ಲಿಕೇಶನ್ ಅನುಭವಕ್ಕಾಗಿ ನಿಮ್ಮ ಆದ್ಯತೆಯ ಭಾಷೆ ಆಯ್ಕೆಮಾಡಿ.",
  selectLanguage: "ಭಾಷೆ ಆಯ್ಕೆಮಾಡಿ",
  editProfileTitle: "ಪ್ರೊಫೈಲ್ ಸಂಪಾದಿಸಿ",
  profileNavTitle: "ಪ್ರೊಫೈಲ್",
  search: "ಹುಡುಕಿ",
  searchUsers: "ಬಳಕೆದಾರರನ್ನು ಹುಡುಕಿ",
  noUsersFound: "ಬಳಕೆದಾರರು ಕಂಡುಬಂದಿಲ್ಲ.",
  messagesTitle: "ಸಂದೇಶಗಳು",
  noMessagesTitle: "ಇನ್ನೂ ಸಂದೇಶಗಳಿಲ್ಲ",
  noMessagesSub: "ಯಾರಾದರೂ ಸಂಪರ್ಕಿಸಿದಾಗ ಇಲ್ಲಿ ಕಾಣಿಸುತ್ತದೆ.",
  sharedReel: "ರೀಲ್ ಹಂಚಿಕೊಂಡರು",
  sharedMedia: "ಫೋಟೋ",
  voiceMessage: "ವಾಯ್ಸ್ ಸಂದೇಶ",
  recordingVoice: "ರೆಕಾರ್ಡ್ ಆಗುತ್ತಿದೆ...",
  galleryPermissionMsg: "ಚಿತ್ರಗಳನ್ನು ಕಳುಹಿಸಲು ಗ್ಯಾಲರಿ ಅನುಮತಿ ನೀಡಿ.",
  cameraPermissionMsg: "ಫೋಟೋ ತೆಗೆಯಲು ಕ್ಯಾಮೆರಾ ಅನುಮತಿ ನೀಡಿ.",
  micPermissionMsg: "ವಾಯ್ಸ್ ನೋಟ್ ಕಳುಹಿಸಲು ಮೈಕ್ ಅನುಮತಿ ನೀಡಿ.",
  voiceNoteWebUnavailable: "ವಾಯ್ಸ್ ನೋಟ್‌ಗಳು ಮೊಬೈಲ್ ಆ್ಯಪ್‌ನಲ್ಲಿ ಲಭ್ಯ.",
  voiceRecordFailed: "ವಾಯ್ಸ್ ನೋಟ್ ರೆಕಾರ್ಡ್ ಆಗಲಿಲ್ಲ.",
  sharedProfile: "ಪ್ರೊಫೈಲ್ ಹಂಚಿಕೊಂಡರು",
  yourStory: "ನಿಮ್ಮ ಸ್ಟೋರಿ",
  messagePlaceholder: "ಸಂದೇಶ...",
  notifications: "ಅಧಿಸೂಚನೆಗಳು",
  noNotifications: "ಇನ್ನೂ ಅಧಿಸೂಚನೆಗಳಿಲ್ಲ.",
  accept: "ಸ್ವೀಕರಿಸಿ",
  decline: "ನಿರಾಕರಿಸಿ",
  notifFollowRequest: "{{name}} ಫಾಲೋ ವಿನಂತಿ ಕಳುಹಿಸಿದ್ದಾರೆ",
  notifNowFollowing: "{{name}} ಈಗ ನಿಮ್ಮನ್ನು ಫಾಲೋ ಮಾಡುತ್ತಿದ್ದಾರೆ.",
  notifAcceptedRequest: "{{name}} ನಿಮ್ಮ ಫಾಲೋ ವಿನಂತಿಯನ್ನು ಸ್ವೀಕರಿಸಿದ್ದಾರೆ.",
  notifDeclinedRequest: "{{name}} ನಿಮ್ಮ ಫಾಲೋ ವಿನಂತಿಯನ್ನು ನಿರಾಕರಿಸಿದ್ದಾರೆ.",
  nameRequired: "ಹೆಸರು ಅಗತ್ಯ",
  nameRequiredMessage: "ದಯವಿಟ್ಟು ನಿಮ್ಮ ಹೆಸರನ್ನು ನಮೂದಿಸಿ.",
  profileSaved: "ಉಳಿಸಲಾಗಿದೆ",
  profileUpdated: "ಪ್ರೊಫೈಲ್ ನವೀಕರಿಸಲಾಗಿದೆ.",
  saveFailed: "ಉಳಿಸುವಿಕೆ ವಿಫಲ",
  saveFailedProfile: "ಪ್ರೊಫೈಲ್ ನವೀಕರಿಸಲಾಗಲಿಲ್ಲ.",
  permissionNeeded: "ಅನುಮತಿ ಬೇಕು",
  photoLibraryPermission: "ದಯವಿಟ್ಟು ಫೋಟೋ ಲೈಬ್ರರಿ ಅನುಮತಿ ನೀಡಿ.",
  profilePhotoUpdated: "ಪ್ರೊಫೈಲ್ ಫೋಟೋ ಅಪ್‌ಲೋಡ್ ಆಗಿದೆ.",
  photoSavedLocal: "ಫೋಟೋ ಸ್ಥಳೀಯವಾಗಿ ಉಳಿಸಲಾಗಿದೆ",
  photoSavedLocalMessage: "ಸರ್ವರ್‌ಗೆ ಅಪ್‌ಲೋಡ್ ಆಗಲಿಲ್ಲ, ಸ್ಥಳೀಯ ಪ್ರಿವ್ಯೂ.",
  changeProfilePhoto: "ಪ್ರೊಫೈಲ್ ಫೋಟೋ ಬದಲಾಯಿಸಿ",
  uploading: "ಅಪ್‌ಲೋಡ್ ಆಗುತ್ತಿದೆ…",
  saving: "ಉಳಿಸಲಾಗುತ್ತಿದೆ…",
  done: "ಮುಗಿಯಿತು",
  website: "ವೆಬ್‌ಸೈಟ್",
  bio: "ಬಯೋ",
  bioPlaceholder: "ನಿಮ್ಮ ಹೊಲ ಅಥವಾ ಕೆಲಸದ ಬಗ್ಗೆ ಹೇಳಿ",
  location: "ಸ್ಥಳ",
  locationPlaceholder: "ಜಿಲ್ಲೆ ಅಥವಾ ಪ್ರದೇಶ",
  usernamePlaceholder: "ಬಳಕೆದಾರಹೆಸರು",
  websitePlaceholder: "https://",
  galleryPosts: "ಪೋಸ್ಟ್‌ಗಳು",
  galleryReels: "ರೀಲ್‌ಗಳು",
  gallerySaved: "ಉಳಿಸಿದವು",
  galleryTagged: "ಟ್ಯಾಗ್",
  savedReelsEmpty: "ಉಳಿಸಿದ ರೀಲ್‌ಗಳು ಇಲ್ಲಿ ಕಾಣಿಸುತ್ತವೆ.",
  addToStory: "ಸ್ಟೋರಿಗೆ ಸೇರಿಸಿ",
  copyLink: "ಲಿಂಕ್ ಕಾಪಿ",
  shareTo: "ಹಂಚಿಕೊಳ್ಳಿ..",
  whatsapp: "ವಾಟ್ಸ್‌ಆ್ಯಪ್",
  messenger: "ಮೆಸೆಂಜರ್",
  snapchat: "ಸ್ನ್ಯಾಪ್‌ಚಾಟ್",
  telegram: "ಟೆಲಿಗ್ರಾಮ್",
  x: "X",
  shared: "ಹಂಚಿಕೊಳ್ಳಲಾಗಿದೆ",
  shareFailed: "ಹಂಚಿಕೆ ವಿಫಲ",
  shareFailedProfile: "ಪ್ರೊಫೈಲ್ ಈಗ ಕಳುಹಿಸಲಾಗಲಿಲ್ಲ.",
  profileSharedTo: "ಪ್ರೊಫೈಲ್ {{name}} ಗೆ ಕಳುಹಿಸಲಾಗಿದೆ",
  removeFromSaved: "ಉಳಿಸಿದವುಗಳಿಂದ ತೆಗೆದುಹಾಕಿ",
  savePost: "ಉಳಿಸಿ",
  savedPostsHint: "ಉಳಿಸಿದ ಪೋಸ್ಟ್‌ಗಳು ನಿಮ್ಮ ಪ್ರೊಫೈಲ್‌ನಲ್ಲಿ ಕಾಣಿಸುತ್ತವೆ.",
  sendFailed: "ಕಳುಹಿಸುವಿಕೆ ವಿಫಲ",
  sendFailedReel: "ರೀಲ್ ಕಳುಹಿಸಲಾಗಲಿಲ್ಲ. ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.",
  cancel: "ರದ್ದುಮಾಡಿ",
  send: "ಕಳುಹಿಸಿ",
  savePostFailed: "ಉಳಿಸಿದ ರೀಲ್‌ಗಳನ್ನು ನವೀಕರಿಸಲಾಗಲಿಲ್ಲ.",
  likes: "ಲೈಕ್‌ಗಳು",
  comments: "ಕಾಮೆಂಟ್‌ಗಳು",
  addCommentPlaceholder: "ಕಾಮೆಂಟ್ ಸೇರಿಸಿ…",
  replyCancel: "ರದ್ದುಮಾಡಿ",
  viewAllComments: "ಎಲ್ಲಾ {{count}} ಕಾಮೆಂಟ್‌ಗಳನ್ನು ನೋಡಿ",
  copied: "ಕಾಪಿ ಆಗಿದೆ",
  profileLinkCopied: "ಪ್ರೊಫೈಲ್ ಲಿಂಕ್ ಕಾಪಿ ಆಗಿದೆ.",
  noRecipients: "ಸ್ವೀಕೃತದಾರರಿಲ್ಲ",
  shareProfileNoRecipients: "ಚಾಟ್‌ನಲ್ಲಿ ಪ್ರೊಫೈಲ್ ಹಂಚಲು ಬಳಕೆದಾರರನ್ನು ಫಾಲೋ ಮಾಡಿ.",
  noTaggedPosts: "ಇನ್ನೂ ಟ್ಯಾಗ್ ಪೋಸ್ಟ್‌ಗಳಿಲ್ಲ.",
  noChatsFound: "ಚಾಟ್‌ಗಳು ಕಂಡುಬಂದಿಲ್ಲ.",
  followBackCapital: "ಮರಳಿ ಫಾಲೋ",
  notifRepliedComment: "{{name}} ನಿಮ್ಮ ಕಾಮೆಂಟ್‌ಗೆ ಉತ್ತರಿಸಿದ್ದಾರೆ{{excerpt}}",
  notifCommentedOn: "{{name}} ನಿಮ್ಮ {{kind}} ಮೇಲೆ ಕಾಮೆಂಟ್ ಮಾಡಿದ್ದಾರೆ{{excerpt}}",
  notifLikedYour: "{{name}} ನಿಮ್ಮ {{kind}} ಅನ್ನು ಲೈಕ್ ಮಾಡಿದ್ದಾರೆ.",
  postKindReel: "ರೀಲ್",
  postKindPost: "ಪೋಸ್ಟ್",
  photoUpdatedTitle: "ನವೀಕರಿಸಲಾಗಿದೆ",
  writeReply: "ಉತ್ತರ ಬರೆಯಿರಿ…",
  you: "ನೀವು",
  userWithId: "ಬಳಕೆದಾರ {{id}}",
  originalAudio: "ಮೂಲ ಆಡಿಯೋ",
  feedDemoTest: "ಟೆಸ್ಟ್",
  feedDemoTestVideoCapture: "ಟೆಸ್ಟ್ ವೀಡಿಯೋ ಕ್ಯಾಪ್ಚರ್",
  feedTestingFromCamera: "ಮೊಬೈಲ್ ಆ್ಯಪ್ ಕ್ಯಾಮೆರಾದಿಂದ ಪರೀಕ್ಷೆ",
  farmerDefaultName: "ರೈತ",
  likesCountLabel: "{{count}} ಲೈಕ್‌ಗಳು",
  shareReelMessage: "{{name}} Cropvibeನಲ್ಲಿ ರೀಲ್ ಹಂಚಿಕೊಂಡಿದ್ದಾರೆ",
  reportUserPrompt: "{{name}} ಅನ್ನು ಏಕೆ ವರದಿ ಮಾಡುತ್ತಿದ್ದೀರಿ?"
};

export const APP_STRINGS_ML: typeof APP_STRINGS_EN = {
  tabMarket: "മാർക്കറ്റ്",
  tabCreate: "സൃഷ്ടിക്കുക",
  tabCommunity: "സമൂഹം",
  tabProfile: "പ്രൊഫൈൽ",
  tabFeed: TAB_FEED_LABEL.ml,
  tabFriends: "സുഹൃത്തുക്കൾ",
  tabLive: "ലൈവ്",
  follow: "ഫോളോ",
  following: "ഫോളോ ചെയ്യുന്നു",
  followBack: "തിരികെ ഫോളോ",
  requested: "അഭ്യർത്ഥിച്ചു",
  followBusy: "...",
  followFailed: "ഫോളോ പരാജയം",
  followFailedMessage: "ഫോളോ അഭ്യർത്ഥന അയയ്ക്കാനായില്ല.",
  emptyFriendsTitle: "നിങ്ങൾ ഫോളോ ചെയ്യുന്നവരുടെ റീൽസ് ഇല്ല",
  emptyFriendsSub: "കൂടുതൽ ക്രിയേറ്റർമാരെ ഫോളോ ചെയ്ത് ഇവിടെ കാണുക.",
  emptyReelsTitle: "ഇതുവരെ റീൽസ് ഇല്ല",
  emptyReelsSub: "ആരംഭിക്കാൻ ഒരു റീൽ സൃഷ്ടിക്കുക.",
  emptyLiveTitle: "ലൈവ് സ്ട്രീമിംഗ് ഉടൻ വരുന്നു",
  emptyLiveSub: "ഞങ്ങൾ ലൈവ് പ്രക്ഷേപണങ്ങൾ നിർമ്മിക്കുന്നു. കാത്തിരിക്കൂ!",
  emptyFeedTitle: EMPTY_DROPS_TITLE.ml,
  emptyNothingTitle: "ഇവിടെ ഇതുവരെ ഒന്നുമില്ല",
  emptyDefaultSub: "ഈ വിഭാഗം നിറയ്ക്കാൻ ഒരു റീൽ സൃഷ്ടിക്കുക.",
  noLikesYet: "ഇതുവരെ ലൈക്കുകൾ ഇല്ല",
  noComments: "കമന്റുകൾ ഇല്ല",
  communityTitle: "സമൂഹം",
  communitySub: "ചോദ്യോത്തരം, ഗ്രൂപ്പുകൾ, പഠനം",
  qaFeed: "ചോദ്യോത്തര ഫീഡ്",
  upvotes: "അപ്‌വോട്ടുകൾ",
  answers: "ഉത്തരങ്ങൾ",
  resolved: "പരിഹരിച്ചു",
  groups: "ഗ്രൂപ്പുകൾ",
  groupWomenCircle: "വനിതാ സർക്കിൾ",
  groupYoungFarmers: "യുവ കർഷകർ",
  groupCropGroups: "വിള ഗ്രൂപ്പുകൾ",
  groupFpoNetwork: "FPO നെറ്റ്‌വർക്ക്",
  myCommunity: "എന്റെ സമൂഹം",
  myCommunityDesc: "സേവ് ചെയ്ത ചോദ്യങ്ങൾ, ഗ്രൂപ്പുകൾ, അറിയിപ്പ് ക്രമീകരണങ്ങൾ.",
  ask: "ചോദിക്കുക",
  servicesTitle: "സേവനങ്ങൾ",
  servicesSub: "യന്ത്രങ്ങൾ, ലോജിസ്റ്റിക്സ്, വിദഗ്ധർ, ഉപദേശം",
  serviceMachineryTitle: "യന്ത്ര ബുക്കിംഗ്",
  serviceMachineryDesc: "ഫിൽട്ടർ, ഷെഡ്യൂൾ, എസ്ക്രോ, പൂർത്തീകരണ റിലീസ്.",
  serviceLogisticsTitle: "ലോജിസ്റ്റിക്സ് ബുക്കിംഗ്",
  serviceLogisticsDesc: "പിക്കപ്പ്, എസ്റ്റിമേറ്റ്, GPS ട്രാക്കിംഗ്, ഓട്ടോ റിലീസ്.",
  serviceExpertTitle: "വിദഗ്ധ കൂടിയാലോചന",
  serviceExpertDesc: "വിദഗ്ധർ, സ്ലോട്ടുകൾ, കോൾ സംഗ്രഹം, റേറ്റിംഗ്.",
  serviceWeatherTitle: "കാലാവസ്ഥയും ഉപദേശവും",
  serviceWeatherDesc: "കാലാവസ്ഥ കാഴ്ചയും കീട അലേർട്ട് ഫീഡും.",
  open: "തുറക്കുക",
  posts: "പോസ്റ്റുകൾ",
  followers: "ഫോളോവേഴ്സ്",
  profileFollowing: "ഫോളോ ചെയ്യുന്നു",
  welcome: "സ്വാഗതം",
  welcomeSub: "അക്കൗണ്ട് സൃഷ്ടിക്കാൻ ലോഞ്ച് സ്ക്രീനുകളിൽ നിന്ന് ആരംഭിക്കുക.",
  kycVerified: "KYC പരിശോധിച്ചു",
  unavailable: "ലഭ്യമല്ല",
  chatUnavailable: "സിങ്ക് ചെയ്ത ഉപയോക്താക്കൾക്ക് മാത്രം ചാറ്റ്.",
  registerHelper: "രജിസ്റ്റർ ചെയ്ത ഉപയോക്താക്കൾ ലോഗിനിലേക്ക് മാറാം.",
  loginHelper: "രജിസ്‌ട്രേഷനിൽ ഉപയോഗിച്ച മൊബൈൽ നമ്പർ ഉപയോഗിക്കുക.",
  learnTitle: "പഠിക്കുക & സമൂഹം",
  learnSub: "കോഴ്‌സുകൾ, മാർഗനിർദേശം, ചോദ്യോത്തരം, കർഷക ഗ്രൂപ്പുകൾ",
  coursesComingSoon: "ഈ വിഭാഗം ഉടൻ. കോഴ്‌സുകൾ തയ്യാറാണ്.",
  loadingCourses: "കോഴ്‌സുകൾ ലോഡ് ചെയ്യുന്നു…",
  noCoursesYet: "ഇതുവരെ കോഴ്‌സുകൾ ഇല്ല.",
  failedLoadCourses: "കോഴ്‌സുകൾ ലോഡ് പരാജയം",
  featuredCourse: "ഫീച്ചർ കോഴ്‌സ്",
  marketTitle: "കാർഷിക മാർക്കറ്റ്",
  marketSearchPlaceholder: "ഉൽപ്പന്നം, കർഷകർ, ഉപകരണങ്ങൾ തിരയുക...",
  chooseLanguageTitle: "നിങ്ങളുടെ\nഭാഷ തിരഞ്ഞെടുക്കുക",
  chooseLanguageSub: "ആപ്പ് അനുഭവത്തിനായി നിങ്ങളുടെ ഇഷ്ട ഭാഷ തിരഞ്ഞെടുക്കുക.",
  selectLanguage: "ഭാഷ തിരഞ്ഞെടുക്കുക",
  editProfileTitle: "പ്രൊഫൈൽ എഡിറ്റ്",
  profileNavTitle: "പ്രൊഫൈൽ",
  search: "തിരയുക",
  searchUsers: "ഉപയോക്താക്കളെ തിരയുക",
  noUsersFound: "ഉപയോക്താക്കൾ കണ്ടെത്തിയില്ല.",
  messagesTitle: "സന്ദേശങ്ങൾ",
  noMessagesTitle: "ഇതുവരെ സന്ദേശങ്ങൾ ഇല്ല",
  noMessagesSub: "ആരെങ്കിലും ബന്ധപ്പെടുമ്പോൾ ഇവിടെ കാണാം.",
  sharedReel: "ഒരു റീൽ പങ്കിട്ടു",
  sharedMedia: "ഫോട്ടോ",
  voiceMessage: "വോയ്സ് സന്ദേശം",
  recordingVoice: "റെക്കോർഡ് ചെയ്യുന്നു...",
  galleryPermissionMsg: "ചിത്രങ്ങൾ അയയ്ക്കാൻ ഗ്യാലറി അനുമതി നൽകുക.",
  cameraPermissionMsg: "ഫോട്ടോ എടുക്കാൻ ക്യാമറ അനുമതി നൽകുക.",
  micPermissionMsg: "വോയ്സ് നോട്ട് അയയ്ക്കാൻ മൈക്ക് അനുമതി നൽകുക.",
  voiceNoteWebUnavailable: "വോയ്സ് നോട്ടുകൾ മൊബൈൽ ആപ്പിൽ ലഭ്യമാണ്.",
  voiceRecordFailed: "വോയ്സ് നോട്ട് റെക്കോർഡ് ചെയ്യാൻ കഴിഞ്ഞില്ല.",
  sharedProfile: "ഒരു പ്രൊഫൈൽ പങ്കിട്ടു",
  yourStory: "നിങ്ങളുടെ സ്റ്റോറി",
  messagePlaceholder: "സന്ദേശം...",
  notifications: "അറിയിപ്പുകൾ",
  noNotifications: "ഇതുവരെ അറിയിപ്പുകൾ ഇല്ല.",
  accept: "സ്വീകരിക്കുക",
  decline: "നിരസിക്കുക",
  notifFollowRequest: "{{name}} ഫോളോ അഭ്യർത്ഥന അയച്ചു",
  notifNowFollowing: "{{name}} ഇപ്പോൾ നിങ്ങളെ ഫോളോ ചെയ്യുന്നു.",
  notifAcceptedRequest: "{{name}} നിങ്ങളുടെ ഫോളോ അഭ്യർത്ഥന സ്വീകരിച്ചു.",
  notifDeclinedRequest: "{{name}} നിങ്ങളുടെ ഫോളോ അഭ്യർത്ഥന നിരസിച്ചു.",
  nameRequired: "പേര് ആവശ്യമാണ്",
  nameRequiredMessage: "ദയവായി നിങ്ങളുടെ പേര് നൽകുക.",
  profileSaved: "സേവ് ചെയ്തു",
  profileUpdated: "പ്രൊഫൈൽ അപ്‌ഡേറ്റ് ചെയ്തു.",
  saveFailed: "സേവ് പരാജയം",
  saveFailedProfile: "പ്രൊഫൈൽ അപ്‌ഡേറ്റ് ചെയ്യാനായില്ല.",
  permissionNeeded: "അനുമതി ആവശ്യമാണ്",
  photoLibraryPermission: "ദയവായി ഫോട്ടോ ലൈബ്രറി അനുമതി നൽകുക.",
  profilePhotoUpdated: "പ്രൊഫൈൽ ഫോട്ടോ അപ്‌ലോഡ് ചെയ്തു.",
  photoSavedLocal: "ഫോട്ടോ ലോക്കലായി സേവ് ചെയ്തു",
  photoSavedLocalMessage: "സെർവറിലേക്ക് അപ്‌ലോഡ് ചെയ്യാനായില്ല, ലോക്കൽ പ്രിവ്യൂ.",
  changeProfilePhoto: "പ്രൊഫൈൽ ഫോട്ടോ മാറ്റുക",
  uploading: "അപ്‌ലോഡ് ചെയ്യുന്നു…",
  saving: "സേവ് ചെയ്യുന്നു…",
  done: "പൂർത്തിയായി",
  website: "വെബ്‌സൈറ്റ്",
  bio: "ബയോ",
  bioPlaceholder: "നിങ്ങളുടെ കൃഷിയിടം അല്ലെങ്കിൽ ജോലിയെ കുറിച്ച് പറയുക",
  location: "സ്ഥലം",
  locationPlaceholder: "ജില്ല അല്ലെങ്കിൽ പ്രദേശം",
  usernamePlaceholder: "ഉപയോക്തൃനാമം",
  websitePlaceholder: "https://",
  galleryPosts: "പോസ്റ്റുകൾ",
  galleryReels: "റീൽസ്",
  gallerySaved: "സേവ് ചെയ്തവ",
  galleryTagged: "ടാഗ്",
  savedReelsEmpty: "സേവ് ചെയ്ത റീൽസ് ഇവിടെ കാണാം.",
  addToStory: "സ്റ്റോറിയിലേക്ക് ചേർക്കുക",
  copyLink: "ലിങ്ക് കോപ്പി",
  shareTo: "പങ്കിടുക..",
  whatsapp: "വാട്ട്‌സ്ആപ്പ്",
  messenger: "മെസഞ്ചർ",
  snapchat: "സ്നാപ്ചാറ്റ്",
  telegram: "ടെലിഗ്രാം",
  x: "X",
  shared: "പങ്കിട്ടു",
  shareFailed: "പങ്കിടൽ പരാജയം",
  shareFailedProfile: "പ്രൊഫൈൽ ഇപ്പോൾ അയയ്ക്കാനായില്ല.",
  profileSharedTo: "പ്രൊഫൈൽ {{name}} ന് അയച്ചു",
  removeFromSaved: "സേവ് ചെയ്തവയിൽ നിന്ന് നീക്കുക",
  savePost: "സേവ്",
  savedPostsHint: "സേവ് ചെയ്ത പോസ്റ്റുകൾ നിങ്ങളുടെ പ്രൊഫൈലിൽ കാണാം.",
  sendFailed: "അയയ്ക്കൽ പരാജയം",
  sendFailedReel: "റീൽ അയയ്ക്കാനായില്ല. വീണ്ടും ശ്രമിക്കുക.",
  cancel: "റദ്ദാക്കുക",
  send: "അയയ്ക്കുക",
  savePostFailed: "സേവ് ചെയ്ത റീൽസ് അപ്‌ഡേറ്റ് ചെയ്യാനായില്ല.",
  likes: "ലൈക്കുകൾ",
  comments: "കമന്റുകൾ",
  addCommentPlaceholder: "ഒരു കമന്റ് ചേർക്കുക…",
  replyCancel: "റദ്ദാക്കുക",
  viewAllComments: "എല്ലാ {{count}} കമന്റുകളും കാണുക",
  copied: "കോപ്പി ചെയ്തു",
  profileLinkCopied: "പ്രൊഫൈൽ ലിങ്ക് കോപ്പി ചെയ്തു.",
  noRecipients: "സ്വീകർത്താക്കൾ ഇല്ല",
  shareProfileNoRecipients: "ചാറ്റിൽ പ്രൊഫൈൽ പങ്കിടാൻ ഉപയോക്താക്കളെ ഫോളോ ചെയ്യുക.",
  noTaggedPosts: "ഇതുവരെ ടാഗ് പോസ്റ്റുകൾ ഇല്ല.",
  noChatsFound: "ചാറ്റുകൾ കണ്ടെത്തിയില്ല.",
  followBackCapital: "തിരികെ ഫോളോ",
  notifRepliedComment: "{{name}} നിങ്ങളുടെ കമന്റിന് മറുപടി നൽകി{{excerpt}}",
  notifCommentedOn: "{{name}} നിങ്ങളുടെ {{kind}}-ൽ കമന്റ് ചെയ്തു{{excerpt}}",
  notifLikedYour: "{{name}} നിങ്ങളുടെ {{kind}} ലൈക്ക് ചെയ്തു.",
  postKindReel: "റീൽ",
  postKindPost: "പോസ്റ്റ്",
  photoUpdatedTitle: "അപ്‌ഡേറ്റ് ചെയ്തു",
  writeReply: "മറുപടി എഴുതുക…",
  you: "നിങ്ങൾ",
  userWithId: "ഉപയോക്താവ് {{id}}",
  originalAudio: "ഒറിജിനൽ ഓഡിയോ",
  feedDemoTest: "ടെസ്റ്റ്",
  feedDemoTestVideoCapture: "ടെസ്റ്റ് വീഡിയോ ക്യാപ്ചർ",
  feedTestingFromCamera: "മൊബൈൽ ആപ്പ് ക്യാമറയിൽ നിന്ന് പരീക്ഷണം",
  farmerDefaultName: "കർഷകൻ",
  likesCountLabel: "{{count}} ലൈക്കുകൾ",
  shareReelMessage: "{{name}} Cropvibeൽ ഒരു റീൽ പങ്കിട്ടു",
  reportUserPrompt: "{{name}} എന്തുകൊണ്ടാണ് റിപ്പോർട്ട് ചെയ്യുന്നത്?"
};

export const APP_STRINGS_TA: typeof APP_STRINGS_EN = {
  tabMarket: "சந்தை",
  tabCreate: "உருவாக்கு",
  tabCommunity: "சமூகம்",
  tabProfile: "சுயவிவரம்",
  tabFeed: TAB_FEED_LABEL.ta,
  tabFriends: "நண்பர்கள்",
  tabLive: "லைவ்",
  follow: "பின்தொடர்",
  following: "பின்தொடர்கிறது",
  followBack: "திரும்ப பின்தொடர்",
  requested: "கோரப்பட்டது",
  followBusy: "...",
  followFailed: "பின்தொடர்தல் தோல்வி",
  followFailedMessage: "பின்தொடர் கோரிக்கையை அனுப்ப இயலவில்லை.",
  emptyFriendsTitle: "நீங்கள் பின்தொடர்பவர்களின் ரீல்கள் இல்லை",
  emptyFriendsSub: "மேலும் படைப்பாளர்களைப் பின்தொடர்ந்து இங்கே பாருங்கள்.",
  emptyReelsTitle: "இதுவரை ரீல்கள் இல்லை",
  emptyReelsSub: "தொடங்க ஒரு ரீல் உருவாக்குங்கள்.",
  emptyLiveTitle: "லைவ் ஸ்ட்ரீமிங் விரைவில் வருகிறது",
  emptyLiveSub: "லைவ் ஒளிபரப்புகளை உருவாக்குகிறோம். காத்திருங்கள்!",
  emptyFeedTitle: EMPTY_DROPS_TITLE.ta,
  emptyNothingTitle: "இங்கே இதுவரை எதுவும் இல்லை",
  emptyDefaultSub: "இந்தப் பிரிவை நிரப்ப ஒரு ரீல் உருவாக்குங்கள்.",
  noLikesYet: "இதுவரை லைக்குகள் இல்லை",
  noComments: "கருத்துகள் இல்லை",
  communityTitle: "சமூகம்",
  communitySub: "கேள்வி-பதில், குழுக்கள், கற்றல்",
  qaFeed: "கேள்வி-பதில் ஃபீட்",
  upvotes: "அப்வோட்டுகள்",
  answers: "பதில்கள்",
  resolved: "தீர்க்கப்பட்டது",
  groups: "குழுக்கள்",
  groupWomenCircle: "பெண்கள் வட்டம்",
  groupYoungFarmers: "இளம் விவசாயிகள்",
  groupCropGroups: "பயிர் குழுக்கள்",
  groupFpoNetwork: "FPO நெட்வொர்க்",
  myCommunity: "என் சமூகம்",
  myCommunityDesc: "சேமித்த கேள்விகள், குழுக்கள் மற்றும் அறிவிப்பு அமைப்புகள்.",
  ask: "கேளுங்கள்",
  servicesTitle: "சேவைகள்",
  servicesSub: "இயந்திரங்கள், லாஜிஸ்டிக்ஸ், நிபுணர்கள், ஆலோசனை",
  serviceMachineryTitle: "இயந்திர முன்பதிவு",
  serviceMachineryDesc: "வடிகட்டு, திட்டமிடு, எஸ்க்ரோ, முடிவு வெளியீடு.",
  serviceLogisticsTitle: "லாஜிஸ்டிக்ஸ் முன்பதிவு",
  serviceLogisticsDesc: "பிக்கப், மதிப்பீடு, GPS கண்காணிப்பு, தானியங்கி வெளியீடு.",
  serviceExpertTitle: "நிபுணர் ஆலோசனை",
  serviceExpertDesc: "நிபுணர்கள், ஸ்லாட்டுகள், அழைப்பு சுருக்கம், மதிப்பீடு.",
  serviceWeatherTitle: "வானிலை மற்றும் ஆலோசனை",
  serviceWeatherDesc: "வானிலை காட்சி மற்றும் பூச்சி எச்சரிக்கை ஃபீட்.",
  open: "திற",
  posts: "பதிவுகள்",
  followers: "பின்தொடர்பவர்கள்",
  profileFollowing: "பின்தொடர்கிறது",
  welcome: "வரவேற்பு",
  welcomeSub: "கணக்கை உருவாக்க தொடக்கத் திரைகளிலிருந்து ஆரம்பியுங்கள்.",
  kycVerified: "KYC சரிபார்க்கப்பட்டது",
  unavailable: "கிடைக்கவில்லை",
  chatUnavailable: "ஒத்திசைக்கப்பட்ட பயனர்களுக்கு மட்டுமே அரட்டை.",
  registerHelper: "பதிவு செய்த பயனர்கள் உள்நுழைவுக்கு மாறலாம்.",
  loginHelper: "பதிவின் போது பயன்படுத்திய மொபைல் எண்ணைப் பயன்படுத்துங்கள்.",
  learnTitle: "கற்றல் & சமூகம்",
  learnSub: "படிப்புகள், வழிகாட்டுதல், கேள்வி-பதில், விவசாயி குழுக்கள்",
  coursesComingSoon: "இந்தப் பிரிவு விரைவில். படிப்புகள் தயாராக உள்ளன.",
  loadingCourses: "படிப்புகள் ஏற்றப்படுகின்றன…",
  noCoursesYet: "இதுவரை படிப்புகள் இல்லை.",
  failedLoadCourses: "படிப்புகள் ஏற்றம் தோல்வி",
  featuredCourse: "சிறப்பு படிப்பு",
  marketTitle: "வேளாண் சந்தை",
  marketSearchPlaceholder: "விளைபொருள், விவசாயிகள், உபகரணங்கள் தேடுங்கள்...",
  chooseLanguageTitle: "உங்கள்\nமொழியைத் தேர்ந்தெடுங்கள்",
  chooseLanguageSub: "ஆப்ப் அனுபவத்திற்காக உங்கள் விருப்ப மொழியைத் தேர்ந்தெடுங்கள்.",
  selectLanguage: "மொழியைத் தேர்ந்தெடு",
  editProfileTitle: "சுயவிவரம் திருத்து",
  profileNavTitle: "சுயவிவரம்",
  search: "தேடு",
  searchUsers: "பயனர்களைத் தேடு",
  noUsersFound: "பயனர்கள் கிடைக்கவில்லை.",
  messagesTitle: "செய்திகள்",
  noMessagesTitle: "இதுவரை செய்திகள் இல்லை",
  noMessagesSub: "யாராவது தொடர்பு கொள்ளும்போது இங்கே தெரியும்.",
  sharedReel: "ஒரு ரீல் பகிர்ந்தது",
  sharedMedia: "புகைப்படம்",
  voiceMessage: "குரல் செய்தி",
  recordingVoice: "பதிவு செய்கிறது...",
  galleryPermissionMsg: "படங்களை அனுப்ப கேலரி அனுமதி வழங்கவும்.",
  cameraPermissionMsg: "புகைப்படம் எடுக்க கேமரா அனுமதி வழங்கவும்.",
  micPermissionMsg: "குரல் குறிப்பு அனுப்ப மைக் அனுமதி வழங்கவும்.",
  voiceNoteWebUnavailable: "குரல் குறிப்புகள் மொபைல் ஆப்பில் கிடைக்கும்.",
  voiceRecordFailed: "குரல் குறிப்பை பதிவு செய்ய முடியவில்லை.",
  sharedProfile: "ஒரு சுயவிவரம் பகிர்ந்தது",
  yourStory: "உங்கள் ஸ்டோரி",
  messagePlaceholder: "செய்தி...",
  notifications: "அறிவிப்புகள்",
  noNotifications: "இதுவரை அறிவிப்புகள் இல்லை.",
  accept: "ஏற்றுக்கொள்",
  decline: "நிராகரி",
  notifFollowRequest: "{{name}} பின்தொடர் கோரிக்கை அனுப்பினார்",
  notifNowFollowing: "{{name}} இப்போது உங்களைப் பின்தொடர்கிறார்.",
  notifAcceptedRequest: "{{name}} உங்கள் பின்தொடர் கோரிக்கையை ஏற்றுக்கொண்டார்.",
  notifDeclinedRequest: "{{name}} உங்கள் பின்தொடர் கோரிக்கையை நிராகரித்தார்.",
  nameRequired: "பெயர் தேவை",
  nameRequiredMessage: "தயவுசெய்து உங்கள் பெயரை உள்ளிடுங்கள்.",
  profileSaved: "சேமிக்கப்பட்டது",
  profileUpdated: "சுயவிவரம் புதுப்பிக்கப்பட்டது.",
  saveFailed: "சேமிப்பு தோல்வி",
  saveFailedProfile: "சுயவிவரத்தைப் புதுப்பிக்க இயலவில்லை.",
  permissionNeeded: "அனுமதி தேவை",
  photoLibraryPermission: "தயவுசெய்து புகைப்பட நூலக அனுமதி வழங்குங்கள்.",
  profilePhotoUpdated: "சுயவிவரப் புகைப்படம் பதிவேற்றப்பட்டது.",
  photoSavedLocal: "புகைப்படம் உள்ளூரில் சேமிக்கப்பட்டது",
  photoSavedLocalMessage: "சேவையகத்தில் பதிவேற்ற இயலவில்லை, உள்ளூர் முன்னோட்டம்.",
  changeProfilePhoto: "சுயவிவரப் புகைப்படம் மாற்று",
  uploading: "பதிவேற்றுகிறது…",
  saving: "சேமிக்கிறது…",
  done: "முடிந்தது",
  website: "இணையதளம்",
  bio: "பயோ",
  bioPlaceholder: "உங்கள் பண்ணை அல்லது பணி பற்றி சொல்லுங்கள்",
  location: "இடம்",
  locationPlaceholder: "மாவட்டம் அல்லது பகுதி",
  usernamePlaceholder: "பயனர்பெயர்",
  websitePlaceholder: "https://",
  galleryPosts: "பதிவுகள்",
  galleryReels: "ரீல்கள்",
  gallerySaved: "சேமித்தவை",
  galleryTagged: "டேக்",
  savedReelsEmpty: "சேமித்த ரீல்கள் இங்கே தெரியும்.",
  addToStory: "ஸ்டோரியில் சேர்",
  copyLink: "இணைப்பு நகலெடு",
  shareTo: "பகிர்..",
  whatsapp: "வாட்ஸ்ஆப்",
  messenger: "மெசஞ்சர்",
  snapchat: "ஸ்னாப்சாட்",
  telegram: "டெலிகிராம்",
  x: "X",
  shared: "பகிரப்பட்டது",
  shareFailed: "பகிர்வு தோல்வி",
  shareFailedProfile: "சுயவிவரத்தை இப்போது அனுப்ப இயலவில்லை.",
  profileSharedTo: "சுயவிவரம் {{name}} க்கு அனுப்பப்பட்டது",
  removeFromSaved: "சேமித்தவற்றிலிருந்து நீக்கு",
  savePost: "சேமி",
  savedPostsHint: "சேமித்த பதிவுகள் உங்கள் சுயவிவரத்தில் தெரியும்.",
  sendFailed: "அனுப்புதல் தோல்வி",
  sendFailedReel: "ரீலை அனுப்ப இயலவில்லை. மீண்டும் முயற்சிக்கவும்.",
  cancel: "ரத்து",
  send: "அனுப்பு",
  savePostFailed: "சேமித்த ரீல்களைப் புதுப்பிக்க இயலவில்லை.",
  likes: "லைக்குகள்",
  comments: "கருத்துகள்",
  addCommentPlaceholder: "கருத்து சேர்…",
  replyCancel: "ரத்து",
  viewAllComments: "அனைத்து {{count}} கருத்துகளையும் காண்க",
  copied: "நகலெடுக்கப்பட்டது",
  profileLinkCopied: "சுயவிவர இணைப்பு நகலெடுக்கப்பட்டது.",
  noRecipients: "பெறுநர்கள் இல்லை",
  shareProfileNoRecipients: "அரட்டையில் சுயவிவரம் பகிர பயனர்களைப் பின்தொடருங்கள்.",
  noTaggedPosts: "இதுவரை டேக் பதிவுகள் இல்லை.",
  noChatsFound: "அரட்டைகள் கிடைக்கவில்லை.",
  followBackCapital: "திரும்ப பின்தொடர்",
  notifRepliedComment: "{{name}} உங்கள் கருத்துக்கு பதிலளித்தார்{{excerpt}}",
  notifCommentedOn: "{{name}} உங்கள் {{kind}} மீது கருத்திட்டார்{{excerpt}}",
  notifLikedYour: "{{name}} உங்கள் {{kind}} ஐ லைக் செய்தார்.",
  postKindReel: "ரீல்",
  postKindPost: "பதிவு",
  photoUpdatedTitle: "புதுப்பிக்கப்பட்டது",
  writeReply: "பதில் எழுதுங்கள்…",
  you: "நீங்கள்",
  userWithId: "பயனர் {{id}}",
  originalAudio: "அசல் ஆடியோ",
  feedDemoTest: "டெஸ்ட்",
  feedDemoTestVideoCapture: "டெஸ்ட் வீடியோ கேப்சர்",
  feedTestingFromCamera: "மொபைல் ஆப் கேமராவிலிருந்து சோதனை",
  farmerDefaultName: "விவசாயி",
  likesCountLabel: "{{count}} லைக்குகள்",
  shareReelMessage: "{{name}} Cropvibeல் ஒரு ரீல் பகிர்ந்தார்",
  reportUserPrompt: "{{name}} ஐ ஏன் புகாரளிக்கிறீர்கள்?"
};

export const APP_STRINGS_MR: typeof APP_STRINGS_EN = {
  tabMarket: "बाजार",
  tabCreate: "तयार करा",
  tabCommunity: "समुदाय",
  tabProfile: "प्रोफाइल",
  tabFeed: TAB_FEED_LABEL.mr,
  tabFriends: "मित्र",
  tabLive: "लाइव्ह",
  follow: "फॉलो",
  following: "फॉलो करत आहात",
  followBack: "परत फॉलो",
  requested: "विनंती केली",
  followBusy: "...",
  followFailed: "फॉलो अयशस्वी",
  followFailedMessage: "फॉलो विनंती पाठवता आली नाही.",
  emptyFriendsTitle: "तुम्ही फॉलो करत असलेल्यांचे रील्स नाहीत",
  emptyFriendsSub: "अधिक क्रिएटर्सना फॉलो करा आणि इथे रील्स पहा.",
  emptyReelsTitle: "अजून रील्स नाहीत",
  emptyReelsSub: "सुरुवात करण्यासाठी रील तयार करा.",
  emptyLiveTitle: "लाइव्ह स्ट्रीमिंग लवकरच येत आहे",
  emptyLiveSub: "आम्ही लाइव्ह प्रसारण तयार करत आहोत. प्रतीक्षा करा!",
  emptyFeedTitle: EMPTY_DROPS_TITLE.mr,
  emptyNothingTitle: "इथे अजून काहीच नाही",
  emptyDefaultSub: "हा विभाग भरण्यासाठी रील तयार करा.",
  noLikesYet: "अजून लाइक्स नाहीत",
  noComments: "कोणत्याही टिप्पण्या नाहीत",
  communityTitle: "समुदाय",
  communitySub: "प्रश्नोत्तर, गट आणि शिकणे",
  qaFeed: "प्रश्नोत्तर फीड",
  upvotes: "अपवोट्स",
  answers: "उत्तरे",
  resolved: "निराकरण झाले",
  groups: "गट",
  groupWomenCircle: "महिला मंडळ",
  groupYoungFarmers: "तरुण शेतकरी",
  groupCropGroups: "पीक गट",
  groupFpoNetwork: "FPO नेटवर्क",
  myCommunity: "माझा समुदाय",
  myCommunityDesc: "जतन केलेले प्रश्न, गट आणि सूचना सेटिंग्ज.",
  ask: "विचारा",
  servicesTitle: "सेवा",
  servicesSub: "यंत्रसामग्री, लॉजिस्टिक्स, तज्ञ आणि सल्ला",
  serviceMachineryTitle: "यंत्रसामग्री बुकिंग",
  serviceMachineryDesc: "फिल्टर, शेड्यूल, एस्क्रो आणि पूर्ण रिलीज.",
  serviceLogisticsTitle: "लॉजिस्टिक्स बुकिंग",
  serviceLogisticsDesc: "पिकअप, अंदाज, GPS ट्रॅकिंग, ऑटो रिलीज.",
  serviceExpertTitle: "तज्ञ सल्लामसलत",
  serviceExpertDesc: "तज्ञ, स्लॉट, कॉल सारांश, रेटिंग.",
  serviceWeatherTitle: "हवामान आणि सल्ला",
  serviceWeatherDesc: "हवामान दृश्य आणि कीटक सूचना फीड.",
  open: "उघडा",
  posts: "पोस्ट",
  followers: "फॉलोअर्स",
  profileFollowing: "फॉलो करत आहात",
  welcome: "स्वागत",
  welcomeSub: "खाते तयार करण्यासाठी लॉन्च स्क्रीनवरून सुरू करा.",
  kycVerified: "KYC सत्यापित",
  unavailable: "उपलब्ध नाही",
  chatUnavailable: "चॅट फक्त सिंक वापरकर्त्यांसाठी.",
  registerHelper: "नोंदणीकृत वापरकर्ते लॉगिनवर जाऊ शकतात.",
  loginHelper: "नोंदणीच्या वेळी वापरलेला मोबाइल नंबर वापरा.",
  learnTitle: "शिका & समुदाय",
  learnSub: "अभ्यासक्रम, मार्गदर्शन, प्रश्नोत्तर आणि शेतकरी गट",
  coursesComingSoon: "हा विभाग लवकरच येत आहे. अभ्यासक्रम तयार आहेत.",
  loadingCourses: "अभ्यासक्रम लोड होत आहेत…",
  noCoursesYet: "अजून अभ्यासक्रम नाहीत.",
  failedLoadCourses: "अभ्यासक्रम लोड अयशस्वी",
  featuredCourse: "विशेष अभ्यासक्रम",
  marketTitle: "कृषी बाजार",
  marketSearchPlaceholder: "उत्पादन, शेतकरी, उपकरणे शोधा...",
  chooseLanguageTitle: "तुमची\nभाषा निवडा",
  chooseLanguageSub: "अॅप अनुभवासाठी तुमची आवडती भाषा निवडा.",
  selectLanguage: "भाषा निवडा",
  editProfileTitle: "प्रोफाइल संपादित करा",
  profileNavTitle: "प्रोफाइल",
  search: "शोधा",
  searchUsers: "वापरकर्ते शोधा",
  noUsersFound: "वापरकर्ते सापडले नाहीत.",
  messagesTitle: "संदेश",
  noMessagesTitle: "अजून संदेश नाहीत",
  noMessagesSub: "कोणी संपर्क करेल तेव्हा इथे दिसेल.",
  sharedReel: "रील शेअर केली",
  sharedMedia: "फोटो",
  voiceMessage: "व्हॉइस मेसेज",
  recordingVoice: "रेकॉर्ड होत आहे...",
  galleryPermissionMsg: "फोटो पाठवण्यासाठी गॅलरी परवानगी द्या.",
  cameraPermissionMsg: "फोटो काढण्यासाठी कॅमेरा परवानगी द्या.",
  micPermissionMsg: "व्हॉइस नोट पाठवण्यासाठी माइक परवानगी द्या.",
  voiceNoteWebUnavailable: "व्हॉइस नोट्स मोबाइल अॅपमध्ये उपलब्ध आहेत.",
  voiceRecordFailed: "व्हॉइस नोट रेकॉर्ड करता आला नाही.",
  sharedProfile: "प्रोफाइल शेअर केली",
  yourStory: "तुमची स्टोरी",
  messagePlaceholder: "संदेश...",
  notifications: "सूचना",
  noNotifications: "अजून सूचना नाहीत.",
  accept: "स्वीकारा",
  decline: "नाकारा",
  notifFollowRequest: "{{name}} ने फॉलो विनंती पाठवली",
  notifNowFollowing: "{{name}} आता तुम्हाला फॉलो करत आहे.",
  notifAcceptedRequest: "{{name}} ने तुमची फॉलो विनंती स्वीकारली.",
  notifDeclinedRequest: "{{name}} ने तुमची फॉलो विनंती नाकारली.",
  nameRequired: "नाव आवश्यक",
  nameRequiredMessage: "कृपया तुमचे नाव प्रविष्ट करा.",
  profileSaved: "जतन केले",
  profileUpdated: "प्रोफाइल अपडेट झाली.",
  saveFailed: "जतन अयशस्वी",
  saveFailedProfile: "प्रोफाइल अपडेट करता आली नाही.",
  permissionNeeded: "परवानगी आवश्यक",
  photoLibraryPermission: "कृपया फोटो लायब्ररी परवानगी द्या.",
  profilePhotoUpdated: "प्रोफाइल फोटो अपलोड झाला.",
  photoSavedLocal: "फोटो स्थानिक पातळीवर जतन केला",
  photoSavedLocalMessage: "सर्व्हरवर अपलोड होऊ शकला नाही, स्थानिक पूर्वावलोकन.",
  changeProfilePhoto: "प्रोफाइल फोटो बदला",
  uploading: "अपलोड होत आहे…",
  saving: "जतन होत आहे…",
  done: "झाले",
  website: "वेबसाइट",
  bio: "बायो",
  bioPlaceholder: "तुमच्या शेताबद्दल किंवा कामाबद्दल सांगा",
  location: "स्थान",
  locationPlaceholder: "जिल्हा किंवा प्रदेश",
  usernamePlaceholder: "वापरकर्तानाव",
  websitePlaceholder: "https://",
  galleryPosts: "पोस्ट",
  galleryReels: "रील्स",
  gallerySaved: "जतन केलेले",
  galleryTagged: "टॅग",
  savedReelsEmpty: "जतन केलेले रील्स इथे दिसतील.",
  addToStory: "स्टोरीत जोडा",
  copyLink: "लिंक कॉपी",
  shareTo: "शेअर करा..",
  whatsapp: "व्हॉट्सअॅप",
  messenger: "मेसेंजर",
  snapchat: "स्नॅपचॅट",
  telegram: "टेलिग्राम",
  x: "X",
  shared: "शेअर केले",
  shareFailed: "शेअर अयशस्वी",
  shareFailedProfile: "प्रोफाइल आत्ता पाठवता आली नाही.",
  profileSharedTo: "प्रोफाइल {{name}} ला पाठवली",
  removeFromSaved: "जतन केलेल्यांमधून काढा",
  savePost: "जतन करा",
  savedPostsHint: "जतन केलेल्या पोस्ट तुमच्या प्रोफाइलमध्ये दिसतात.",
  sendFailed: "पाठवणे अयशस्वी",
  sendFailedReel: "रील पाठवता आली नाही. पुन्हा प्रयत्न करा.",
  cancel: "रद्द करा",
  send: "पाठवा",
  savePostFailed: "जतन केलेले रील्स अपडेट करता आले नाहीत.",
  likes: "लाइक्स",
  comments: "टिप्पण्या",
  addCommentPlaceholder: "टिप्पणी जोडा…",
  replyCancel: "रद्द करा",
  viewAllComments: "सर्व {{count}} टिप्पण्या पहा",
  copied: "कॉपी झाले",
  profileLinkCopied: "प्रोफाइल लिंक कॉपी झाली.",
  noRecipients: "प्राप्तकर्ते नाहीत",
  shareProfileNoRecipients: "चॅटमध्ये प्रोफाइल शेअर करण्यासाठी वापरकर्त्यांना फॉलो करा.",
  noTaggedPosts: "अजून टॅग पोस्ट नाहीत.",
  noChatsFound: "चॅट सापडल्या नाहीत.",
  followBackCapital: "परत फॉलो करा",
  notifRepliedComment: "{{name}} ने तुमच्या टिप्पणीला उत्तर दिले{{excerpt}}",
  notifCommentedOn: "{{name}} ने तुमच्या {{kind}} वर टिप्पणी केली{{excerpt}}",
  notifLikedYour: "{{name}} ने तुमच्या {{kind}} ला लाइक केले.",
  postKindReel: "रील",
  postKindPost: "पोस्ट",
  photoUpdatedTitle: "अपडेट",
  writeReply: "उत्तर लिहा…",
  you: "तुम्ही",
  userWithId: "वापरकर्ता {{id}}",
  originalAudio: "मूळ ऑडिओ",
  feedDemoTest: "टेस्ट",
  feedDemoTestVideoCapture: "टेस्ट व्हिडिओ कॅप्चर",
  feedTestingFromCamera: "मोबाइल अॅप कॅमेऱ्यातून चाचणी",
  farmerDefaultName: "शेतकरी",
  likesCountLabel: "{{count}} लाइक्स",
  shareReelMessage: "{{name}} ने Cropvibe वर रील शेअर केली",
  reportUserPrompt: "तुम्ही {{name}} ची तक्रार का करत आहात?"
};

export const APP_STRINGS_BN: typeof APP_STRINGS_EN = {
  tabMarket: "বাজার",
  tabCreate: "তৈরি করুন",
  tabCommunity: "সম্প্রদায়",
  tabProfile: "প্রোফাইল",
  tabFeed: TAB_FEED_LABEL.bn,
  tabFriends: "বন্ধুরা",
  tabLive: "লাইভ",
  follow: "ফলো",
  following: "ফলো করছেন",
  followBack: "ফিরে ফলো",
  requested: "অনুরোধ করা হয়েছে",
  followBusy: "...",
  followFailed: "ফলো ব্যর্থ",
  followFailedMessage: "ফলো অনুরোধ পাঠানো যায়নি।",
  emptyFriendsTitle: "আপনি যাদের ফলো করেন তাদের রিলস নেই",
  emptyFriendsSub: "আরও ক্রিয়েটরদের ফলো করুন এবং এখানে দেখুন।",
  emptyReelsTitle: "এখনও কোনো রিলস নেই",
  emptyReelsSub: "শুরু করতে একটি রিল তৈরি করুন।",
  emptyLiveTitle: "লাইভ স্ট্রিমিং শীঘ্রই আসছে",
  emptyLiveSub: "আমরা লাইভ সম্প্রচার তৈরি করছি। অপেক্ষা করুন!",
  emptyFeedTitle: EMPTY_DROPS_TITLE.bn,
  emptyNothingTitle: "এখানে এখনও কিছুই নেই",
  emptyDefaultSub: "এই বিভাগটি পূরণ করতে একটি রিল তৈরি করুন।",
  noLikesYet: "এখনও কোনো লাইক নেই",
  noComments: "কোনো মন্তব্য নেই",
  communityTitle: "সম্প্রদায়",
  communitySub: "প্রশ্নোত্তর, গোষ্ঠী এবং শেখা",
  qaFeed: "প্রশ্নোত্তর ফিড",
  upvotes: "আপভোট",
  answers: "উত্তর",
  resolved: "সমাধান হয়েছে",
  groups: "গোষ্ঠী",
  groupWomenCircle: "মহিলা চক্র",
  groupYoungFarmers: "তরুণ কৃষক",
  groupCropGroups: "ফসল গোষ্ঠী",
  groupFpoNetwork: "FPO নেটওয়ার্ক",
  myCommunity: "আমার সম্প্রদায়",
  myCommunityDesc: "সংরক্ষিত প্রশ্ন, গোষ্ঠী এবং বিজ্ঞপ্তি সেটিংস।",
  ask: "জিজ্ঞাসা করুন",
  servicesTitle: "সেবা",
  servicesSub: "যন্ত্রপাতি, লজিস্টিকস, বিশেষজ্ঞ এবং পরামর্শ",
  serviceMachineryTitle: "যন্ত্রপাতি বুকিং",
  serviceMachineryDesc: "ফিল্টার, সময়সূচি, এসক্রো এবং সম্পূর্ণ রিলিজ।",
  serviceLogisticsTitle: "লজিস্টিকস বুকিং",
  serviceLogisticsDesc: "পিকআপ, অনুমান, GPS ট্র্যাকিং, অটো রিলিজ।",
  serviceExpertTitle: "বিশেষজ্ঞ পরামর্শ",
  serviceExpertDesc: "বিশেষজ্ঞরা, স্লট, কল সারাংশ, রেটিং।",
  serviceWeatherTitle: "আবহাওয়া ও পরামর্শ",
  serviceWeatherDesc: "আবহাওয়া দৃশ্য এবং কীটপতঙ্গ সতর্কতা ফিড।",
  open: "খুলুন",
  posts: "পোস্ট",
  followers: "ফলোয়ার",
  profileFollowing: "ফলো করছেন",
  welcome: "স্বাগতম",
  welcomeSub: "অ্যাকাউন্ট তৈরি করতে লঞ্চ স্ক্রিন থেকে শুরু করুন।",
  kycVerified: "KYC যাচাই হয়েছে",
  unavailable: "অনুপলব্ধ",
  chatUnavailable: "চ্যাট শুধুমাত্র সিঙ্ক করা ব্যবহারকারীদের জন্য।",
  registerHelper: "নিবন্ধিত ব্যবহারকারীরা লগইনে যেতে পারেন।",
  loginHelper: "নিবন্ধনের সময় ব্যবহৃত মোবাইল নম্বর ব্যবহার করুন।",
  learnTitle: "শিখুন & সম্প্রদায়",
  learnSub: "কোর্স, নির্দেশনা, প্রশ্নোত্তর এবং কৃষক গোষ্ঠী",
  coursesComingSoon: "এই বিভাগ শীঘ্রই আসছে। কোর্সগুলি প্রস্তুত।",
  loadingCourses: "কোর্সগুলি লোড হচ্ছে…",
  noCoursesYet: "এখনও কোনো কোর্স নেই।",
  failedLoadCourses: "কোর্স লোড ব্যর্থ",
  featuredCourse: "বিশেষ কোর্স",
  marketTitle: "কৃষি বাজার",
  marketSearchPlaceholder: "ফসল, কৃষক, সরঞ্জাম খুঁজুন...",
  chooseLanguageTitle: "আপনার\nভাষা বেছে নিন",
  chooseLanguageSub: "অ্যাপ অভিজ্ঞতার জন্য আপনার পছন্দের ভাষা বেছে নিন।",
  selectLanguage: "ভাষা নির্বাচন করুন",
  editProfileTitle: "প্রোফাইল সম্পাদনা",
  profileNavTitle: "প্রোফাইল",
  search: "খুঁজুন",
  searchUsers: "ব্যবহারকারী খুঁজুন",
  noUsersFound: "কোনো ব্যবহারকারী পাওয়া যায়নি।",
  messagesTitle: "বার্তা",
  noMessagesTitle: "এখনও কোনো বার্তা নেই",
  noMessagesSub: "কেউ যোগাযোগ করলে এখানে দেখা যাবে।",
  sharedReel: "একটি রিল শেয়ার করেছেন",
  sharedMedia: "ছবি",
  voiceMessage: "ভয়েস মেসেজ",
  recordingVoice: "রেকর্ড হচ্ছে...",
  galleryPermissionMsg: "ছবি পাঠাতে গ্যালারি অনুমতি দিন।",
  cameraPermissionMsg: "ছবি তুলতে ক্যামেরা অনুমতি দিন।",
  micPermissionMsg: "ভয়েস নোট পাঠাতে মাইক অনুমতি দিন।",
  voiceNoteWebUnavailable: "ভয়েস নোট মোবাইল অ্যাপে উপলব্ধ।",
  voiceRecordFailed: "ভয়েস নোট রেকর্ড করা যায়নি।",
  sharedProfile: "একটি প্রোফাইল শেয়ার করেছেন",
  yourStory: "আপনার স্টোরি",
  messagePlaceholder: "বার্তা...",
  notifications: "বিজ্ঞপ্তি",
  noNotifications: "এখনও কোনো বিজ্ঞপ্তি নেই।",
  accept: "গ্রহণ করুন",
  decline: "প্রত্যাখ্যান",
  notifFollowRequest: "{{name}} ফলো অনুরোধ পাঠিয়েছেন",
  notifNowFollowing: "{{name}} এখন আপনাকে ফলো করছেন।",
  notifAcceptedRequest: "{{name}} আপনার ফলো অনুরোধ গ্রহণ করেছেন।",
  notifDeclinedRequest: "{{name}} আপনার ফলো অনুরোধ প্রত্যাখ্যান করেছেন।",
  nameRequired: "নাম প্রয়োজন",
  nameRequiredMessage: "অনুগ্রহ করে আপনার নাম লিখুন।",
  profileSaved: "সংরক্ষিত",
  profileUpdated: "প্রোফাইল আপডেট হয়েছে।",
  saveFailed: "সংরক্ষণ ব্যর্থ",
  saveFailedProfile: "প্রোফাইল আপডেট করা যায়নি।",
  permissionNeeded: "অনুমতি প্রয়োজন",
  photoLibraryPermission: "অনুগ্রহ করে ফটো লাইব্রেরি অনুমতি দিন।",
  profilePhotoUpdated: "প্রোফাইল ছবি আপলোড হয়েছে।",
  photoSavedLocal: "ছবি স্থানীয়ভাবে সংরক্ষিত",
  photoSavedLocalMessage: "সার্ভারে আপলোড হয়নি, স্থানীয় প্রিভিউ।",
  changeProfilePhoto: "প্রোফাইল ছবি পরিবর্তন করুন",
  uploading: "আপলোড হচ্ছে…",
  saving: "সংরক্ষণ হচ্ছে…",
  done: "সম্পন্ন",
  website: "ওয়েবসাইট",
  bio: "বায়ো",
  bioPlaceholder: "আপনার খামার বা কাজ সম্পর্কে বলুন",
  location: "অবস্থান",
  locationPlaceholder: "জেলা বা অঞ্চল",
  usernamePlaceholder: "ব্যবহারকারীনাম",
  websitePlaceholder: "https://",
  galleryPosts: "পোস্ট",
  galleryReels: "রিলস",
  gallerySaved: "সংরক্ষিত",
  galleryTagged: "ট্যাগ",
  savedReelsEmpty: "সংরক্ষিত রিলস এখানে দেখা যাবে।",
  addToStory: "স্টোরিতে যোগ করুন",
  copyLink: "লিঙ্ক কপি",
  shareTo: "শেয়ার করুন..",
  whatsapp: "হোয়াটসঅ্যাপ",
  messenger: "মেসেঞ্জার",
  snapchat: "স্ন্যাপচ্যাট",
  telegram: "টেলিগ্রাম",
  x: "X",
  shared: "শেয়ার করা হয়েছে",
  shareFailed: "শেয়ার ব্যর্থ",
  shareFailedProfile: "প্রোফাইল এখন পাঠানো যায়নি।",
  profileSharedTo: "প্রোফাইল {{name}} কে পাঠানো হয়েছে",
  removeFromSaved: "সংরক্ষিত থেকে সরান",
  savePost: "সংরক্ষণ",
  savedPostsHint: "সংরক্ষিত পোস্ট আপনার প্রোফাইলে দেখা যায়।",
  sendFailed: "পাঠানো ব্যর্থ",
  sendFailedReel: "রিল পাঠানো যায়নি। আবার চেষ্টা করুন।",
  cancel: "বাতিল",
  send: "পাঠান",
  savePostFailed: "সংরক্ষিত রিলস আপডেট করা যায়নি।",
  likes: "লাইক",
  comments: "মন্তব্য",
  addCommentPlaceholder: "মন্তব্য যোগ করুন…",
  replyCancel: "বাতিল",
  viewAllComments: "সব {{count}} মন্তব্য দেখুন",
  copied: "কপি হয়েছে",
  profileLinkCopied: "প্রোফাইল লিঙ্ক কপি হয়েছে।",
  noRecipients: "কোনো প্রাপক নেই",
  shareProfileNoRecipients: "চ্যাটে প্রোফাইল শেয়ার করতে ব্যবহারকারীদের ফলো করুন।",
  noTaggedPosts: "এখনও কোনো ট্যাগ পোস্ট নেই।",
  noChatsFound: "কোনো চ্যাট পাওয়া যায়নি।",
  followBackCapital: "ফিরে ফলো করুন",
  notifRepliedComment: "{{name}} আপনার মন্তব্যের উত্তর দিয়েছেন{{excerpt}}",
  notifCommentedOn: "{{name}} আপনার {{kind}}-এ মন্তব্য করেছেন{{excerpt}}",
  notifLikedYour: "{{name}} আপনার {{kind}} লাইক করেছেন।",
  postKindReel: "রিল",
  postKindPost: "পোস্ট",
  photoUpdatedTitle: "আপডেট হয়েছে",
  writeReply: "উত্তর লিখুন…",
  you: "আপনি",
  userWithId: "ব্যবহারকারী {{id}}",
  originalAudio: "মূল অডিও",
  feedDemoTest: "টেস্ট",
  feedDemoTestVideoCapture: "টেস্ট ভিডিও ক্যাপচার",
  feedTestingFromCamera: "মোবাইল অ্যাপ ক্যামেরা থেকে পরীক্ষা",
  farmerDefaultName: "কৃষক",
  likesCountLabel: "{{count}} লাইক",
  shareReelMessage: "{{name}} Cropvibe-এ একটি রিল শেয়ার করেছেন",
  reportUserPrompt: "আপনি কেন {{name}} কে রিপোর্ট করছেন?"
};
