/** Shared UI strings for screens not yet split into feature-specific bundles. */
export const COMMON_UI_EN = {
  loginRequired: "Login required",
  loginRequiredChat: "Please log in to send reels in chat.",
  loginRequiredSave: "Please log in to save reels.",
  loginRequiredReport: "Please log in to report posts.",
  loginRequiredDelete: "Please log in to delete posts.",
  chatUnavailableSend: "This user cannot receive messages yet.",
  sentTitle: "Sent",
  reelSentTo: "Reel sent to {{name}}.",
  shareFailedSystem: "Could not open system share.",
  noMediaTitle: "No media",
  noMediaStory: "This reel has no media to add as story.",
  addedTitle: "Added",
  addedToStory: "Reel added to your story.",
  copiedPostLink: "Post link copied to clipboard.",
  copyFailedTitle: "Copy failed",
  copyFailed: "Could not copy the link.",
  gotItHidePost: "Got it",
  gotItHidePostMsg: "We will hide this post and tune what we show you on this device.",
  thanksReport: "Thanks",
  thanksReportMsg: "We received your report and will review it.",
  reportFailed: "Report failed",
  notAllowedTitle: "Not allowed",
  notAllowedDeleteOwn: "You can only delete your own posts.",
  deleteFailed: "Delete failed",
  deletePostTitle: "Delete this post?",
  deletePostBody: "This cannot be undone.",
  deleteConfirm: "Delete",
  reportSpam: "Spam or misleading",
  reportHarassment: "Harassment or bullying",
  reportHate: "Hate speech or symbols",
  reportNudity: "Nudity or sexual content",
  reportViolence: "Violence or dangerous acts",
  reportScam: "Scam or fraud",
  reportIp: "Intellectual property violation",
  reportOther: "Something else",
  myFarm: "My Farm",
  unknownLocation: "Unknown",
  liveStream: "Live stream",
  liveNow: "Live now",
  goLive: "Go Live",
  liveBadge: "LIVE",
  liveEndedBadge: "ENDED",
  noOneLive: "No one is live right now",
  popularLive: "Popular live",
  completedLive: "Completed live",
  noLiveStreamsYet: "No live streams yet",
  noLiveStreamsSub: "When creators go live, they will show up here.",
  noCompletedLiveYet: "No completed live streams yet",
  noCompletedLiveSub: "Past live streams will appear here after they end.",
  liveCompletedLabel: "Completed",
  noCompletedRecording: "Recording was not saved for this live.",
  startLive: "Start a live",
  publicAccount: "Public account",
  messageBtn: "Message",
  tryAgainMoment: "Try again in a moment.",
  viewProfilePhoto: "View profile photo",
  cannotOpenChat: "Cannot open chat for this user yet.",
  createModePost: "POST",
  createModeStory: "STORY",
  createModeReel: "REEL",
  createModeLive: "LIVE",
  filterNormal: "Normal",
  filterWarm: "Warm",
  filterCool: "Cool",
  filterBw: "B&W",
  filterVivid: "Vivid",
  filterSunset: "Sunset",
  filterNoir: "Noir",
  createPreviewReel: "Reel",
  createPreviewPost: "New Post",
  createPreviewStory: "Story",
  createPreviewTitle: "Create",
  tagPeople: "Tag people",
  addLocation: "Add location",
  locationPrefix: "Location: {{place}}",
  addAudio: "Add audio",
  audioPrefix: "Audio: {{title}}",
  audience: "Audience",
  audienceSoon: "Audience controls coming soon.",
  scheduleLiveTitle: "Schedule live",
  scheduleLiveBody: "Scheduling will be available in a future update.",
  shareBtn: "Share",
  nextBtn: "Next",
  writeReelCaptionPh: "Write a reel caption...",
  writeCaptionPh: "Write a caption...",
  typeTextPlaceholder: "Type text",
  recents: "Recents",
  unknownArtist: "Unknown artist",
  unknownTitle: "Unknown",
  createErrSelectPhoto: "Please select at least one photo.",
  createErrCarouselPhotos: "Photo carousels can only include pictures. Pick one video for a video post.",
  createErrPostPhotosOnly: "Post grid supports photos only. Choose Reel for video.",
  createErrCameraPerm: "Camera permission is required.",
  createErrReelVideoOnly: "Reels support video only. Please select or record a video.",
  createErrCapturePhoto: "Could not capture photo.",
  createErrReelVideoOnlyShort: "Reels support video only.",
  createErrMediaPerm: "Media library permission is required.",
  createErrChooseOption: "Choose an option to continue.",
  createErrStoryMedia: "Please record or upload story media.",
  createErrCaptionRequired: "Caption is required.",
  createErrReelMedia: "Please record or upload a reel video.",
  createErrPostMedia: "Please add media for your post.",
  createErrReelSingleVideo: "A reel must be a single video.",
  createErrUploadReel: "Please upload one video reel.",
  createErrMixedMedia: "Use either one video or multiple photos — not both.",
  createErrOneVideo: "Only one video per post.",
  createErrUploadImages: "Could not upload images.",
  createErrPublish: "Failed to publish video.",
  createErrAudioPreview: "Could not preview this audio track.",
  createErrAudioFetch: "Could not fetch songs. Check internet and try again.",
  createToolAudio: "Audio",
  createToolText: "Text",
  createToolOverlay: "Overlay",
  createToolFilter: "Filter",
  createToolEdit: "Edit",
  openGallery: "Open photo gallery",
  videoSizeLimit: "Video is {{size}}MB. Please select a video under {{max}}MB.",
  languageNoteTitle: "About language",
  languageNoteBody:
    "Buttons, menus, and messages change with your language. Posts you write stay as you typed them unless they use common crop words from our dictionary.",
  back: "Back",
  continue: "Continue",
  roleSelectionTitle: "How will you use Cropvibe?",
  roleSelectionSub: "Pick one — you can explore other areas anytime.",
  roleBuyerTitle: "Buyer",
  roleBuyerDesc: "Shop produce, machinery, and services",
  roleSellerTitle: "Seller",
  roleSellerDesc: "List from your farm and manage orders",
  roleExpertTitle: "Expert",
  roleExpertDesc: "Teach courses and advise the community",
  personalInfoTitle: "About you",
  personalInfoSubtitle: "We use this to personalize Cropvibe. You can edit it anytime in profile.",
  personalInfoPrimaryLabel: "Create account",
  fullNameLabel: "Full name",
  fullNamePlaceholder: "Your name",
  emailLabel: "Email",
  emailPlaceholder: "you@example.com",
  dobLabel: "Date of birth",
  dobPlaceholder: "YYYY-MM-DD (optional)",
  languageLocationTitle: "Language & location",
  languageLocationSub: "Optional shortcuts for regional content",
  preferredLanguageLabel: "Preferred language",
  preferredLanguagePlaceholder: "e.g. English, Telugu",
  districtOrCityPlaceholder: "District or city",
  addLanguageLocation: "Add language & location",
  otpTitle: "6 Digit Code",
  otpSubtitle: "Please enter the verification code sent to {{phone}}",
  verifying: "Verifying...",
  verifyContinue: "Verify & Continue",
  invalidOtp: "Invalid OTP. Please try again.",
  resendCode: "Resend the code?",
  resend: "Resend",
  sending: "Sending...",
  failedResendOtp: "Failed to resend OTP.",
  buyerInterestsTitle: "Your interests",
  buyerInterestsSubtitle: "What do you usually shop for? Helps us rank listings and tips.",
  interestsLabel: "Crops, categories, or goals",
  interestsPlaceholder: "e.g. Organic vegetables, drip irrigation, tractor parts",
  buyerDeliveryTitle: "Delivery address",
  buyerDeliverySubtitle: "Default drop-off for marketplace orders (you can add more later).",
  addressLineLabel: "Address line",
  addressLinePlaceholder: "Village, landmark, street",
  districtLabel: "District",
  pinCodeOptional: "PIN code (optional)",
  sellerFarmTitle: "Farm details",
  sellerFarmSubtitle: "Tell buyers who you are. You can refine this on your seller profile later.",
  farmNameLabel: "Farm or business name",
  landAcresLabel: "Land under cultivation (acres, optional)",
  acresPlaceholder: "e.g. 12.5",
  primaryCropLabel: "Primary crop or product",
  primaryCropPlaceholder: "e.g. Basmati, dairy, nursery",
  sellerKycTitle: "KYC basics",
  sellerKycSubtitle: "Demo step — production would capture ID document OCR and match your name.",
  legalNameLabel: "Legal name (as on ID)",
  idLast4Label: "Last 4 digits of Aadhaar / ID reference",
  sellerBankTitle: "Bank account",
  sellerBankSubtitle: "Payouts for sold listings deposit here. Demo only — do not enter real banking data.",
  continueToSecurity: "Continue to security",
  accountHolderLabel: "Account holder name",
  ifscLabel: "IFSC",
  accountNumberLabel: "Account number",
  expertDomainTitle: "Your domain",
  expertDomainSubtitle: "What topics or crops do you advise on? Shown on your expert profile.",
  specializationsLabel: "Specializations",
  specializationsPlaceholder: "e.g. Soil health, polyhouse tomatoes, organic certification",
  yearsExperienceLabel: "Years of experience (optional)",
  yearsPlaceholder: "e.g. 8",
  expertCredentialsTitle: "Credentials",
  expertCredentialsSubtitle: "Degrees, certifications, or institutional affiliations learners should know about.",
  professionalHeadlineLabel: "Professional headline",
  professionalHeadlinePlaceholder: "e.g. Agronomist, KVK extension officer",
  certificationsOptionalLabel: "Certifications (optional)",
  certificationsPlaceholder: "B.Sc. Ag, Certificate in organic inspection…",
  expertVerificationTitle: "Expert verification",
  expertVerificationSubtitle:
    "We review credentials and sample content before badges go live. This demo marks the step complete when you continue.",
  submitForReviewDemo: "Submit for review (demo)",
  whatHappensNext: "What happens next",
  expertVerificationBody:
    "Production: upload a short teaching clip, references, and optional ID. Our team typically responds within 48 hours.",
  securityVerificationTitle: "Security verification",
  securityVerificationSubtitle:
    "Face liveness, ID OCR, and third-party KYC would plug in here. Tap below to simulate a successful check.",
  completeVerificationDemo: "Complete verification (demo)",
  checksTitle: "Checks",
  checkFaceLiveness: "• Face liveness (anti-spoof)",
  checkGovIdOcr: "• Government ID capture & OCR",
  checkVendorKyc: "• Optional vendor KYC match",
  buyerWalkthroughTitle: "Quick tips",
  buyerWalkthroughSubtitle: "A short walk-through — we'll remind you inside the app with gentle nudges.",
  buyerWalkthroughNudge1: "Pull down on Home to refresh your feed.",
  buyerWalkthroughNudge2: "Use the + tab to post a harvest story or question.",
  buyerWalkthroughNudge3: "Verified badges on listings mean the seller passed basic checks.",
  firstTimeRoleTitle: "What do you do?",
  firstTimeRoleSubtitle: "Select your role within the app.",
  firstTimeRoleFarmer: "Farmer",
  firstTimeRoleFarmerSub: "I cultivate crops and sell my produce.",
  firstTimeRoleConsumer: "Consumer",
  firstTimeRoleConsumerSub: "I buy produce for home and business use.",
  firstTimeRoleEducator: "Educator",
  firstTimeRoleEducatorSub: "I share knowledge, tools and best practices.",
  firstTimeRoleLogistics: "Logistics",
  firstTimeRoleLogisticsSub: "I help move farm produce and inputs.",
  firstTimeCropsTitle: "What do you grow?",
  firstTimeCropsSubtitle: "Tell us what crops you grow to receive relevant recommendations.",
  searchByCrop: "Search by crop",
  cropGroupGrains: "GRAINS & CEREALS",
  cropGroupVegetables: "VEGETABLES",
  cropGroupFruits: "FRUITS",
  cropGroupPulses: "PULSES",
  cropRice: "Rice",
  cropWheat: "Wheat",
  cropJowar: "Jowar",
  cropMaize: "Maize",
  cropBajra: "Bajra",
  cropTomato: "Tomato",
  cropPotato: "Potato",
  cropOnion: "Onion",
  cropChilli: "Chilli",
  cropBrinjal: "Brinjal",
  cropMango: "Mango",
  cropBanana: "Banana",
  cropGrapes: "Grapes",
  cropOrange: "Orange",
  cropApple: "Apple",
  cropTur: "Tur",
  cropMoong: "Moong",
  cropUrad: "Urad",
  cropMasoor: "Masoor",
  cropChana: "Chana",
  locationLabel: "Location",
  idLast4Placeholder: "••••"
} as const;

export const COMMON_UI_HI: typeof COMMON_UI_EN = {
  loginRequired: "लॉगिन आवश्यक",
  loginRequiredChat: "चैट में रील भेजने के लिए लॉगिन करें।",
  loginRequiredSave: "रील सेव करने के लिए लॉगिन करें।",
  loginRequiredReport: "पोस्ट रिपोर्ट करने के लिए लॉगिन करें।",
  loginRequiredDelete: "पोस्ट हटाने के लिए लॉगिन करें।",
  chatUnavailableSend: "यह उपयोगकर्ता अभी संदेश नहीं ले सकता।",
  sentTitle: "भेजा गया",
  reelSentTo: "रील {{name}} को भेजी गई।",
  shareFailedSystem: "सिस्टम शेयर नहीं खुल सका।",
  noMediaTitle: "कोई मीडिया नहीं",
  noMediaStory: "इस रील में स्टोरी के लिए मीडिया नहीं है।",
  addedTitle: "जोड़ा गया",
  addedToStory: "रील आपकी स्टोरी में जोड़ी गई।",
  copiedPostLink: "पोस्ट लिंक कॉपी हो गया।",
  copyFailedTitle: "कॉपी विफल",
  copyFailed: "लिंक कॉपी नहीं हो सका।",
  gotItHidePost: "ठीक है",
  gotItHidePostMsg: "हम इस पोस्ट को छुपाएंगे और इस डिवाइस पर आपके लिए फ़ीड ठीक करेंगे।",
  thanksReport: "धन्यवाद",
  thanksReportMsg: "आपकी रिपोर्ट मिली, हम जल्द समीक्षा करेंगे।",
  reportFailed: "रिपोर्ट विफल",
  notAllowedTitle: "अनुमति नहीं",
  notAllowedDeleteOwn: "आप केवल अपनी पोस्ट हटा सकते हैं।",
  deleteFailed: "हटाना विफल",
  deletePostTitle: "यह पोस्ट हटाएं?",
  deletePostBody: "यह वापस नहीं हो सकता।",
  deleteConfirm: "हटाएं",
  reportSpam: "स्पैम या भ्रामक",
  reportHarassment: "उत्पीड़न या धमकाना",
  reportHate: "नफरत भाषण या प्रतीक",
  reportNudity: "नग्नता या यौन सामग्री",
  reportViolence: "हिंसा या खतरनाक कृत्य",
  reportScam: "धोखा या फ्रॉड",
  reportIp: "बौद्धिक संपदा उल्लंघन",
  reportOther: "कुछ और",
  myFarm: "मेरा खेत",
  unknownLocation: "अज्ञात",
  liveStream: "लाइव स्ट्रीम",
  liveNow: "अभी लाइव",
  goLive: "लाइव जाएं",
  liveBadge: "लाइव",
  liveEndedBadge: "समाप्त",
  noOneLive: "अभी कोई लाइव नहीं",
  popularLive: "लोकप्रिय लाइव",
  completedLive: "पूर्ण लाइव",
  noLiveStreamsYet: "अभी कोई लाइव स्ट्रीम नहीं",
  noLiveStreamsSub: "जब क्रिएटर लाइव होंगे, वे यहाँ दिखेंगे।",
  noCompletedLiveYet: "अभी कोई पूर्ण लाइव स्ट्रीम नहीं",
  noCompletedLiveSub: "लाइव समाप्त होने के बाद पुरानी स्ट्रीम यहाँ दिखेंगी।",
  liveCompletedLabel: "पूर्ण",
  noCompletedRecording: "इस लाइव की रिकॉर्डिंग सहेजी नहीं गई।",
  startLive: "लाइव शुरू करें",
  publicAccount: "सार्वजनिक खाता",
  messageBtn: "संदेश",
  tryAgainMoment: "थोड़ी देर बाद फिर कोशिश करें।",
  viewProfilePhoto: "प्रोफाइल फोटो देखें",
  cannotOpenChat: "इस उपयोगकर्ता के लिए चैट अभी नहीं खुल सकती।",
  createModePost: "पोस्ट",
  createModeStory: "स्टोरी",
  createModeReel: "रील",
  createModeLive: "लाइव",
  filterNormal: "सामान्य",
  filterWarm: "गर्म",
  filterCool: "ठंडा",
  filterBw: "काला-सफेद",
  filterVivid: "चमकीला",
  filterSunset: "सूर्यास्त",
  filterNoir: "नोयर",
  createPreviewReel: "रील",
  createPreviewPost: "नई पोस्ट",
  createPreviewStory: "स्टोरी",
  createPreviewTitle: "बनाएं",
  tagPeople: "लोगों को टैग करें",
  addLocation: "स्थान जोड़ें",
  locationPrefix: "स्थान: {{place}}",
  addAudio: "ऑडियो जोड़ें",
  audioPrefix: "ऑडियो: {{title}}",
  audience: "दर्शक",
  audienceSoon: "दर्शक नियंत्रण जल्द आएंगे।",
  scheduleLiveTitle: "लाइव शेड्यूल",
  scheduleLiveBody: "शेड्यूलिंग भविष्य के अपडेट में आएगी।",
  shareBtn: "शेयर",
  nextBtn: "आगे",
  writeReelCaptionPh: "रील कैप्शन लिखें...",
  writeCaptionPh: "कैप्शन लिखें...",
  typeTextPlaceholder: "टेक्स्ट लिखें",
  recents: "हाल के",
  unknownArtist: "अज्ञात कलाकार",
  unknownTitle: "अज्ञात",
  createErrSelectPhoto: "कम से कम एक फोटो चुनें।",
  createErrCarouselPhotos: "कैरोसेल में केवल फोटो। वीडियो पोस्ट के लिए एक वीडियो चुनें।",
  createErrPostPhotosOnly: "पोस्ट ग्रिड में केवल फोटो। वीडियो के लिए रील चुनें।",
  createErrCameraPerm: "कैमरा अनुमति आवश्यक है।",
  createErrReelVideoOnly: "रील केवल वीडियो। वीडियो चुनें या रिकॉर्ड करें।",
  createErrCapturePhoto: "फोटो कैप्चर नहीं हो सका।",
  createErrReelVideoOnlyShort: "रील केवल वीडियो।",
  createErrMediaPerm: "मीडिया लाइब्रेरी अनुमति आवश्यक है।",
  createErrChooseOption: "जारी रखने के लिए एक विकल्प चुनें।",
  createErrStoryMedia: "स्टोरी मीडिया रिकॉर्ड या अपलोड करें।",
  createErrCaptionRequired: "कैप्शन आवश्यक है।",
  createErrReelMedia: "रील वीडियो रिकॉर्ड या अपलोड करें।",
  createErrPostMedia: "पोस्ट के लिए मीडिया जोड़ें।",
  createErrReelSingleVideo: "रील में एक ही वीडियो होना चाहिए।",
  createErrUploadReel: "एक वीडियो रील अपलोड करें।",
  createErrMixedMedia: "एक वीडियो या कई फोटो — दोनों नहीं।",
  createErrOneVideo: "प्रति पोस्ट एक वीडियो।",
  createErrUploadImages: "छवियां अपलोड नहीं हो सकीं।",
  createErrPublish: "वीडियो प्रकाशित नहीं हो सका।",
  createErrAudioPreview: "ऑडियो पूर्वावलोकन नहीं हो सका।",
  createErrAudioFetch: "गाने लोड नहीं हुए। इंटरनेट जांचें।",
  createToolAudio: "ऑडियो",
  createToolText: "टेक्स्ट",
  createToolOverlay: "ओवरले",
  createToolFilter: "फ़िल्टर",
  createToolEdit: "संपादन",
  openGallery: "फोटो गैलरी खोलें",
  videoSizeLimit: "वीडियो {{size}}MB है। {{max}}MB से कम चुनें।",
  languageNoteTitle: "भाषा के बारे में",
  languageNoteBody:
    "बटन, मेनू और संदेश आपकी भाषा में बदलते हैं। आपकी लिखी पोस्ट वैसी ही रहती हैं जब तक शब्द हमारे शब्दकोश में न हों।",
  back: "वापस",
  continue: "जारी रखें",
  roleSelectionTitle: "आप क्रॉपवाइब का उपयोग कैसे करेंगे?",
  roleSelectionSub: "एक विकल्प चुनें — आप कभी भी अन्य क्षेत्रों को देख सकते हैं।",
  roleBuyerTitle: "खरीदार",
  roleBuyerDesc: "उत्पाद, मशीनरी और सेवाएं खरीदें",
  roleSellerTitle: "विक्रेता",
  roleSellerDesc: "अपने खेत से सूची बनाएं और ऑर्डर प्रबंधित करें",
  roleExpertTitle: "विशेषज्ञ",
  roleExpertDesc: "कोर्स पढ़ाएं और समुदाय को सलाह दें",
  personalInfoTitle: "आपके बारे में",
  personalInfoSubtitle: "हम इससे क्रॉपवाइब को व्यक्तिगत बनाते हैं। आप इसे प्रोफाइल में कभी भी संपादित कर सकते हैं।",
  personalInfoPrimaryLabel: "खाता बनाएं",
  fullNameLabel: "पूरा नाम",
  fullNamePlaceholder: "आपका नाम",
  emailLabel: "ईमेल",
  emailPlaceholder: "you@example.com",
  dobLabel: "जन्म तिथि",
  dobPlaceholder: "YYYY-MM-DD (वैकल्पिक)",
  languageLocationTitle: "भाषा और स्थान",
  languageLocationSub: "क्षेत्रीय सामग्री के लिए वैकल्पिक शॉर्टकट",
  preferredLanguageLabel: "पसंदीदा भाषा",
  preferredLanguagePlaceholder: "जैसे अंग्रेज़ी, हिंदी, तेलुगु",
  districtOrCityPlaceholder: "जिला या शहर",
  addLanguageLocation: "भाषा और स्थान जोड़ें",
  otpTitle: "6 अंकों का कोड",
  otpSubtitle: "कृपया {{phone}} पर भेजा गया सत्यापन कोड दर्ज करें",
  verifying: "सत्यापित हो रहा है...",
  verifyContinue: "सत्यापित करें और जारी रखें",
  invalidOtp: "अमान्य OTP। कृपया पुनः प्रयास करें।",
  resendCode: "कोड दोबारा भेजें?",
  resend: "पुनः भेजें",
  sending: "भेजा जा रहा है...",
  failedResendOtp: "OTP पुनः भेजने में विफल।",
  buyerInterestsTitle: "आपकी रुचियां",
  buyerInterestsSubtitle: "आप आमतौर पर क्या खरीदते हैं? इससे सूचियों और सुझावों को क्रमबद्ध करने में मदद मिलती है।",
  interestsLabel: "फसलें, श्रेणियां या लक्ष्य",
  interestsPlaceholder: "जैसे जैविक सब्जियां, ड्रिप सिंचाई, ट्रैक्टर पुर्जे",
  buyerDeliveryTitle: "डिलीवरी पता",
  buyerDeliverySubtitle: "मार्केटप्लेस ऑर्डर के लिए डिफ़ॉल्ट ड्रॉप-ऑफ (बाद में और जोड़ सकते हैं)।",
  addressLineLabel: "पता पंक्ति",
  addressLinePlaceholder: "गांव, लैंडमार्क, सड़क",
  districtLabel: "जिला",
  pinCodeOptional: "पिन कोड (वैकल्पिक)",
  sellerFarmTitle: "खेत का विवरण",
  sellerFarmSubtitle: "खरीदारों को बताएं आप कौन हैं। बाद में विक्रेता प्रोफाइल में इसे और बेहतर कर सकते हैं।",
  farmNameLabel: "खेत या व्यवसाय का नाम",
  landAcresLabel: "खेती योग्य भूमि (एकड़, वैकल्पिक)",
  acresPlaceholder: "जैसे 12.5",
  primaryCropLabel: "मुख्य फसल या उत्पाद",
  primaryCropPlaceholder: "जैसे बासमती, डेयरी, नर्सरी",
  sellerKycTitle: "KYC मूल बातें",
  sellerKycSubtitle: "डेमो चरण — वास्तविक में ID दस्तावेज़ OCR और नाम मिलान होगा।",
  legalNameLabel: "कानूनी नाम (ID के अनुसार)",
  idLast4Label: "आधार / ID संदर्भ के अंतिम 4 अंक",
  sellerBankTitle: "बैंक खाता",
  sellerBankSubtitle: "बिकी सूचियों का भुगतान यहाँ जमा होगा। केवल डेमो — वास्तविक बैंक विवरण न दर्ज करें।",
  continueToSecurity: "सुरक्षा पर जारी रखें",
  accountHolderLabel: "खाताधारक का नाम",
  ifscLabel: "IFSC",
  accountNumberLabel: "खाता संख्या",
  expertDomainTitle: "आपका क्षेत्र",
  expertDomainSubtitle: "आप किन विषयों या फसलों पर सलाह देते हैं? यह आपकी विशेषज्ञ प्रोफाइल पर दिखेगा।",
  specializationsLabel: "विशेषज्ञता",
  specializationsPlaceholder: "जैसे मृदा स्वास्थ्य, पॉलीहाउस टमाटर, जैविक प्रमाणन",
  yearsExperienceLabel: "अनुभव के वर्ष (वैकल्पिक)",
  yearsPlaceholder: "जैसे 8",
  expertCredentialsTitle: "योग्यता",
  expertCredentialsSubtitle: "डिग्री, प्रमाणपत्र या संस्थागत संबद्धता जो शिक्षार्थियों को जाननी चाहिए।",
  professionalHeadlineLabel: "पेशेवर शीर्षक",
  professionalHeadlinePlaceholder: "जैसे कृषि वैज्ञानिक, KVK विस्तार अधिकारी",
  certificationsOptionalLabel: "प्रमाणपत्र (वैकल्पिक)",
  certificationsPlaceholder: "B.Sc. Ag, जैविक निरीक्षण प्रमाणपत्र…",
  expertVerificationTitle: "विशेषज्ञ सत्यापन",
  expertVerificationSubtitle:
    "बैज लाइव होने से पहले हम योग्यता और नमूना सामग्री की समीक्षा करते हैं। यह डेमो जारी रखने पर चरण पूर्ण करता है।",
  submitForReviewDemo: "समीक्षा के लिए भेजें (डेमो)",
  whatHappensNext: "आगे क्या होगा",
  expertVerificationBody:
    "वास्तविक में: संक्षिप्त शिक्षण क्लिप, संदर्भ और वैकल्पिक ID अपलोड करें। हमारी टीम आमतौर पर 48 घंटों में जवाब देती है।",
  securityVerificationTitle: "सुरक्षा सत्यापन",
  securityVerificationSubtitle:
    "चेहरे की जीवंतता, ID OCR और तृतीय-पक्ष KYC यहाँ जुड़ेगा। सफल जांच का अनुकरण करने के लिए नीचे टैप करें।",
  completeVerificationDemo: "सत्यापन पूर्ण करें (डेमो)",
  checksTitle: "जांच",
  checkFaceLiveness: "• चेहरे की जीवंतता (एंटी-स्पूफ)",
  checkGovIdOcr: "• सरकारी ID कैप्चर और OCR",
  checkVendorKyc: "• वैकल्पिक विक्रेता KYC मिलान",
  buyerWalkthroughTitle: "त्वरित सुझाव",
  buyerWalkthroughSubtitle: "एक संक्षिप्त परिचय — ऐप के अंदर हम आपको कोमल अनुस्मारक देंगे।",
  buyerWalkthroughNudge1: "फ़ीड रिफ्रेश करने के लिए होम पर नीचे खींचें।",
  buyerWalkthroughNudge2: "फसल की कहानी या प्रश्न पोस्ट करने के लिए + टैब का उपयोग करें।",
  buyerWalkthroughNudge3: "सूचियों पर सत्यापित बैज का मतलब है कि विक्रेता ने बुनियादी जांच पास की है।",
  firstTimeRoleTitle: "आप क्या करते हैं?",
  firstTimeRoleSubtitle: "ऐप में अपनी भूमिका चुनें।",
  firstTimeRoleFarmer: "किसान",
  firstTimeRoleFarmerSub: "मैं फसलें उगाता/उगाती हूँ और अपनी उपज बेचता/बेचती हूँ।",
  firstTimeRoleConsumer: "उपभोक्ता",
  firstTimeRoleConsumerSub: "मैं घर और व्यवसाय के लिए उपज खरीदता/खरीदती हूँ।",
  firstTimeRoleEducator: "शिक्षक",
  firstTimeRoleEducatorSub: "मैं ज्ञान, उपकरण और सर्वोत्तम प्रथाएं साझा करता/करती हूँ।",
  firstTimeRoleLogistics: "लॉजिस्टिक्स",
  firstTimeRoleLogisticsSub: "मैं कृषि उपज और सामग्री की ढुलाई में मदद करता/करती हूँ।",
  firstTimeCropsTitle: "आप क्या उगाते हैं?",
  firstTimeCropsSubtitle: "प्रासंगिक सुझाव पाने के लिए बताएं आप कौन-सी फसलें उगाते हैं।",
  searchByCrop: "फसल से खोजें",
  cropGroupGrains: "अनाज और दलहन",
  cropGroupVegetables: "सब्जियां",
  cropGroupFruits: "फल",
  cropGroupPulses: "दालें",
  cropRice: "चावल",
  cropWheat: "गेहूं",
  cropJowar: "ज्वार",
  cropMaize: "मक्का",
  cropBajra: "बाजरा",
  cropTomato: "टमाटर",
  cropPotato: "आलू",
  cropOnion: "प्याज",
  cropChilli: "मिर्च",
  cropBrinjal: "बैंगन",
  cropMango: "आम",
  cropBanana: "केला",
  cropGrapes: "अंगूर",
  cropOrange: "संतरा",
  cropApple: "सेब",
  cropTur: "अरहर",
  cropMoong: "मूंग",
  cropUrad: "उड़द",
  cropMasoor: "मसूर",
  cropChana: "चना",
  locationLabel: "स्थान",
  idLast4Placeholder: "••••"
};

export const COMMON_UI_TE: typeof COMMON_UI_EN = {
  loginRequired: "లాగిన్ అవసరం",
  loginRequiredChat: "చాట్‌లో రీల్ పంపడానికి లాగిన్ అవ్వండి.",
  loginRequiredSave: "రీల్స్ సేవ్ చేయడానికి లాగిన్ అవ్వండి.",
  loginRequiredReport: "పోస్ట్ రిపోర్ట్ చేయడానికి లాగిన్ అవ్వండి.",
  loginRequiredDelete: "పోస్ట్ తొలగించడానికి లాగిన్ అవ్వండి.",
  chatUnavailableSend: "ఈ వినియోగదారు ఇంకా సందేశాలు స్వీకరించలేరు.",
  sentTitle: "పంపబడింది",
  reelSentTo: "రీల్ {{name}} కు పంపబడింది.",
  shareFailedSystem: "సిస్టమ్ షేర్ తెరవలేకపోయింది.",
  noMediaTitle: "మీడియా లేదు",
  noMediaStory: "ఈ రీల్‌లో స్టోరీకి మీడియా లేదు.",
  addedTitle: "జోడించబడింది",
  addedToStory: "రీల్ మీ స్టోరీకి జోడించబడింది.",
  copiedPostLink: "పోస్ట్ లింక్ కాపీ అయింది.",
  copyFailedTitle: "కాపీ విఫలమైంది",
  copyFailed: "లింక్ కాపీ కాలేదు.",
  gotItHidePost: "సరే",
  gotItHidePostMsg: "ఈ పోస్ట్ దాచబడుతుంది; ఈ పరికరంలో మీ ఫీడ్ మెరుగుపరచబడుతుంది.",
  thanksReport: "ధన్యవాదాలు",
  thanksReportMsg: "మీ రిపోర్ట్ అందింది, త్వరలో సమీక్షిస్తాము.",
  reportFailed: "రిపోర్ట్ విఫలమైంది",
  notAllowedTitle: "అనుమతి లేదు",
  notAllowedDeleteOwn: "మీరు మీ పోస్ట్‌లనే తొలగించవచ్చు.",
  deleteFailed: "తొలగింపు విఫలమైంది",
  deletePostTitle: "ఈ పోస్ట్ తొలగించాలా?",
  deletePostBody: "దీన్ని రద్దు చేయలేము.",
  deleteConfirm: "తొలగించు",
  reportSpam: "స్పామ్ లేదా మోసపూరిత",
  reportHarassment: "వేధింపు లేదా బుల్లింగ్",
  reportHate: "ద్వేష ప్రసంగం లేదా చిహ్నాలు",
  reportNudity: "నగ్నత్వం లేదా లైంగిక కంటెంట్",
  reportViolence: "హింస లేదా ప్రమాదకర చర్యలు",
  reportScam: "మోసం లేదా వంచన",
  reportIp: "బౌద్ధిక ఆస్తి ఉల్లంఘన",
  reportOther: "ఇతరతరం",
  myFarm: "నా పొలం",
  unknownLocation: "తెలియదు",
  liveStream: "లైవ్ స్ట్రీమ్",
  liveNow: "ఇప్పుడు లైవ్",
  goLive: "లైవ్ వెళ్లండి",
  liveBadge: "లైవ్",
  liveEndedBadge: "ముగిసింది",
  noOneLive: "ఇప్పుడు ఎవరూ లైవ్ లేరు",
  popularLive: "జనాదరణ పొందిన లైవ్",
  completedLive: "పూర్తైన లైవ్",
  noLiveStreamsYet: "ఇంకా లైవ్ స్ట్రీమ్‌లు లేవు",
  noLiveStreamsSub: "క్రియేటర్లు లైవ్ అయినప్పుడు ఇక్కడ కనిపిస్తారు.",
  noCompletedLiveYet: "ఇంకా పూర్తైన లైవ్ స్ట్రీమ్‌లు లేవు",
  noCompletedLiveSub: "లైవ్ ముగిసిన తర్వాత గత స్ట్రీమ్‌లు ఇక్కడ కనిపిస్తాయి.",
  liveCompletedLabel: "పూర్తయింది",
  noCompletedRecording: "ఈ లైవ్ రికార్డింగ్ సేవ్ కాలేదు.",
  startLive: "లైవ్ ప్రారంభించండి",
  publicAccount: "పబ్లిక్ ఖాతా",
  messageBtn: "సందేశం",
  tryAgainMoment: "కాసేపటి తర్వాత మళ్లీ ప్రయత్నించండి.",
  viewProfilePhoto: "ప్రొఫైల్ ఫోటో చూడండి",
  cannotOpenChat: "ఈ వినియోగదారుకు చాట్ ఇంకా తెరవలేదు.",
  createModePost: "పోస్ట్",
  createModeStory: "స్టోరీ",
  createModeReel: "రీల్",
  createModeLive: "లైవ్",
  filterNormal: "సాధారణ",
  filterWarm: "వెచ్చని",
  filterCool: "చల్లని",
  filterBw: "నలుపు-తెలుపు",
  filterVivid: "ప్రకాశవంతం",
  filterSunset: "సూర్యాస్తమయం",
  filterNoir: "నోయిర్",
  createPreviewReel: "రీల్",
  createPreviewPost: "కొత్త పోస్ట్",
  createPreviewStory: "స్టోరీ",
  createPreviewTitle: "సృష్టించు",
  tagPeople: "వ్యక్తులను ట్యాగ్ చేయండి",
  addLocation: "స్థానం జోడించండి",
  locationPrefix: "స్థానం: {{place}}",
  addAudio: "ఆడియో జోడించండి",
  audioPrefix: "ఆడియో: {{title}}",
  audience: "ప్రేక్షకులు",
  audienceSoon: "ప్రేక్షక నియంత్రణలు త్వరలో వస్తాయి.",
  scheduleLiveTitle: "లైవ్ షెడ్యూల్",
  scheduleLiveBody: "షెడ్యూలింగ్ తదుపరి అప్‌డేట్‌లో వస్తుంది.",
  shareBtn: "షేర్",
  nextBtn: "తదుపరి",
  writeReelCaptionPh: "రీల్ క్యాప్షన్ రాయండి...",
  writeCaptionPh: "క్యాప్షన్ రాయండి...",
  typeTextPlaceholder: "టెక్స్ట్ టైప్ చేయండి",
  recents: "ఇటీవలి",
  unknownArtist: "తెలియని కళాకారుడు",
  unknownTitle: "తెలియదు",
  createErrSelectPhoto: "కనీసం ఒక ఫోటో ఎంచుకోండి.",
  createErrCarouselPhotos: "కరోసెల్‌లో ఫోటోలు మాత్రమే. వీడియో పోస్ట్ కోసం ఒక వీడియో ఎంచుకోండి.",
  createErrPostPhotosOnly: "పోస్ట్ గ్రిడ్‌లో ఫోటోలు మాత్రమే. వీడియోకు రీల్ ఎంచుకోండి.",
  createErrCameraPerm: "కెమెరా అనుమతి అవసరం.",
  createErrReelVideoOnly: "రీల్‌లకు వీడియో మాత్రమే. వీడియో ఎంచుకోండి లేదా రికార్డ్ చేయండి.",
  createErrCapturePhoto: "ఫోటో క్యాప్చర్ కాలేదు.",
  createErrReelVideoOnlyShort: "రీల్‌లకు వీడియో మాత్రమే.",
  createErrMediaPerm: "మీడియా లైబ్రరీ అనుమతి అవసరం.",
  createErrChooseOption: "కొనసాగడానికి ఒక ఎంపిక ఎంచుకోండి.",
  createErrStoryMedia: "స్టోరీ మీడియా రికార్డ్ లేదా అప్‌లోడ్ చేయండి.",
  createErrCaptionRequired: "క్యాప్షన్ అవసరం.",
  createErrReelMedia: "రీల్ వీడియో రికార్డ్ లేదా అప్‌లోడ్ చేయండి.",
  createErrPostMedia: "పోస్ట్ కోసం మీడియా జోడించండి.",
  createErrReelSingleVideo: "రీల్‌లో ఒకే వీడియో ఉండాలి.",
  createErrUploadReel: "ఒక వీడియో రీల్ అప్‌లోడ్ చేయండి.",
  createErrMixedMedia: "ఒక వీడియో లేదా అనేక ఫోటోలు — రెండూ కాదు.",
  createErrOneVideo: "పోస్ట్‌కు ఒకే వీడియో.",
  createErrUploadImages: "చిత్రాలు అప్‌లోడ్ కాలేదు.",
  createErrPublish: "వీడియో ప్రచురించలేకపోయాము.",
  createErrAudioPreview: "ఆడియో ప్రివ్యూ కాలేదు.",
  createErrAudioFetch: "పాటలు లోడ్ కాలేదు. ఇంటర్నెట్ తనిఖీ చేయండి.",
  createToolAudio: "ఆడియో",
  createToolText: "టెక్స్ట్",
  createToolOverlay: "ఓవర్లే",
  createToolFilter: "ఫిల్టర్",
  createToolEdit: "సవరణ",
  openGallery: "ఫోటో గ్యాలరీ తెరవండి",
  videoSizeLimit: "వీడియో {{size}}MB. {{max}}MB కంటే తక్కువ ఎంచుకోండి.",
  languageNoteTitle: "భాష గురించి",
  languageNoteBody:
    "బటన్లు, మెనూలు, సందేశాలు మీ భాషలో మారుతాయి. మీరు రాసిన పోస్ట్‌లు మీరు రాసినట్లుగానే ఉంటాయి — మా నిఘంటువులో ఉన్న పంట పదాలు మాత్రమే మారుతాయి.",
  back: "వెనక్కి",
  continue: "కొనసాగించండి",
  roleSelectionTitle: "మీరు క్రాప్‌వైబ్‌ను ఎలా ఉపయోగిస్తారు?",
  roleSelectionSub: "ఒకటి ఎంచుకోండి — మీరు ఎప్పుడైనా ఇతర ప్రాంతాలను అన్వేషించవచ్చు.",
  roleBuyerTitle: "కొనుగోలుదారు",
  roleBuyerDesc: "ఉత్పత్తులు, మెషినరీ మరియు సేవలు కొనండి",
  roleSellerTitle: "విక్రేత",
  roleSellerDesc: "మీ పొలం నుండి జాబితా చేసి ఆర్డర్లు నిర్వహించండి",
  roleExpertTitle: "నిపుణుడు",
  roleExpertDesc: "కోర్సులు బోధించండి మరియు సమాజానికి సలహా ఇవ్వండి",
  personalInfoTitle: "మీ గురించి",
  personalInfoSubtitle: "క్రాప్‌వైబ్‌ను వ్యక్తిగతీకరించడానికి మేము దీన్ని ఉపయోగిస్తాము. ప్రొఫైల్‌లో ఎప్పుడైనా మార్చవచ్చు.",
  personalInfoPrimaryLabel: "ఖాతా సృష్టించండి",
  fullNameLabel: "పూర్తి పేరు",
  fullNamePlaceholder: "మీ పేరు",
  emailLabel: "ఇమెయిల్",
  emailPlaceholder: "you@example.com",
  dobLabel: "పుట్టిన తేదీ",
  dobPlaceholder: "YYYY-MM-DD (ఐచ్ఛికం)",
  languageLocationTitle: "భాష మరియు స్థానం",
  languageLocationSub: "ప్రాంతీయ కంటెంట్ కోసం ఐచ్ఛిక సత్వరమార్గాలు",
  preferredLanguageLabel: "ఇష్టమైన భాష",
  preferredLanguagePlaceholder: "ఉదా. English, Telugu, Hindi",
  districtOrCityPlaceholder: "జిల్లా లేదా నగరం",
  addLanguageLocation: "భాష మరియు స్థానం జోడించండి",
  otpTitle: "6 అంకెల కోడ్",
  otpSubtitle: "{{phone}}కు పంపిన ధృవీకరణ కోడ్‌ను నమోదు చేయండి",
  verifying: "ధృవీకరిస్తోంది...",
  verifyContinue: "ధృవీకరించి కొనసాగించండి",
  invalidOtp: "చెల్లని OTP. దయచేసి మళ్లీ ప్రయత్నించండి.",
  resendCode: "కోడ్ మళ్లీ పంపాలా?",
  resend: "మళ్లీ పంపండి",
  sending: "పంపుతోంది...",
  failedResendOtp: "OTP మళ్లీ పంపడం విఫలమైంది.",
  buyerInterestsTitle: "మీ ఆసక్తులు",
  buyerInterestsSubtitle: "మీరు సాధారణంగా ఏమి కొనుగోలు చేస్తారు? జాబితాలు మరియు చిట్కాలను క్రమబద్ధీకరించడానికి సహాయపడుతుంది.",
  interestsLabel: "పంటలు, వర్గాలు లేదా లక్ష్యాలు",
  interestsPlaceholder: "ఉదా. సేంద్రీయ కూరగాయలు, డ్రిప్ సాగు, ట్రాక్టర్ భాగాలు",
  buyerDeliveryTitle: "డెలివరీ చిరునామా",
  buyerDeliverySubtitle: "మార్కెట్‌ప్లేస్ ఆర్డర్లకు డిఫాల్ట్ డ్రాప్-ఆఫ్ (తర్వాత మరిన్ని జోడించవచ్చు).",
  addressLineLabel: "చిరునామా పంక్తి",
  addressLinePlaceholder: "గ్రామం, ల్యాండ్‌మార్క్, వీధి",
  districtLabel: "జిల్లా",
  pinCodeOptional: "పిన్ కోడ్ (ఐచ్ఛికం)",
  sellerFarmTitle: "పొలం వివరాలు",
  sellerFarmSubtitle: "మీరు ఎవరో కొనుగోలుదారులకు చెప్పండి. తర్వాత విక్రేత ప్రొఫైల్‌లో మెరుగుపరచవచ్చు.",
  farmNameLabel: "పొలం లేదా వ్యాపార పేరు",
  landAcresLabel: "సాగు భూమి (ఎకరాలు, ఐచ్ఛికం)",
  acresPlaceholder: "ఉదా. 12.5",
  primaryCropLabel: "ప్రధాన పంట లేదా ఉత్పత్తి",
  primaryCropPlaceholder: "ఉదా. బాస్మతి, పాల ఉత్పత్తులు, నర్సరీ",
  sellerKycTitle: "KYC ప్రాథమికాలు",
  sellerKycSubtitle: "డెమో దశ — వాస్తవంలో ID పత్ర OCR మరియు పేరు సరిపోలిక జరుగుతుంది.",
  legalNameLabel: "చట్టపరమైన పేరు (ID ప్రకారం)",
  idLast4Label: "ఆధార్ / ID సందర్భం చివరి 4 అంకెలు",
  sellerBankTitle: "బ్యాంక్ ఖాతా",
  sellerBankSubtitle: "అమ్మిన జాబితాల చెల్లింపులు ఇక్కడ జమ అవుతాయి. డెమో మాత్రమే — నిజమైన బ్యాంక్ వివరాలు నమోదు చేయవద్దు.",
  continueToSecurity: "భద్రతకు కొనసాగించండి",
  accountHolderLabel: "ఖాతాదారు పేరు",
  ifscLabel: "IFSC",
  accountNumberLabel: "ఖాతా నంబర్",
  expertDomainTitle: "మీ రంగం",
  expertDomainSubtitle: "మీరు ఏ అంశాలు లేదా పంటలపై సలహా ఇస్తారు? మీ నిపుణుల ప్రొఫైల్‌లో చూపబడుతుంది.",
  specializationsLabel: "ప్రత్యేకతలు",
  specializationsPlaceholder: "ఉదా. నేల ఆరోగ్యం, పాలిహౌస్ టమాటాలు, సేంద్రీయ ధృవీకరణ",
  yearsExperienceLabel: "అనుభవ సంవత్సరాలు (ఐచ్ఛికం)",
  yearsPlaceholder: "ఉదా. 8",
  expertCredentialsTitle: "అర్హతలు",
  expertCredentialsSubtitle: "డిగ్రీలు, సర్టిఫికేట్లు లేదా సంస్థ అనుబంధాలు నేర్చుకునేవారు తెలుసుకోవాలి.",
  professionalHeadlineLabel: "వృత్తిపరమైన శీర్షిక",
  professionalHeadlinePlaceholder: "ఉదా. వ్యవసాయ శాస్త్రవేత్త, KVK విస్తరణ అధికారి",
  certificationsOptionalLabel: "సర్టిఫికేట్లు (ఐచ్ఛికం)",
  certificationsPlaceholder: "B.Sc. Ag, సేంద్రీయ తనిఖీ సర్టిఫికేట్…",
  expertVerificationTitle: "నిపుణుల ధృవీకరణ",
  expertVerificationSubtitle:
    "బ్యాడ్జ్‌లు ప్రారంభమయ్యే ముందు మేము అర్హతలు మరియు నమూనా కంటెంట్‌ను సమీక్షిస్తాము. ఈ డెమో కొనసాగించినప్పుడు దశ పూర్తవుతుంది.",
  submitForReviewDemo: "సమీక్ష కోసం సమర్పించండి (డెమో)",
  whatHappensNext: "తర్వాత ఏమి జరుగుతుంది",
  expertVerificationBody:
    "వాస్తవంలో: చిన్న బోధన క్లిప్, సందర్భాలు మరియు ఐచ్ఛిక ID అప్‌లోడ్ చేయండి. మా బృందం సాధారణంగా 48 గంటలలో స్పందిస్తుంది.",
  securityVerificationTitle: "భద్రతా ధృవీకరణ",
  securityVerificationSubtitle:
    "ముఖ జీవనం, ID OCR మరియు తృతీయ-పక్ష KYC ఇక్కడ అనుసంధానమవుతుంది. విజయవంతమైన తనిఖీని అనుకరించడానికి క్రింద ట్యాప్ చేయండి.",
  completeVerificationDemo: "ధృవీకరణ పూర్తి చేయండి (డెమో)",
  checksTitle: "తనిఖీలు",
  checkFaceLiveness: "• ముఖ జీవనం (ఆంటీ-స్పూఫ్)",
  checkGovIdOcr: "• ప్రభుత్వ ID క్యాప్చర్ & OCR",
  checkVendorKyc: "• ఐచ్ఛిక విక్రేత KYC సరిపోలిక",
  buyerWalkthroughTitle: "త్వరిత చిట్కాలు",
  buyerWalkthroughSubtitle: "చిన్న పరిచయం — యాప్‌లో మేము మృదువైన గుర్తుచేతలతో గుర్తు చేస్తాము.",
  buyerWalkthroughNudge1: "ఫీడ్‌ను రిఫ్రెష్ చేయడానికి హోమ్‌పై కిందికి లాగండి.",
  buyerWalkthroughNudge2: "పంట కథ లేదా ప్రశ్న పోస్ట్ చేయడానికి + ట్యాబ్ ఉపయోగించండి.",
  buyerWalkthroughNudge3: "జాబితాలపై ధృవీకరించిన బ్యాడ్జ్‌లు విక్రేత ప్రాథమిక తనిఖీలు పూర్తి చేశాడని అర్థం.",
  firstTimeRoleTitle: "మీరు ఏమి చేస్తారు?",
  firstTimeRoleSubtitle: "యాప్‌లో మీ పాత్రను ఎంచుకోండి.",
  firstTimeRoleFarmer: "రైతు",
  firstTimeRoleFarmerSub: "నేను పంటలు పండించి నా ఉత్పత్తిని అమ్ముతాను.",
  firstTimeRoleConsumer: "వినియోగదారు",
  firstTimeRoleConsumerSub: "నేను ఇంటి మరియు వ్యాపార వినియోగం కోసం ఉత్పత్తులు కొనుగోలు చేస్తాను.",
  firstTimeRoleEducator: "బోధకుడు",
  firstTimeRoleEducatorSub: "నేను జ్ఞానం, సాధనాలు మరియు ఉత్తమ పద్ధతులను పంచుకుంటాను.",
  firstTimeRoleLogistics: "లాజిస్టిక్స్",
  firstTimeRoleLogisticsSub: "నేను వ్యవసాయ ఉత్పత్తులు మరియు సామగ్రిని రవాణా చేయడంలో సహాయపడతాను.",
  firstTimeCropsTitle: "మీరు ఏమి పండిస్తారు?",
  firstTimeCropsSubtitle: "సంబంధిత సిఫార్సులు పొందడానికి మీరు ఏ పంటలు పండిస్తారో చెప్పండి.",
  searchByCrop: "పంట ద్వారా శోధించండి",
  cropGroupGrains: "ధాన్యాలు & తృణధాన్యాలు",
  cropGroupVegetables: "కూరగాయలు",
  cropGroupFruits: "పండ్లు",
  cropGroupPulses: "పప్పులు",
  cropRice: "బియ్యం",
  cropWheat: "గోధుమ",
  cropJowar: "జొన్న",
  cropMaize: "మొక్కజొన్న",
  cropBajra: "సజ్జ",
  cropTomato: "టమాట",
  cropPotato: "ఆలుగడ్డ",
  cropOnion: "ఉల్లిపాయ",
  cropChilli: "మిరపకాయ",
  cropBrinjal: "వంకాయ",
  cropMango: "మామిడి",
  cropBanana: "అరటి",
  cropGrapes: "ద్రాక్ష",
  cropOrange: "నారింజ",
  cropApple: "ఆపిల్",
  cropTur: "కంది పప్పు",
  cropMoong: "పెసర పప్పు",
  cropUrad: "మినప పప్పు",
  cropMasoor: "మసూర్ పప్పు",
  cropChana: "శనగ",
  locationLabel: "స్థానం",
  idLast4Placeholder: "••••"
};
