/** Shared UI strings for screens not yet split into feature-specific bundles. */
export const COMMON_UI_EN = {
  loginRequired: "Login required",
  loginRequiredChat: "Please log in to send reels in chat.",
  loginRequiredSave: "Please log in to save reels.",
  loginRequiredReport: "Please log in to report posts.",
  loginRequiredDelete: "Please log in to delete posts.",
  chatUnavailableSend: "This user cannot receive messages yet.",
  sentTitle: "Sent",
  reelSentTo: "Reel sent to {{name}}.",
  shareFailedSystem: "Could not open system share.",
  noMediaTitle: "No media",
  noMediaStory: "This reel has no media to add as story.",
  addedTitle: "Added",
  addedToStory: "Reel added to your story.",
  copiedPostLink: "Post link copied to clipboard.",
  copyFailedTitle: "Copy failed",
  copyFailed: "Could not copy the link.",
  gotItHidePost: "Got it",
  gotItHidePostMsg: "We will hide this post and tune what we show you on this device.",
  thanksReport: "Thanks",
  thanksReportMsg: "We received your report and will review it.",
  reportFailed: "Report failed",
  notAllowedTitle: "Not allowed",
  notAllowedDeleteOwn: "You can only delete your own posts.",
  deleteFailed: "Delete failed",
  deletePostTitle: "Delete this post?",
  deletePostBody: "This cannot be undone.",
  deleteConfirm: "Delete",
  reportSpam: "Spam or misleading",
  reportHarassment: "Harassment or bullying",
  reportHate: "Hate speech or symbols",
  reportNudity: "Nudity or sexual content",
  reportViolence: "Violence or dangerous acts",
  reportScam: "Scam or fraud",
  reportIp: "Intellectual property violation",
  reportOther: "Something else",
  myFarm: "My Farm",
  unknownLocation: "Unknown",
  liveStream: "Live stream",
  liveNow: "Live now",
  goLive: "Go Live",
  liveBadge: "LIVE",
  noOneLive: "No one is live right now",
  popularLive: "Popular live",
  noLiveStreamsYet: "No live streams yet",
  noLiveStreamsSub: "When creators go live, they will show up here.",
  startLive: "Start a live",
  publicAccount: "Public account",
  messageBtn: "Message",
  tryAgainMoment: "Try again in a moment.",
  viewProfilePhoto: "View profile photo",
  cannotOpenChat: "Cannot open chat for this user yet.",
  createModePost: "POST",
  createModeStory: "STORY",
  createModeReel: "REEL",
  createModeLive: "LIVE",
  filterNormal: "Normal",
  filterWarm: "Warm",
  filterCool: "Cool",
  filterBw: "B&W",
  filterVivid: "Vivid",
  filterSunset: "Sunset",
  filterNoir: "Noir",
  createPreviewReel: "Reel",
  createPreviewPost: "New Post",
  createPreviewStory: "Story",
  createPreviewTitle: "Create",
  tagPeople: "Tag people",
  addLocation: "Add location",
  locationPrefix: "Location: {{place}}",
  addAudio: "Add audio",
  audioPrefix: "Audio: {{title}}",
  audience: "Audience",
  audienceSoon: "Audience controls coming soon.",
  scheduleLiveTitle: "Schedule live",
  scheduleLiveBody: "Scheduling will be available in a future update.",
  shareBtn: "Share",
  nextBtn: "Next",
  writeReelCaptionPh: "Write a reel caption...",
  writeCaptionPh: "Write a caption...",
  typeTextPlaceholder: "Type text",
  recents: "Recents",
  unknownArtist: "Unknown artist",
  unknownTitle: "Unknown",
  createErrSelectPhoto: "Please select at least one photo.",
  createErrCarouselPhotos: "Photo carousels can only include pictures. Pick one video for a video post.",
  createErrPostPhotosOnly: "Post grid supports photos only. Choose Reel for video.",
  createErrCameraPerm: "Camera permission is required.",
  createErrReelVideoOnly: "Reels support video only. Please select or record a video.",
  createErrCapturePhoto: "Could not capture photo.",
  createErrReelVideoOnlyShort: "Reels support video only.",
  createErrMediaPerm: "Media library permission is required.",
  createErrChooseOption: "Choose an option to continue.",
  createErrStoryMedia: "Please record or upload story media.",
  createErrCaptionRequired: "Caption is required.",
  createErrReelMedia: "Please record or upload a reel video.",
  createErrPostMedia: "Please add media for your post.",
  createErrReelSingleVideo: "A reel must be a single video.",
  createErrUploadReel: "Please upload one video reel.",
  createErrMixedMedia: "Use either one video or multiple photos — not both.",
  createErrOneVideo: "Only one video per post.",
  createErrUploadImages: "Could not upload images.",
  createErrPublish: "Failed to publish video.",
  createErrAudioPreview: "Could not preview this audio track.",
  createErrAudioFetch: "Could not fetch songs. Check internet and try again.",
  createToolAudio: "Audio",
  createToolText: "Text",
  createToolOverlay: "Overlay",
  createToolFilter: "Filter",
  createToolEdit: "Edit",
  openGallery: "Open photo gallery",
  videoSizeLimit: "Video is {{size}}MB. Please select a video under {{max}}MB.",
  languageNoteTitle: "About language",
  languageNoteBody:
    "Buttons, menus, and messages change with your language. Posts you write stay as you typed them unless they use common crop words from our dictionary.",
  back: "Back",
  continue: "Continue",
  roleSelectionTitle: "How will you use Cropvibe?",
  roleSelectionSub: "Pick one — you can explore other areas anytime.",
  roleBuyerTitle: "Buyer",
  roleBuyerDesc: "Shop produce, machinery, and services",
  roleSellerTitle: "Seller",
  roleSellerDesc: "List from your farm and manage orders",
  roleExpertTitle: "Expert",
  roleExpertDesc: "Teach courses and advise the community",
  personalInfoTitle: "About you",
  personalInfoSubtitle: "We use this to personalize Cropvibe. You can edit it anytime in profile.",
  personalInfoPrimaryLabel: "Create account",
  fullNameLabel: "Full name",
  fullNamePlaceholder: "Your name",
  emailLabel: "Email",
  emailPlaceholder: "you@example.com",
  dobLabel: "Date of birth",
  dobPlaceholder: "YYYY-MM-DD (optional)",
  languageLocationTitle: "Language & location",
  languageLocationSub: "Optional shortcuts for regional content",
  preferredLanguageLabel: "Preferred language",
  preferredLanguagePlaceholder: "e.g. English, Telugu",
  districtOrCityPlaceholder: "District or city",
  addLanguageLocation: "Add language & location",
  otpTitle: "6 Digit Code",
  otpSubtitle: "Please enter the verification code sent to {{phone}}",
  verifying: "Verifying...",
  verifyContinue: "Verify & Continue",
  invalidOtp: "Invalid OTP. Please try again.",
  resendCode: "Resend the code?",
  resend: "Resend",
  sending: "Sending...",
  failedResendOtp: "Failed to resend OTP.",
  buyerInterestsTitle: "Your interests",
  buyerInterestsSubtitle: "What do you usually shop for? Helps us rank listings and tips.",
  interestsLabel: "Crops, categories, or goals",
  interestsPlaceholder: "e.g. Organic vegetables, drip irrigation, tractor parts",
  buyerDeliveryTitle: "Delivery address",
  buyerDeliverySubtitle: "Default drop-off for marketplace orders (you can add more later).",
  addressLineLabel: "Address line",
  addressLinePlaceholder: "Village, landmark, street",
  districtLabel: "District",
  pinCodeOptional: "PIN code (optional)",
  sellerFarmTitle: "Farm details",
  sellerFarmSubtitle: "Tell buyers who you are. You can refine this on your seller profile later.",
  farmNameLabel: "Farm or business name",
  landAcresLabel: "Land under cultivation (acres, optional)",
  acresPlaceholder: "e.g. 12.5",
  primaryCropLabel: "Primary crop or product",
  primaryCropPlaceholder: "e.g. Basmati, dairy, nursery",
  sellerKycTitle: "KYC basics",
  sellerKycSubtitle: "Demo step — production would capture ID document OCR and match your name.",
  legalNameLabel: "Legal name (as on ID)",
  idLast4Label: "Last 4 digits of Aadhaar / ID reference",
  sellerBankTitle: "Bank account",
  sellerBankSubtitle: "Payouts for sold listings deposit here. Demo only — do not enter real banking data.",
  continueToSecurity: "Continue to security",
  accountHolderLabel: "Account holder name",
  ifscLabel: "IFSC",
  accountNumberLabel: "Account number",
  expertDomainTitle: "Your domain",
  expertDomainSubtitle: "What topics or crops do you advise on? Shown on your expert profile.",
  specializationsLabel: "Specializations",
  specializationsPlaceholder: "e.g. Soil health, polyhouse tomatoes, organic certification",
  yearsExperienceLabel: "Years of experience (optional)",
  yearsPlaceholder: "e.g. 8",
  expertCredentialsTitle: "Credentials",
  expertCredentialsSubtitle: "Degrees, certifications, or institutional affiliations learners should know about.",
  professionalHeadlineLabel: "Professional headline",
  professionalHeadlinePlaceholder: "e.g. Agronomist, KVK extension officer",
  certificationsOptionalLabel: "Certifications (optional)",
  certificationsPlaceholder: "B.Sc. Ag, Certificate in organic inspection…",
  expertVerificationTitle: "Expert verification",
  expertVerificationSubtitle:
    "We review credentials and sample content before badges go live. This demo marks the step complete when you continue.",
  submitForReviewDemo: "Submit for review (demo)",
  whatHappensNext: "What happens next",
  expertVerificationBody:
    "Production: upload a short teaching clip, references, and optional ID. Our team typically responds within 48 hours.",
  securityVerificationTitle: "Security verification",
  securityVerificationSubtitle:
    "Face liveness, ID OCR, and third-party KYC would plug in here. Tap below to simulate a successful check.",
  completeVerificationDemo: "Complete verification (demo)",
  checksTitle: "Checks",
  checkFaceLiveness: "• Face liveness (anti-spoof)",
  checkGovIdOcr: "• Government ID capture & OCR",
  checkVendorKyc: "• Optional vendor KYC match",
  buyerWalkthroughTitle: "Quick tips",
  buyerWalkthroughSubtitle: "A short walk-through — we'll remind you inside the app with gentle nudges.",
  buyerWalkthroughNudge1: "Pull down on Home to refresh your feed.",
  buyerWalkthroughNudge2: "Use the + tab to post a harvest story or question.",
  buyerWalkthroughNudge3: "Verified badges on listings mean the seller passed basic checks.",
  firstTimeRoleTitle: "What do you do?",
  firstTimeRoleSubtitle: "Select your role within the app.",
  firstTimeRoleFarmer: "Farmer",
  firstTimeRoleFarmerSub: "I cultivate crops and sell my produce.",
  firstTimeRoleConsumer: "Consumer",
  firstTimeRoleConsumerSub: "I buy produce for home and business use.",
  firstTimeRoleEducator: "Educator",
  firstTimeRoleEducatorSub: "I share knowledge, tools and best practices.",
  firstTimeRoleLogistics: "Logistics",
  firstTimeRoleLogisticsSub: "I help move farm produce and inputs.",
  firstTimeCropsTitle: "What do you grow?",
  firstTimeCropsSubtitle: "Tell us what crops you grow to receive relevant recommendations.",
  searchByCrop: "Search by crop",
  cropGroupGrains: "GRAINS & CEREALS",
  cropGroupVegetables: "VEGETABLES",
  cropGroupFruits: "FRUITS",
  cropGroupPulses: "PULSES",
  cropRice: "Rice",
  cropWheat: "Wheat",
  cropJowar: "Jowar",
  cropMaize: "Maize",
  cropBajra: "Bajra",
  cropTomato: "Tomato",
  cropPotato: "Potato",
  cropOnion: "Onion",
  cropChilli: "Chilli",
  cropBrinjal: "Brinjal",
  cropMango: "Mango",
  cropBanana: "Banana",
  cropGrapes: "Grapes",
  cropOrange: "Orange",
  cropApple: "Apple",
  cropTur: "Tur",
  cropMoong: "Moong",
  cropUrad: "Urad",
  cropMasoor: "Masoor",
  cropChana: "Chana",
  locationLabel: "Location",
  idLast4Placeholder: "••••"
} as const;

export const COMMON_UI_HI: typeof COMMON_UI_EN = {
  loginRequired: "लॉगिन आवश्यक",
  loginRequiredChat: "चैट में रील भेजने के लिए लॉगिन करें।",
  loginRequiredSave: "रील सेव करने के लिए लॉगिन करें।",
  loginRequiredReport: "पोस्ट रिपोर्ट करने के लिए लॉगिन करें।",
  loginRequiredDelete: "पोस्ट हटाने के लिए लॉगिन करें।",
  chatUnavailableSend: "यह उपयोगकर्ता अभी संदेश नहीं ले सकता।",
  sentTitle: "भेजा गया",
  reelSentTo: "रील {{name}} को भेजी गई।",
  shareFailedSystem: "सिस्टम शेयर नहीं खुल सका।",
  noMediaTitle: "कोई मीडिया नहीं",
  noMediaStory: "इस रील में स्टोरी के लिए मीडिया नहीं है।",
  addedTitle: "जोड़ा गया",
  addedToStory: "रील आपकी स्टोरी में जोड़ी गई।",
  copiedPostLink: "पोस्ट लिंक कॉपी हो गया।",
  copyFailedTitle: "कॉपी विफल",
  copyFailed: "लिंक कॉपी नहीं हो सका।",
  gotItHidePost: "ठीक है",
  gotItHidePostMsg: "हम इस पोस्ट को छुपाएंगे और इस डिवाइस पर आपके लिए फ़ीड ठीक करेंगे।",
  thanksReport: "धन्यवाद",
  thanksReportMsg: "आपकी रिपोर्ट मिली, हम जल्द समीक्षा करेंगे।",
  reportFailed: "रिपोर्ट विफल",
  notAllowedTitle: "अनुमति नहीं",
  notAllowedDeleteOwn: "आप केवल अपनी पोस्ट हटा सकते हैं।",
  deleteFailed: "हटाना विफल",
  deletePostTitle: "यह पोस्ट हटाएं?",
  deletePostBody: "यह वापस नहीं हो सकता।",
  deleteConfirm: "हटाएं",
  reportSpam: "स्पैम या भ्रामक",
  reportHarassment: "उत्पीड़न या धमकाना",
  reportHate: "नफरत भाषण या प्रतीक",
  reportNudity: "नग्नता या यौन सामग्री",
  reportViolence: "हिंसा या खतरनाक कृत्य",
  reportScam: "धोखा या फ्रॉड",
  reportIp: "बौद्धिक संपदा उल्लंघन",
  reportOther: "कुछ और",
  myFarm: "मेरा खेत",
  unknownLocation: "अज्ञात",
  liveStream: "लाइव स्ट्रीम",
  liveNow: "अभी लाइव",
  goLive: "लाइव जाएं",
  liveBadge: "लाइव",
  noOneLive: "अभी कोई लाइव नहीं",
  popularLive: "लोकप्रिय लाइव",
  noLiveStreamsYet: "अभी कोई लाइव स्ट्रीम नहीं",
  noLiveStreamsSub: "जब क्रिएटर लाइव होंगे, वे यहाँ दिखेंगे।",
  startLive: "लाइव शुरू करें",
  publicAccount: "सार्वजनिक खाता",
  messageBtn: "संदेश",
  tryAgainMoment: "थोड़ी देर बाद फिर कोशिश करें।",
  viewProfilePhoto: "प्रोफाइल फोटो देखें",
  cannotOpenChat: "इस उपयोगकर्ता के लिए चैट अभी नहीं खुल सकती।",
  createModePost: "पोस्ट",
  createModeStory: "स्टोरी",
  createModeReel: "रील",
  createModeLive: "लाइव",
  filterNormal: "सामान्य",
  filterWarm: "गर्म",
  filterCool: "ठंडा",
  filterBw: "काला-सफेद",
  filterVivid: "चमकीला",
  filterSunset: "सूर्यास्त",
  filterNoir: "नोयर",
  createPreviewReel: "रील",
  createPreviewPost: "नई पोस्ट",
  createPreviewStory: "स्टोरी",
  createPreviewTitle: "बनाएं",
  tagPeople: "लोगों को टैग करें",
  addLocation: "स्थान जोड़ें",
  locationPrefix: "स्थान: {{place}}",
  addAudio: "ऑडियो जोड़ें",
  audioPrefix: "ऑडियो: {{title}}",
  audience: "दर्शक",
  audienceSoon: "दर्शक नियंत्रण जल्द आएंगे।",
  scheduleLiveTitle: "लाइव शेड्यूल",
  scheduleLiveBody: "शेड्यूलिंग भविष्य के अपडेट में आएगी।",
  shareBtn: "शेयर",
  nextBtn: "आगे",
  writeReelCaptionPh: "रील कैप्शन लिखें...",
  writeCaptionPh: "कैप्शन लिखें...",
  typeTextPlaceholder: "टेक्स्ट लिखें",
  recents: "हाल के",
  unknownArtist: "अज्ञात कलाकार",
  unknownTitle: "अज्ञात",
  createErrSelectPhoto: "कम से कम एक फोटो चुनें।",
  createErrCarouselPhotos: "कैरोसेल में केवल फोटो। वीडियो पोस्ट के लिए एक वीडियो चुनें।",
  createErrPostPhotosOnly: "पोस्ट ग्रिड में केवल फोटो। वीडियो के लिए रील चुनें।",
  createErrCameraPerm: "कैमरा अनुमति आवश्यक है।",
  createErrReelVideoOnly: "रील केवल वीडियो। वीडियो चुनें या रिकॉर्ड करें।",
  createErrCapturePhoto: "फोटो कैप्चर नहीं हो सका।",
  createErrReelVideoOnlyShort: "रील केवल वीडियो।",
  createErrMediaPerm: "मीडिया लाइब्रेरी अनुमति आवश्यक है।",
  createErrChooseOption: "जारी रखने के लिए एक विकल्प चुनें।",
  createErrStoryMedia: "स्टोरी मीडिया रिकॉर्ड या अपलोड करें।",
  createErrCaptionRequired: "कैप्शन आवश्यक है।",
  createErrReelMedia: "रील वीडियो रिकॉर्ड या अपलोड करें।",
  createErrPostMedia: "पोस्ट के लिए मीडिया जोड़ें।",
  createErrReelSingleVideo: "रील में एक ही वीडियो होना चाहिए।",
  createErrUploadReel: "एक वीडियो रील अपलोड करें।",
  createErrMixedMedia: "एक वीडियो या कई फोटो — दोनों नहीं।",
  createErrOneVideo: "प्रति पोस्ट एक वीडियो।",
  createErrUploadImages: "छवियां अपलोड नहीं हो सकीं।",
  createErrPublish: "वीडियो प्रकाशित नहीं हो सका।",
  createErrAudioPreview: "ऑडियो पूर्वावलोकन नहीं हो सका।",
  createErrAudioFetch: "गाने लोड नहीं हुए। इंटरनेट जांचें।",
  createToolAudio: "ऑडियो",
  createToolText: "टेक्स्ट",
  createToolOverlay: "ओवरले",
  createToolFilter: "फ़िल्टर",
  createToolEdit: "संपादन",
  openGallery: "फोटो गैलरी खोलें",
  videoSizeLimit: "वीडियो {{size}}MB है। {{max}}MB से कम चुनें।",
  languageNoteTitle: "भाषा के बारे में",
  languageNoteBody:
    "बटन, मेनू और संदेश आपकी भाषा में बदलते हैं। आपकी लिखी पोस्ट वैसी ही रहती हैं जब तक शब्द हमारे शब्दकोश में न हों।",
  back: "वापस",
  continue: "जारी रखें",
  roleSelectionTitle: "आप क्रॉपवाइब का उपयोग कैसे करेंगे?",
  roleSelectionSub: "एक विकल्प चुनें — आप कभी भी अन्य क्षेत्रों को देख सकते हैं।",
  roleBuyerTitle: "खरीदार",
  roleBuyerDesc: "उत्पाद, मशीनरी और सेवाएं खरीदें",
  roleSellerTitle: "विक्रेता",
  roleSellerDesc: "अपने खेत से सूची बनाएं और ऑर्डर प्रबंधित करें",
  roleExpertTitle: "विशेषज्ञ",
  roleExpertDesc: "कोर्स पढ़ाएं और समुदाय को सलाह दें",
  personalInfoTitle: "आपके बारे में",
  personalInfoSubtitle: "हम इससे क्रॉपवाइब को व्यक्तिगत बनाते हैं। आप इसे प्रोफाइल में कभी भी संपादित कर सकते हैं।",
  personalInfoPrimaryLabel: "खाता बनाएं",
  fullNameLabel: "पूरा नाम",
  fullNamePlaceholder: "आपका नाम",
  emailLabel: "ईमेल",
  emailPlaceholder: "you@example.com",
  dobLabel: "जन्म तिथि",
  dobPlaceholder: "YYYY-MM-DD (वैकल्पिक)",
  languageLocationTitle: "भाषा और स्थान",
  languageLocationSub: "क्षेत्रीय सामग्री के लिए वैकल्पिक शॉर्टकट",
  preferredLanguageLabel: "पसंदीदा भाषा",
  preferredLanguagePlaceholder: "जैसे अंग्रेज़ी, हिंदी, तेलुगु",
  districtOrCityPlaceholder: "जिला या शहर",
  addLanguageLocation: "भाषा और स्थान जोड़ें",
  otpTitle: "6 अंकों का कोड",
  otpSubtitle: "कृपया {{phone}} पर भेजा गया सत्यापन कोड दर्ज करें",
  verifying: "सत्यापित हो रहा है...",
  verifyContinue: "सत्यापित करें और जारी रखें",
  invalidOtp: "अमान्य OTP। कृपया पुनः प्रयास करें।",
  resendCode: "कोड दोबारा भेजें?",
  resend: "पुनः भेजें",
  sending: "भेजा जा रहा है...",
  failedResendOtp: "OTP पुनः भेजने में विफल।",
  buyerInterestsTitle: "आपकी रुचियां",
  buyerInterestsSubtitle: "आप आमतौर पर क्या खरीदते हैं? इससे सूचियों और सुझावों को क्रमबद्ध करने में मदद मिलती है।",
  interestsLabel: "फसलें, श्रेणियां या लक्ष्य",
  interestsPlaceholder: "जैसे जैविक सब्जियां, ड्रिप सिंचाई, ट्रैक्टर पुर्जे",
  buyerDeliveryTitle: "डिलीवरी पता",
  buyerDeliverySubtitle: "मार्केटप्लेस ऑर्डर के लिए डिफ़ॉल्ट ड्रॉप-ऑफ (बाद में और जोड़ सकते हैं)।",
  addressLineLabel: "पता पंक्ति",
  addressLinePlaceholder: "गांव, लैंडमार्क, सड़क",
  districtLabel: "जिला",
  pinCodeOptional: "पिन कोड (वैकल्पिक)",
  sellerFarmTitle: "खेत का विवरण",
  sellerFarmSubtitle: "खरीदारों को बताएं आप कौन हैं। बाद में विक्रेता प्रोफाइल में इसे और बेहतर कर सकते हैं।",
  farmNameLabel: "खेत या व्यवसाय का नाम",
  landAcresLabel: "खेती योग्य भूमि (एकड़, वैकल्पिक)",
  acresPlaceholder: "जैसे 12.5",
  primaryCropLabel: "मुख्य फसल या उत्पाद",
  primaryCropPlaceholder: "जैसे बासमती, डेयरी, नर्सरी",
  sellerKycTitle: "KYC मूल बातें",
  sellerKycSubtitle: "डेमो चरण — वास्तविक में ID दस्तावेज़ OCR और नाम मिलान होगा।",
  legalNameLabel: "कानूनी नाम (ID के अनुसार)",
  idLast4Label: "आधार / ID संदर्भ के अंतिम 4 अंक",
  sellerBankTitle: "बैंक खाता",
  sellerBankSubtitle: "बिकी सूचियों का भुगतान यहाँ जमा होगा। केवल डेमो — वास्तविक बैंक विवरण न दर्ज करें।",
  continueToSecurity: "सुरक्षा पर जारी रखें",
  accountHolderLabel: "खाताधारक का नाम",
  ifscLabel: "IFSC",
  accountNumberLabel: "खाता संख्या",
  expertDomainTitle: "आपका क्षेत्र",
  expertDomainSubtitle: "आप किन विषयों या फसलों पर सलाह देते हैं? यह आपकी विशेषज्ञ प्रोफाइल पर दिखेगा।",
  specializationsLabel: "विशेषज्ञता",
  specializationsPlaceholder: "जैसे मृदा स्वास्थ्य, पॉलीहाउस टमाटर, जैविक प्रमाणन",
  yearsExperienceLabel: "अनुभव के वर्ष (वैकल्पिक)",
  yearsPlaceholder: "जैसे 8",
  expertCredentialsTitle: "योग्यता",
  expertCredentialsSubtitle: "डिग्री, प्रमाणपत्र या संस्थागत संबद्धता जो शिक्षार्थियों को जाननी चाहिए।",
  professionalHeadlineLabel: "पेशेवर शीर्षक",
  professionalHeadlinePlaceholder: "जैसे कृषि वैज्ञानिक, KVK विस्तार अधिकारी",
  certificationsOptionalLabel: "प्रमाणपत्र (वैकल्पिक)",
  certificationsPlaceholder: "B.Sc. Ag, जैविक निरीक्षण प्रमाणपत्र…",
  expertVerificationTitle: "विशेषज्ञ सत्यापन",
  expertVerificationSubtitle:
    "बैज लाइव होने से पहले हम योग्यता और नमूना सामग्री की समीक्षा करते हैं। यह डेमो जारी रखने पर चरण पूर्ण करता है।",
  submitForReviewDemo: "समीक्षा के लिए भेजें (डेमो)",
  whatHappensNext: "आगे क्या होगा",
  expertVerificationBody:
    "वास्तविक में: संक्षिप्त शिक्षण क्लिप, संदर्भ और वैकल्पिक ID अपलोड करें। हमारी टीम आमतौर पर 48 घंटों में जवाब देती है।",
  securityVerificationTitle: "सुरक्षा सत्यापन",
  securityVerificationSubtitle:
    "चेहरे की जीवंतता, ID OCR और तृतीय-पक्ष KYC यहाँ जुड़ेगा। सफल जांच का अनुकरण करने के लिए नीचे टैप करें।",
  completeVerificationDemo: "सत्यापन पूर्ण करें (डेमो)",
  checksTitle: "जांच",
  checkFaceLiveness: "• चेहरे की जीवंतता (एंटी-स्पूफ)",
  checkGovIdOcr: "• सरकारी ID कैप्चर और OCR",
  checkVendorKyc: "• वैकल्पिक विक्रेता KYC मिलान",
  buyerWalkthroughTitle: "त्वरित सुझाव",
  buyerWalkthroughSubtitle: "एक संक्षिप्त परिचय — ऐप के अंदर हम आपको कोमल अनुस्मारक देंगे।",
  buyerWalkthroughNudge1: "फ़ीड रिफ्रेश करने के लिए होम पर नीचे खींचें।",
  buyerWalkthroughNudge2: "फसल की कहानी या प्रश्न पोस्ट करने के लिए + टैब का उपयोग करें।",
  buyerWalkthroughNudge3: "सूचियों पर सत्यापित बैज का मतलब है कि विक्रेता ने बुनियादी जांच पास की है।",
  firstTimeRoleTitle: "आप क्या करते हैं?",
  firstTimeRoleSubtitle: "ऐप में अपनी भूमिका चुनें।",
  firstTimeRoleFarmer: "किसान",
  firstTimeRoleFarmerSub: "मैं फसलें उगाता/उगाती हूँ और अपनी उपज बेचता/बेचती हूँ।",
  firstTimeRoleConsumer: "उपभोक्ता",
  firstTimeRoleConsumerSub: "मैं घर और व्यवसाय के लिए उपज खरीदता/खरीदती हूँ।",
  firstTimeRoleEducator: "शिक्षक",
  firstTimeRoleEducatorSub: "मैं ज्ञान, उपकरण और सर्वोत्तम प्रथाएं साझा करता/करती हूँ।",
  firstTimeRoleLogistics: "लॉजिस्टिक्स",
  firstTimeRoleLogisticsSub: "मैं कृषि उपज और सामग्री की ढुलाई में मदद करता/करती हूँ।",
  firstTimeCropsTitle: "आप क्या उगाते हैं?",
  firstTimeCropsSubtitle: "प्रासंगिक सुझाव पाने के लिए बताएं आप कौन-सी फसलें उगाते हैं।",
  searchByCrop: "फसल से खोजें",
  cropGroupGrains: "अनाज और दलहन",
  cropGroupVegetables: "सब्जियां",
  cropGroupFruits: "फल",
  cropGroupPulses: "दालें",
  cropRice: "चावल",
  cropWheat: "गेहूं",
  cropJowar: "ज्वार",
  cropMaize: "मक्का",
  cropBajra: "बाजरा",
  cropTomato: "टमाटर",
  cropPotato: "आलू",
  cropOnion: "प्याज",
  cropChilli: "मिर्च",
  cropBrinjal: "बैंगन",
  cropMango: "आम",
  cropBanana: "केला",
  cropGrapes: "अंगूर",
  cropOrange: "संतरा",
  cropApple: "सेब",
  cropTur: "अरहर",
  cropMoong: "मूंग",
  cropUrad: "उड़द",
  cropMasoor: "मसूर",
  cropChana: "चना",
  locationLabel: "स्थान",
  idLast4Placeholder: "••••"
};

export const COMMON_UI_TE: typeof COMMON_UI_EN = {
  loginRequired: "లాగిన్ అవసరం",
  loginRequiredChat: "చాట్‌లో రీల్ పంపడానికి లాగిన్ అవ్వండి.",
  loginRequiredSave: "రీల్స్ సేవ్ చేయడానికి లాగిన్ అవ్వండి.",
  loginRequiredReport: "పోస్ట్ రిపోర్ట్ చేయడానికి లాగిన్ అవ్వండి.",
  loginRequiredDelete: "పోస్ట్ తొలగించడానికి లాగిన్ అవ్వండి.",
  chatUnavailableSend: "ఈ వినియోగదారు ఇంకా సందేశాలు స్వీకరించలేరు.",
  sentTitle: "పంపబడింది",
  reelSentTo: "రీల్ {{name}} కు పంపబడింది.",
  shareFailedSystem: "సిస్టమ్ షేర్ తెరవలేకపోయింది.",
  noMediaTitle: "మీడియా లేదు",
  noMediaStory: "ఈ రీల్‌లో స్టోరీకి మీడియా లేదు.",
  addedTitle: "జోడించబడింది",
  addedToStory: "రీల్ మీ స్టోరీకి జోడించబడింది.",
  copiedPostLink: "పోస్ట్ లింక్ కాపీ అయింది.",
  copyFailedTitle: "కాపీ విఫలమైంది",
  copyFailed: "లింక్ కాపీ కాలేదు.",
  gotItHidePost: "సరే",
  gotItHidePostMsg: "ఈ పోస్ట్ దాచబడుతుంది; ఈ పరికరంలో మీ ఫీడ్ మెరుగుపరచబడుతుంది.",
  thanksReport: "ధన్యవాదాలు",
  thanksReportMsg: "మీ రిపోర్ట్ అందింది, త్వరలో సమీక్షిస్తాము.",
  reportFailed: "రిపోర్ట్ విఫలమైంది",
  notAllowedTitle: "అనుమతి లేదు",
  notAllowedDeleteOwn: "మీరు మీ పోస్ట్‌లనే తొలగించవచ్చు.",
  deleteFailed: "తొలగింపు విఫలమైంది",
  deletePostTitle: "ఈ పోస్ట్ తొలగించాలా?",
  deletePostBody: "దీన్ని రద్దు చేయలేము.",
  deleteConfirm: "తొలగించు",
  reportSpam: "స్పామ్ లేదా మోసపూరిత",
  reportHarassment: "వేధింపు లేదా బుల్లింగ్",
  reportHate: "ద్వేష ప్రసంగం లేదా చిహ్నాలు",
  reportNudity: "నగ్నత్వం లేదా లైంగిక కంటెంట్",
  reportViolence: "హింస లేదా ప్రమాదకర చర్యలు",
  reportScam: "మోసం లేదా వంచన",
  reportIp: "బౌద్ధిక ఆస్తి ఉల్లంఘన",
  reportOther: "ఇతరతరం",
  myFarm: "నా పొలం",
  unknownLocation: "తెలియదు",
  liveStream: "లైవ్ స్ట్రీమ్",
  liveNow: "ఇప్పుడు లైవ్",
  goLive: "లైవ్ వెళ్లండి",
  liveBadge: "లైవ్",
  noOneLive: "ఇప్పుడు ఎవరూ లైవ్ లేరు",
  popularLive: "జనాదరణ పొందిన లైవ్",
  noLiveStreamsYet: "ఇంకా లైవ్ స్ట్రీమ్‌లు లేవు",
  noLiveStreamsSub: "క్రియేటర్లు లైవ్ అయినప్పుడు ఇక్కడ కనిపిస్తారు.",
  startLive: "లైవ్ ప్రారంభించండి",
  publicAccount: "పబ్లిక్ ఖాతా",
  messageBtn: "సందేశం",
  tryAgainMoment: "కాసేపటి తర్వాత మళ్లీ ప్రయత్నించండి.",
  viewProfilePhoto: "ప్రొఫైల్ ఫోటో చూడండి",
  cannotOpenChat: "ఈ వినియోగదారుకు చాట్ ఇంకా తెరవలేదు.",
  createModePost: "పోస్ట్",
  createModeStory: "స్టోరీ",
  createModeReel: "రీల్",
  createModeLive: "లైవ్",
  filterNormal: "సాధారణ",
  filterWarm: "వెచ్చని",
  filterCool: "చల్లని",
  filterBw: "నలుపు-తెలుపు",
  filterVivid: "ప్రకాశవంతం",
  filterSunset: "సూర్యాస్తమయం",
  filterNoir: "నోయిర్",
  createPreviewReel: "రీల్",
  createPreviewPost: "కొత్త పోస్ట్",
  createPreviewStory: "స్టోరీ",
  createPreviewTitle: "సృష్టించు",
  tagPeople: "వ్యక్తులను ట్యాగ్ చేయండి",
  addLocation: "స్థానం జోడించండి",
  locationPrefix: "స్థానం: {{place}}",
  addAudio: "ఆడియో జోడించండి",
  audioPrefix: "ఆడియో: {{title}}",
  audience: "ప్రేక్షకులు",
  audienceSoon: "ప్రేక్షక నియంత్రణలు త్వరలో వస్తాయి.",
  scheduleLiveTitle: "లైవ్ షెడ్యూల్",
  scheduleLiveBody: "షెడ్యూలింగ్ తదుపరి అప్‌డేట్‌లో వస్తుంది.",
  shareBtn: "షేర్",
  nextBtn: "తదుపరి",
  writeReelCaptionPh: "రీల్ క్యాప్షన్ రాయండి...",
  writeCaptionPh: "క్యాప్షన్ రాయండి...",
  typeTextPlaceholder: "టెక్స్ట్ టైప్ చేయండి",
  recents: "ఇటీవలి",
  unknownArtist: "తెలియని కళాకారుడు",
  unknownTitle: "తెలియదు",
  createErrSelectPhoto: "కనీసం ఒక ఫోటో ఎంచుకోండి.",
  createErrCarouselPhotos: "కరోసెల్‌లో ఫోటోలు మాత్రమే. వీడియో పోస్ట్ కోసం ఒక వీడియో ఎంచుకోండి.",
  createErrPostPhotosOnly: "పోస్ట్ గ్రిడ్‌లో ఫోటోలు మాత్రమే. వీడియోకు రీల్ ఎంచుకోండి.",
  createErrCameraPerm: "కెమెరా అనుమతి అవసరం.",
  createErrReelVideoOnly: "రీల్‌లకు వీడియో మాత్రమే. వీడియో ఎంచుకోండి లేదా రికార్డ్ చేయండి.",
  createErrCapturePhoto: "ఫోటో క్యాప్చర్ కాలేదు.",
  createErrReelVideoOnlyShort: "రీల్‌లకు వీడియో మాత్రమే.",
  createErrMediaPerm: "మీడియా లైబ్రరీ అనుమతి అవసరం.",
  createErrChooseOption: "కొనసాగడానికి ఒక ఎంపిక ఎంచుకోండి.",
  createErrStoryMedia: "స్టోరీ మీడియా రికార్డ్ లేదా అప్‌లోడ్ చేయండి.",
  createErrCaptionRequired: "క్యాప్షన్ అవసరం.",
  createErrReelMedia: "రీల్ వీడియో రికార్డ్ లేదా అప్‌లోడ్ చేయండి.",
  createErrPostMedia: "పోస్ట్ కోసం మీడియా జోడించండి.",
  createErrReelSingleVideo: "రీల్‌లో ఒకే వీడియో ఉండాలి.",
  createErrUploadReel: "ఒక వీడియో రీల్ అప్‌లోడ్ చేయండి.",
  createErrMixedMedia: "ఒక వీడియో లేదా అనేక ఫోటోలు — రెండూ కాదు.",
  createErrOneVideo: "పోస్ట్‌కు ఒకే వీడియో.",
  createErrUploadImages: "చిత్రాలు అప్‌లోడ్ కాలేదు.",
  createErrPublish: "వీడియో ప్రచురించలేకపోయాము.",
  createErrAudioPreview: "ఆడియో ప్రివ్యూ కాలేదు.",
  createErrAudioFetch: "పాటలు లోడ్ కాలేదు. ఇంటర్నెట్ తనిఖీ చేయండి.",
  createToolAudio: "ఆడియో",
  createToolText: "టెక్స్ట్",
  createToolOverlay: "ఓవర్లే",
  createToolFilter: "ఫిల్టర్",
  createToolEdit: "సవరణ",
  openGallery: "ఫోటో గ్యాలరీ తెరవండి",
  videoSizeLimit: "వీడియో {{size}}MB. {{max}}MB కంటే తక్కువ ఎంచుకోండి.",
  languageNoteTitle: "భాష గురించి",
  languageNoteBody:
    "బటన్లు, మెనూలు, సందేశాలు మీ భాషలో మారుతాయి. మీరు రాసిన పోస్ట్‌లు మీరు రాసినట్లుగానే ఉంటాయి — మా నిఘంటువులో ఉన్న పంట పదాలు మాత్రమే మారుతాయి.",
  back: "వెనక్కి",
  continue: "కొనసాగించండి",
  roleSelectionTitle: "మీరు క్రాప్‌వైబ్‌ను ఎలా ఉపయోగిస్తారు?",
  roleSelectionSub: "ఒకటి ఎంచుకోండి — మీరు ఎప్పుడైనా ఇతర ప్రాంతాలను అన్వేషించవచ్చు.",
  roleBuyerTitle: "కొనుగోలుదారు",
  roleBuyerDesc: "ఉత్పత్తులు, మెషినరీ మరియు సేవలు కొనండి",
  roleSellerTitle: "విక్రేత",
  roleSellerDesc: "మీ పొలం నుండి జాబితా చేసి ఆర్డర్లు నిర్వహించండి",
  roleExpertTitle: "నిపుణుడు",
  roleExpertDesc: "కోర్సులు బోధించండి మరియు సమాజానికి సలహా ఇవ్వండి",
  personalInfoTitle: "మీ గురించి",
  personalInfoSubtitle: "క్రాప్‌వైబ్‌ను వ్యక్తిగతీకరించడానికి మేము దీన్ని ఉపయోగిస్తాము. ప్రొఫైల్‌లో ఎప్పుడైనా మార్చవచ్చు.",
  personalInfoPrimaryLabel: "ఖాతా సృష్టించండి",
  fullNameLabel: "పూర్తి పేరు",
  fullNamePlaceholder: "మీ పేరు",
  emailLabel: "ఇమెయిల్",
  emailPlaceholder: "you@example.com",
  dobLabel: "పుట్టిన తేదీ",
  dobPlaceholder: "YYYY-MM-DD (ఐచ్ఛికం)",
  languageLocationTitle: "భాష మరియు స్థానం",
  languageLocationSub: "ప్రాంతీయ కంటెంట్ కోసం ఐచ్ఛిక సత్వరమార్గాలు",
  preferredLanguageLabel: "ఇష్టమైన భాష",
  preferredLanguagePlaceholder: "ఉదా. English, Telugu, Hindi",
  districtOrCityPlaceholder: "జిల్లా లేదా నగరం",
  addLanguageLocation: "భాష మరియు స్థానం జోడించండి",
  otpTitle: "6 అంకెల కోడ్",
  otpSubtitle: "{{phone}}కు పంపిన ధృవీకరణ కోడ్‌ను నమోదు చేయండి",
  verifying: "ధృవీకరిస్తోంది...",
  verifyContinue: "ధృవీకరించి కొనసాగించండి",
  invalidOtp: "చెల్లని OTP. దయచేసి మళ్లీ ప్రయత్నించండి.",
  resendCode: "కోడ్ మళ్లీ పంపాలా?",
  resend: "మళ్లీ పంపండి",
  sending: "పంపుతోంది...",
  failedResendOtp: "OTP మళ్లీ పంపడం విఫలమైంది.",
  buyerInterestsTitle: "మీ ఆసక్తులు",
  buyerInterestsSubtitle: "మీరు సాధారణంగా ఏమి కొనుగోలు చేస్తారు? జాబితాలు మరియు చిట్కాలను క్రమబద్ధీకరించడానికి సహాయపడుతుంది.",
  interestsLabel: "పంటలు, వర్గాలు లేదా లక్ష్యాలు",
  interestsPlaceholder: "ఉదా. సేంద్రీయ కూరగాయలు, డ్రిప్ సాగు, ట్రాక్టర్ భాగాలు",
  buyerDeliveryTitle: "డెలివరీ చిరునామా",
  buyerDeliverySubtitle: "మార్కెట్‌ప్లేస్ ఆర్డర్లకు డిఫాల్ట్ డ్రాప్-ఆఫ్ (తర్వాత మరిన్ని జోడించవచ్చు).",
  addressLineLabel: "చిరునామా పంక్తి",
  addressLinePlaceholder: "గ్రామం, ల్యాండ్‌మార్క్, వీధి",
  districtLabel: "జిల్లా",
  pinCodeOptional: "పిన్ కోడ్ (ఐచ్ఛికం)",
  sellerFarmTitle: "పొలం వివరాలు",
  sellerFarmSubtitle: "మీరు ఎవరో కొనుగోలుదారులకు చెప్పండి. తర్వాత విక్రేత ప్రొఫైల్‌లో మెరుగుపరచవచ్చు.",
  farmNameLabel: "పొలం లేదా వ్యాపార పేరు",
  landAcresLabel: "సాగు భూమి (ఎకరాలు, ఐచ్ఛికం)",
  acresPlaceholder: "ఉదా. 12.5",
  primaryCropLabel: "ప్రధాన పంట లేదా ఉత్పత్తి",
  primaryCropPlaceholder: "ఉదా. బాస్మతి, పాల ఉత్పత్తులు, నర్సరీ",
  sellerKycTitle: "KYC ప్రాథమికాలు",
  sellerKycSubtitle: "డెమో దశ — వాస్తవంలో ID పత్ర OCR మరియు పేరు సరిపోలిక జరుగుతుంది.",
  legalNameLabel: "చట్టపరమైన పేరు (ID ప్రకారం)",
  idLast4Label: "ఆధార్ / ID సందర్భం చివరి 4 అంకెలు",
  sellerBankTitle: "బ్యాంక్ ఖాతా",
  sellerBankSubtitle: "అమ్మిన జాబితాల చెల్లింపులు ఇక్కడ జమ అవుతాయి. డెమో మాత్రమే — నిజమైన బ్యాంక్ వివరాలు నమోదు చేయవద్దు.",
  continueToSecurity: "భద్రతకు కొనసాగించండి",
  accountHolderLabel: "ఖాతాదారు పేరు",
  ifscLabel: "IFSC",
  accountNumberLabel: "ఖాతా నంబర్",
  expertDomainTitle: "మీ రంగం",
  expertDomainSubtitle: "మీరు ఏ అంశాలు లేదా పంటలపై సలహా ఇస్తారు? మీ నిపుణుల ప్రొఫైల్‌లో చూపబడుతుంది.",
  specializationsLabel: "ప్రత్యేకతలు",
  specializationsPlaceholder: "ఉదా. నేల ఆరోగ్యం, పాలిహౌస్ టమాటాలు, సేంద్రీయ ధృవీకరణ",
  yearsExperienceLabel: "అనుభవ సంవత్సరాలు (ఐచ్ఛికం)",
  yearsPlaceholder: "ఉదా. 8",
  expertCredentialsTitle: "అర్హతలు",
  expertCredentialsSubtitle: "డిగ్రీలు, సర్టిఫికేట్లు లేదా సంస్థ అనుబంధాలు నేర్చుకునేవారు తెలుసుకోవాలి.",
  professionalHeadlineLabel: "వృత్తిపరమైన శీర్షిక",
  professionalHeadlinePlaceholder: "ఉదా. వ్యవసాయ శాస్త్రవేత్త, KVK విస్తరణ అధికారి",
  certificationsOptionalLabel: "సర్టిఫికేట్లు (ఐచ్ఛికం)",
  certificationsPlaceholder: "B.Sc. Ag, సేంద్రీయ తనిఖీ సర్టిఫికేట్…",
  expertVerificationTitle: "నిపుణుల ధృవీకరణ",
  expertVerificationSubtitle:
    "బ్యాడ్జ్‌లు ప్రారంభమయ్యే ముందు మేము అర్హతలు మరియు నమూనా కంటెంట్‌ను సమీక్షిస్తాము. ఈ డెమో కొనసాగించినప్పుడు దశ పూర్తవుతుంది.",
  submitForReviewDemo: "సమీక్ష కోసం సమర్పించండి (డెమో)",
  whatHappensNext: "తర్వాత ఏమి జరుగుతుంది",
  expertVerificationBody:
    "వాస్తవంలో: చిన్న బోధన క్లిప్, సందర్భాలు మరియు ఐచ్ఛిక ID అప్‌లోడ్ చేయండి. మా బృందం సాధారణంగా 48 గంటలలో స్పందిస్తుంది.",
  securityVerificationTitle: "భద్రతా ధృవీకరణ",
  securityVerificationSubtitle:
    "ముఖ జీవనం, ID OCR మరియు తృతీయ-పక్ష KYC ఇక్కడ అనుసంధానమవుతుంది. విజయవంతమైన తనిఖీని అనుకరించడానికి క్రింద ట్యాప్ చేయండి.",
  completeVerificationDemo: "ధృవీకరణ పూర్తి చేయండి (డెమో)",
  checksTitle: "తనిఖీలు",
  checkFaceLiveness: "• ముఖ జీవనం (ఆంటీ-స్పూఫ్)",
  checkGovIdOcr: "• ప్రభుత్వ ID క్యాప్చర్ & OCR",
  checkVendorKyc: "• ఐచ్ఛిక విక్రేత KYC సరిపోలిక",
  buyerWalkthroughTitle: "త్వరిత చిట్కాలు",
  buyerWalkthroughSubtitle: "చిన్న పరిచయం — యాప్‌లో మేము మృదువైన గుర్తుచేతలతో గుర్తు చేస్తాము.",
  buyerWalkthroughNudge1: "ఫీడ్‌ను రిఫ్రెష్ చేయడానికి హోమ్‌పై కిందికి లాగండి.",
  buyerWalkthroughNudge2: "పంట కథ లేదా ప్రశ్న పోస్ట్ చేయడానికి + ట్యాబ్ ఉపయోగించండి.",
  buyerWalkthroughNudge3: "జాబితాలపై ధృవీకరించిన బ్యాడ్జ్‌లు విక్రేత ప్రాథమిక తనిఖీలు పూర్తి చేశాడని అర్థం.",
  firstTimeRoleTitle: "మీరు ఏమి చేస్తారు?",
  firstTimeRoleSubtitle: "యాప్‌లో మీ పాత్రను ఎంచుకోండి.",
  firstTimeRoleFarmer: "రైతు",
  firstTimeRoleFarmerSub: "నేను పంటలు పండించి నా ఉత్పత్తిని అమ్ముతాను.",
  firstTimeRoleConsumer: "వినియోగదారు",
  firstTimeRoleConsumerSub: "నేను ఇంటి మరియు వ్యాపార వినియోగం కోసం ఉత్పత్తులు కొనుగోలు చేస్తాను.",
  firstTimeRoleEducator: "బోధకుడు",
  firstTimeRoleEducatorSub: "నేను జ్ఞానం, సాధనాలు మరియు ఉత్తమ పద్ధతులను పంచుకుంటాను.",
  firstTimeRoleLogistics: "లాజిస్టిక్స్",
  firstTimeRoleLogisticsSub: "నేను వ్యవసాయ ఉత్పత్తులు మరియు సామగ్రిని రవాణా చేయడంలో సహాయపడతాను.",
  firstTimeCropsTitle: "మీరు ఏమి పండిస్తారు?",
  firstTimeCropsSubtitle: "సంబంధిత సిఫార్సులు పొందడానికి మీరు ఏ పంటలు పండిస్తారో చెప్పండి.",
  searchByCrop: "పంట ద్వారా శోధించండి",
  cropGroupGrains: "ధాన్యాలు & తృణధాన్యాలు",
  cropGroupVegetables: "కూరగాయలు",
  cropGroupFruits: "పండ్లు",
  cropGroupPulses: "పప్పులు",
  cropRice: "బియ్యం",
  cropWheat: "గోధుమ",
  cropJowar: "జొన్న",
  cropMaize: "మొక్కజొన్న",
  cropBajra: "సజ్జ",
  cropTomato: "టమాట",
  cropPotato: "ఆలుగడ్డ",
  cropOnion: "ఉల్లిపాయ",
  cropChilli: "మిరపకాయ",
  cropBrinjal: "వంకాయ",
  cropMango: "మామిడి",
  cropBanana: "అరటి",
  cropGrapes: "ద్రాక్ష",
  cropOrange: "నారింజ",
  cropApple: "ఆపిల్",
  cropTur: "కంది పప్పు",
  cropMoong: "పెసర పప్పు",
  cropUrad: "మినప పప్పు",
  cropMasoor: "మసూర్ పప్పు",
  cropChana: "శనగ",
  locationLabel: "స్థానం",
  idLast4Placeholder: "••••"
};

export const COMMON_UI_KN: typeof COMMON_UI_EN = {
  loginRequired: "ಲಾಗಿನ್ ಅಗತ್ಯ",
  loginRequiredChat: "ಚಾಟ್‌ನಲ್ಲಿ ರೀಲ್ ಕಳುಹಿಸಲು ಲಾಗಿನ್ ಮಾಡಿ.",
  loginRequiredSave: "ರೀಲ್ ಉಳಿಸಲು ಲಾಗಿನ್ ಮಾಡಿ.",
  loginRequiredReport: "ಪೋಸ್ಟ್ ವರದಿ ಮಾಡಲು ಲಾಗಿನ್ ಮಾಡಿ.",
  loginRequiredDelete: "ಪೋಸ್ಟ್ ಅಳಿಸಲು ಲಾಗಿನ್ ಮಾಡಿ.",
  chatUnavailableSend: "ಈ ಬಳಕೆದಾರರು ಇನ್ನೂ ಸಂದೇಶಗಳನ್ನು ಸ್ವೀಕರಿಸಲು ಸಾಧ್ಯವಿಲ್ಲ.",
  sentTitle: "ಕಳುಹಿಸಲಾಗಿದೆ",
  reelSentTo: "ರೀಲ್ {{name}} ಗೆ ಕಳುಹಿಸಲಾಗಿದೆ.",
  shareFailedSystem: "ಸಿಸ್ಟಂ ಹಂಚಿಕೆ ತೆರೆಯಲಾಗಲಿಲ್ಲ.",
  noMediaTitle: "ಮೀಡಿಯಾ ಇಲ್ಲ",
  noMediaStory: "ಈ ರೀಲ್‌ನಲ್ಲಿ ಸ್ಟೋರಿಗೆ ಮೀಡಿಯಾ ಇಲ್ಲ.",
  addedTitle: "ಸೇರಿಸಲಾಗಿದೆ",
  addedToStory: "ರೀಲ್ ನಿಮ್ಮ ಸ್ಟೋರಿಗೆ ಸೇರಿಸಲಾಗಿದೆ.",
  copiedPostLink: "ಪೋಸ್ಟ್ ಲಿಂಕ್ ಕ್ಲಿಪ್‌ಬೋರ್ಡ್‌ಗೆ ನಕಲಿಸಲಾಗಿದೆ.",
  copyFailedTitle: "ನಕಲು ವಿಫಲ",
  copyFailed: "ಲಿಂಕ್ ನಕಲಿಸಲಾಗಲಿಲ್ಲ.",
  gotItHidePost: "ಸರಿ",
  gotItHidePostMsg: "ನಾವು ಈ ಪೋಸ್ಟ್ ಮರೆಮಾಡುತ್ತೇವೆ ಮತ್ತು ಈ ಸಾಧನದಲ್ಲಿ ನಿಮಗೆ ತೋರಿಸುವುದನ್ನು ಹೊಂದಿಸುತ್ತೇವೆ.",
  thanksReport: "ಧನ್ಯವಾದ",
  thanksReportMsg: "ನಿಮ್ಮ ವರದಿ ಸ್ವೀಕರಿಸಲಾಗಿದೆ, ಶೀಘ್ರದಲ್ಲಿ ಪರಿಶೀಲಿಸುತ್ತೇವೆ.",
  reportFailed: "ವರದಿ ವಿಫಲ",
  notAllowedTitle: "ಅನುಮತಿ ಇಲ್ಲ",
  notAllowedDeleteOwn: "ನೀವು ನಿಮ್ಮ ಸ್ವಂತ ಪೋಸ್ಟ್‌ಗಳನ್ನು ಮಾತ್ರ ಅಳಿಸಬಹುದು.",
  deleteFailed: "ಅಳಿಸುವಿಕೆ ವಿಫಲ",
  deletePostTitle: "ಈ ಪೋಸ್ಟ್ ಅಳಿಸಬೇಕೆ?",
  deletePostBody: "ಇದನ್ನು ರದ್ದುಗೊಳಿಸಲಾಗುವುದಿಲ್ಲ.",
  deleteConfirm: "ಅಳಿಸಿ",
  reportSpam: "ಸ್ಪ್ಯಾಮ್ ಅಥವಾ ತಪ್ಪು ಮಾಹಿತಿ",
  reportHarassment: "ಕಿರುಕುಳ ಅಥವಾ ಬೆದರಿಕೆ",
  reportHate: "ದ್ವೇಷ ಭಾಷಣ ಅಥವಾ ಚಿಹ್ನೆಗಳು",
  reportNudity: "ನಗ್ನತೆ ಅಥವಾ ಲೈಂಗಿಕ ವಿಷಯ",
  reportViolence: "ಹಿಂಸೆ ಅಥವಾ ಅಪಾಯಕಾರಿ ಕೃತ್ಯಗಳು",
  reportScam: "ವಂಚನೆ ಅಥವಾ ಮೋಸ",
  reportIp: "ಬೌದ್ಧಿಕ ಆಸ್ತಿ ಉಲ್ಲಂಘನೆ",
  reportOther: "ಬೇರೆ ಏನಾದರೂ",
  myFarm: "ನನ್ನ ಹೊಲ",
  unknownLocation: "ಅಪರಿಚಿತ",
  liveStream: "ಲೈವ್ ಸ್ಟ್ರೀಮ್",
  liveNow: "ಈಗ ಲೈವ್",
  goLive: "ಲೈವ್ ಹೋಗಿ",
  liveBadge: "ಲೈವ್",
  noOneLive: "ಈಗ ಯಾರೂ ಲೈವ್‌ನಲ್ಲಿ ಇಲ್ಲ",
  popularLive: "ಜನಪ್ರಿಯ ಲೈವ್",
  noLiveStreamsYet: "ಇನ್ನೂ ಲೈವ್ ಸ್ಟ್ರೀಮ್‌ಗಳಿಲ್ಲ",
  noLiveStreamsSub: "ಕ್ರಿಯೇಟರ್‌ಗಳು ಲೈವ್ ಆದಾಗ ಅವರು ಇಲ್ಲಿ ಕಾಣಿಸುತ್ತಾರೆ.",
  startLive: "ಲೈವ್ ಪ್ರಾರಂಭಿಸಿ",
  publicAccount: "ಸಾರ್ವಜನಿಕ ಖಾತೆ",
  messageBtn: "ಸಂದೇಶ",
  tryAgainMoment: "ಸ್ವಲ್ಪ ಸಮಯದ ನಂತರ ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.",
  viewProfilePhoto: "ಪ್ರೊಫೈಲ್ ಫೋಟೋ ನೋಡಿ",
  cannotOpenChat: "ಈ ಬಳಕೆದಾರರಿಗೆ ಇನ್ನೂ ಚಾಟ್ ತೆರೆಯಲಾಗುವುದಿಲ್ಲ.",
  createModePost: "ಪೋಸ್ಟ್",
  createModeStory: "ಸ್ಟೋರಿ",
  createModeReel: "ರೀಲ್",
  createModeLive: "ಲೈವ್",
  filterNormal: "ಸಾಮಾನ್ಯ",
  filterWarm: "ಬೆಚ್ಚಗಿನ",
  filterCool: "ತಂಪಾದ",
  filterBw: "ಕಪ್ಪು-ಬಿಳಿ",
  filterVivid: "ಹೊಳೆಯುವ",
  filterSunset: "ಸೂರ್ಯಾಸ್ತ",
  filterNoir: "ನೋಯ್ರ್",
  createPreviewReel: "ರೀಲ್",
  createPreviewPost: "ಹೊಸ ಪೋಸ್ಟ್",
  createPreviewStory: "ಸ್ಟೋರಿ",
  createPreviewTitle: "ರಚಿಸಿ",
  tagPeople: "ಜನರನ್ನು ಟ್ಯಾಗ್ ಮಾಡಿ",
  addLocation: "ಸ್ಥಳ ಸೇರಿಸಿ",
  locationPrefix: "ಸ್ಥಳ: {{place}}",
  addAudio: "ಆಡಿಯೋ ಸೇರಿಸಿ",
  audioPrefix: "ಆಡಿಯೋ: {{title}}",
  audience: "ಪ್ರೇಕ್ಷಕರು",
  audienceSoon: "ಪ್ರೇಕ್ಷಕ ನಿಯಂತ್ರಣಗಳು ಶೀಘ್ರದಲ್ಲಿ ಬರುತ್ತವೆ.",
  scheduleLiveTitle: "ಲೈವ್ ಶೆಡ್ಯೂಲ್",
  scheduleLiveBody: "ಶೆಡ್ಯೂಲಿಂಗ್ ಮುಂದಿನ ಅಪ್‌ಡೇಟ್‌ನಲ್ಲಿ ಲಭ್ಯವಾಗುತ್ತದೆ.",
  shareBtn: "ಹಂಚಿಕೊಳ್ಳಿ",
  nextBtn: "ಮುಂದೆ",
  writeReelCaptionPh: "ರೀಲ್ ಕ್ಯಾಪ್ಶನ್ ಬರೆಯಿರಿ...",
  writeCaptionPh: "ಕ್ಯಾಪ್ಶನ್ ಬರೆಯಿರಿ...",
  typeTextPlaceholder: "ಪಠ್ಯ ಟೈಪ್ ಮಾಡಿ",
  recents: "ಇತ್ತೀಚಿನ",
  unknownArtist: "ಅಪರಿಚಿತ ಕಲಾವಿದ",
  unknownTitle: "ಅಪರಿಚಿತ",
  createErrSelectPhoto: "ಕನಿಷ್ಠ ಒಂದು ಫೋಟೋ ಆಯ್ಕೆ ಮಾಡಿ.",
  createErrCarouselPhotos: "ಕರೋಸೆಲ್‌ನಲ್ಲಿ ಫೋಟೋಗಳು ಮಾತ್ರ. ವೀಡಿಯೋ ಪೋಸ್ಟ್‌ಗೆ ಒಂದು ವೀಡಿಯೋ ಆಯ್ಕೆ ಮಾಡಿ.",
  createErrPostPhotosOnly: "ಪೋಸ್ಟ್ ಗ್ರಿಡ್‌ನಲ್ಲಿ ಫೋಟೋಗಳು ಮಾತ್ರ. ವೀಡಿಯೋಗೆ ರೀಲ್ ಆಯ್ಕೆ ಮಾಡಿ.",
  createErrCameraPerm: "ಕ್ಯಾಮೆರಾ ಅನುಮತಿ ಅಗತ್ಯ.",
  createErrReelVideoOnly: "ರೀಲ್‌ಗಳಿಗೆ ವೀಡಿಯೋ ಮಾತ್ರ. ವೀಡಿಯೋ ಆಯ್ಕೆ ಮಾಡಿ ಅಥವಾ ರೆಕಾರ್ಡ್ ಮಾಡಿ.",
  createErrCapturePhoto: "ಫೋಟೋ ಕ್ಯಾಪ್ಚರ್ ಆಗಲಿಲ್ಲ.",
  createErrReelVideoOnlyShort: "ರೀಲ್‌ಗಳಿಗೆ ವೀಡಿಯೋ ಮಾತ್ರ.",
  createErrMediaPerm: "ಮೀಡಿಯಾ ಲೈಬ್ರರಿ ಅನುಮತಿ ಅಗತ್ಯ.",
  createErrChooseOption: "ಮುಂದುವರಿಸಲು ಒಂದು ಆಯ್ಕೆ ಮಾಡಿ.",
  createErrStoryMedia: "ಸ್ಟೋರಿ ಮೀಡಿಯಾ ರೆಕಾರ್ಡ್ ಅಥವಾ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ.",
  createErrCaptionRequired: "ಕ್ಯಾಪ್ಶನ್ ಅಗತ್ಯ.",
  createErrReelMedia: "ರೀಲ್ ವೀಡಿಯೋ ರೆಕಾರ್ಡ್ ಅಥವಾ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ.",
  createErrPostMedia: "ನಿಮ್ಮ ಪೋಸ್ಟ್‌ಗೆ ಮೀಡಿಯಾ ಸೇರಿಸಿ.",
  createErrReelSingleVideo: "ರೀಲ್‌ನಲ್ಲಿ ಒಂದೇ ವೀಡಿಯೋ ಇರಬೇಕು.",
  createErrUploadReel: "ಒಂದು ವೀಡಿಯೋ ರೀಲ್ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ.",
  createErrMixedMedia: "ಒಂದು ವೀಡಿಯೋ ಅಥವಾ ಹಲವು ಫೋಟೋಗಳು — ಎರಡೂ ಅಲ್ಲ.",
  createErrOneVideo: "ಪ್ರತಿ ಪೋಸ್ಟ್‌ಗೆ ಒಂದೇ ವೀಡಿಯೋ.",
  createErrUploadImages: "ಚಿತ್ರಗಳನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಲಾಗಲಿಲ್ಲ.",
  createErrPublish: "ವೀಡಿಯೋ ಪ್ರಕಟಿಸಲಾಗಲಿಲ್ಲ.",
  createErrAudioPreview: "ಆಡಿಯೋ ಪ್ರಿವ್ಯೂ ಆಗಲಿಲ್ಲ.",
  createErrAudioFetch: "ಹಾಡುಗಳು ಲೋಡ್ ಆಗಲಿಲ್ಲ. ಇಂಟರ್ನೆಟ್ ಪರಿಶೀಲಿಸಿ.",
  createToolAudio: "ಆಡಿಯೋ",
  createToolText: "ಪಠ್ಯ",
  createToolOverlay: "ಓವರ್ಲೇ",
  createToolFilter: "ಫಿಲ್ಟರ್",
  createToolEdit: "ಸಂಪಾದನೆ",
  openGallery: "ಫೋಟೋ ಗ್ಯಾಲರಿ ತೆರೆಯಿರಿ",
  videoSizeLimit: "ವೀಡಿಯೋ {{size}}MB ಇದೆ. {{max}}MB ಗಿಂತ ಕಡಿಮೆ ಆಯ್ಕೆ ಮಾಡಿ.",
  languageNoteTitle: "ಭಾಷೆ ಕುರಿತು",
  languageNoteBody:
    "ಬಟನ್‌ಗಳು, ಮೆನುಗಳು ಮತ್ತು ಸಂದೇಶಗಳು ನಿಮ್ಮ ಭಾಷೆಗೆ ಬದಲಾಗುತ್ತವೆ. ನೀವು ಬರೆದ ಪೋಸ್ಟ್‌ಗಳು ನೀವು ಟೈಪ್ ಮಾಡಿದಂತೆಯೇ ಉಳಿಯುತ್ತವೆ — ನಮ್ಮ ನಿಘಂಟಿನಲ್ಲಿರುವ ಬೆಳೆ ಪದಗಳು ಮಾತ್ರ ಬದಲಾಗುತ್ತವೆ.",
  back: "ಹಿಂದೆ",
  continue: "ಮುಂದುವರಿಸಿ",
  roleSelectionTitle: "ನೀವು ಕ್ರಾಪ್‌ವೈಬ್ ಹೇಗೆ ಬಳಸುತ್ತೀರಿ?",
  roleSelectionSub: "ಒಂದನ್ನು ಆಯ್ಕೆ ಮಾಡಿ — ನೀವು ಯಾವಾಗ ಬೇಕಾದರೂ ಇತರ ಕ್ಷೇತ್ರಗಳನ್ನು ಅನ್ವೇಷಿಸಬಹುದು.",
  roleBuyerTitle: "ಖರೀದಿದಾರ",
  roleBuyerDesc: "ಉತ್ಪನ್ನಗಳು, ಯಂತ್ರಗಳು ಮತ್ತು ಸೇವೆಗಳನ್ನು ಖರೀದಿಸಿ",
  roleSellerTitle: "ಮಾರಾಟಗಾರ",
  roleSellerDesc: "ನಿಮ್ಮ ಹೊಲದಿಂದ ಪಟ್ಟಿ ಮಾಡಿ ಮತ್ತು ಆರ್ಡರ್‌ಗಳನ್ನು ನಿರ್ವಹಿಸಿ",
  roleExpertTitle: "ತಜ್ಞ",
  roleExpertDesc: "ಕೋರ್ಸ್‌ಗಳನ್ನು ಕಲಿಸಿ ಮತ್ತು ಸಮುದಾಯಕ್ಕೆ ಸಲಹೆ ನೀಡಿ",
  personalInfoTitle: "ನಿಮ್ಮ ಬಗ್ಗೆ",
  personalInfoSubtitle: "ಕ್ರಾಪ್‌ವೈಬ್ ಅನ್ನು ವೈಯಕ್ತೀಕರಿಸಲು ನಾವು ಇದನ್ನು ಬಳಸುತ್ತೇವೆ. ಪ್ರೊಫೈಲ್‌ನಲ್ಲಿ ಯಾವಾಗ ಬೇಕಾದರೂ ಬದಲಾಯಿಸಬಹುದು.",
  personalInfoPrimaryLabel: "ಖಾತೆ ರಚಿಸಿ",
  fullNameLabel: "ಪೂರ್ಣ ಹೆಸರು",
  fullNamePlaceholder: "ನಿಮ್ಮ ಹೆಸರು",
  emailLabel: "ಇಮೇಲ್",
  emailPlaceholder: "you@example.com",
  dobLabel: "ಹುಟ್ಟಿದ ದಿನಾಂಕ",
  dobPlaceholder: "YYYY-MM-DD (ಐಚ್ಛಿಕ)",
  languageLocationTitle: "ಭಾಷೆ ಮತ್ತು ಸ್ಥಳ",
  languageLocationSub: "ಪ್ರಾದೇಶಿಕ ವಿಷಯಕ್ಕೆ ಐಚ್ಛಿಕ ಶಾರ್ಟ್‌ಕಟ್‌ಗಳು",
  preferredLanguageLabel: "ಆದ್ಯತೆಯ ಭಾಷೆ",
  preferredLanguagePlaceholder: "ಉದಾ. ಕನ್ನಡ, English",
  districtOrCityPlaceholder: "ಜಿಲ್ಲೆ ಅಥವಾ ನಗರ",
  addLanguageLocation: "ಭಾಷೆ ಮತ್ತು ಸ್ಥಳ ಸೇರಿಸಿ",
  otpTitle: "6 ಅಂಕಿ ಕೋಡ್",
  otpSubtitle: "{{phone}} ಗೆ ಕಳುಹಿಸಲಾದ ಪರಿಶೀಲನೆ ಕೋಡ್ ನಮೂದಿಸಿ",
  verifying: "ಪರಿಶೀಲಿಸಲಾಗುತ್ತಿದೆ...",
  verifyContinue: "ಪರಿಶೀಲಿಸಿ ಮತ್ತು ಮುಂದುವರಿಸಿ",
  invalidOtp: "ಅಮಾನ್ಯ OTP. ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.",
  resendCode: "ಕೋಡ್ ಮತ್ತೆ ಕಳುಹಿಸಬೇಕೆ?",
  resend: "ಮರುಕಳುಹಿಸಿ",
  sending: "ಕಳುಹಿಸಲಾಗುತ್ತಿದೆ...",
  failedResendOtp: "OTP ಮರುಕಳುಹಿಸಲು ವಿಫಲ.",
  buyerInterestsTitle: "ನಿಮ್ಮ ಆಸಕ್ತಿಗಳು",
  buyerInterestsSubtitle: "ನೀವು ಸಾಮಾನ್ಯವಾಗಿ ಏನು ಖರೀದಿಸುತ್ತೀರಿ? ಪಟ್ಟಿಗಳು ಮತ್ತು ಸಲಹೆಗಳನ್ನು ಕ್ರಮಗೊಳಿಸಲು ಸಹಾಯ ಮಾಡುತ್ತದೆ.",
  interestsLabel: "ಬೆಳೆಗಳು, ವಿಭಾಗಗಳು ಅಥವಾ ಗುರಿಗಳು",
  interestsPlaceholder: "ಉದಾ. ಸಾವಯವ ತರಕಾರಿಗಳು, ಹನಿ ನೀರಾವರಿ, ಟ್ರಾಕ್ಟರ್ ಭಾಗಗಳು",
  buyerDeliveryTitle: "ಡೆಲಿವರಿ ವಿಳಾಸ",
  buyerDeliverySubtitle: "ಮಾರುಕಟ್ಟೆ ಆರ್ಡರ್‌ಗಳಿಗೆ ಡಿಫಾಲ್ಟ್ ಡ್ರಾಪ್-ಆಫ್ (ನಂತರ ಇನ್ನಷ್ಟು ಸೇರಿಸಬಹುದು).",
  addressLineLabel: "ವಿಳಾಸ ಸಾಲು",
  addressLinePlaceholder: "ಹಳ್ಳಿ, ಹೆಗ್ಗುರುತು, ರಸ್ತೆ",
  districtLabel: "ಜಿಲ್ಲೆ",
  pinCodeOptional: "ಪಿನ್ ಕೋಡ್ (ಐಚ್ಛಿಕ)",
  sellerFarmTitle: "ಹೊಲದ ವಿವರಗಳು",
  sellerFarmSubtitle: "ನೀವು ಯಾರೆಂದು ಖರೀದಿದಾರರಿಗೆ ತಿಳಿಸಿ. ಮಾರಾಟಗಾರ ಪ್ರೊಫೈಲ್‌ನಲ್ಲಿ ನಂತರ ಸುಧಾರಿಸಬಹುದು.",
  farmNameLabel: "ಹೊಲ ಅಥವಾ ವ್ಯಾಪಾರದ ಹೆಸರು",
  landAcresLabel: "ಕೃಷಿ ಭೂಮಿ (ಎಕರೆ, ಐಚ್ಛಿಕ)",
  acresPlaceholder: "ಉದಾ. 12.5",
  primaryCropLabel: "ಪ್ರಧಾನ ಬೆಳೆ ಅಥವಾ ಉತ್ಪನ್ನ",
  primaryCropPlaceholder: "ಉದಾ. ಬಾಸ್ಮತಿ, ಹೈನು, ನರ್ಸರಿ",
  sellerKycTitle: "KYC ಮೂಲಭೂತ ಅಂಶಗಳು",
  sellerKycSubtitle: "ಡೆಮೊ ಹಂತ — ಉತ್ಪಾದನೆಯಲ್ಲಿ ID ದಾಖಲೆ OCR ಮತ್ತು ಹೆಸರು ಹೊಂದಾಣಿಕೆ ನಡೆಯುತ್ತದೆ.",
  legalNameLabel: "ಕಾನೂನು ಹೆಸರು (ID ಪ್ರಕಾರ)",
  idLast4Label: "ಆಧಾರ್ / ID ಉಲ್ಲೇಖದ ಕೊನೆಯ 4 ಅಂಕಿಗಳು",
  sellerBankTitle: "ಬ್ಯಾಂಕ್ ಖಾತೆ",
  sellerBankSubtitle: "ಮಾರಾಟವಾದ ಪಟ್ಟಿಗಳ ಪಾವತಿ ಇಲ್ಲಿ ಜಮೆಯಾಗುತ್ತದೆ. ಡೆಮೊ ಮಾತ್ರ — ನಿಜವಾದ ಬ್ಯಾಂಕ್ ವಿವರ ನಮೂದಿಸಬೇಡಿ.",
  continueToSecurity: "ಭದ್ರತೆಗೆ ಮುಂದುವರಿಸಿ",
  accountHolderLabel: "ಖಾತೆದಾರರ ಹೆಸರು",
  ifscLabel: "IFSC",
  accountNumberLabel: "ಖಾತೆ ಸಂಖ್ಯೆ",
  expertDomainTitle: "ನಿಮ್ಮ ಕ್ಷೇತ್ರ",
  expertDomainSubtitle: "ನೀವು ಯಾವ ವಿಷಯಗಳು ಅಥವಾ ಬೆಳೆಗಳ ಬಗ್ಗೆ ಸಲಹೆ ನೀಡುತ್ತೀರಿ? ನಿಮ್ಮ ತಜ್ಞ ಪ್ರೊಫೈಲ್‌ನಲ್ಲಿ ತೋರಿಸಲಾಗುತ್ತದೆ.",
  specializationsLabel: "ವಿಶೇಷತೆಗಳು",
  specializationsPlaceholder: "ಉದಾ. ಮಣ್ಣಿನ ಆರೋಗ್ಯ, ಪಾಲಿಹೌಸ್ ಟೊಮೇಟೊ, ಸಾವಯವ ಪ್ರಮಾಣೀಕರಣ",
  yearsExperienceLabel: "ಅನುಭವದ ವರ್ಷಗಳು (ಐಚ್ಛಿಕ)",
  yearsPlaceholder: "ಉದಾ. 8",
  expertCredentialsTitle: "ಅರ್ಹತೆಗಳು",
  expertCredentialsSubtitle: "ಕಲಿಯುವವರು ತಿಳಿಯಬೇಕಾದ ಪದವಿಗಳು, ಪ್ರಮಾಣಪತ್ರಗಳು ಅಥವಾ ಸಂಸ್ಥೆಯ ಸಂಬಂಧ.",
  professionalHeadlineLabel: "ವೃತ್ತಿಪರ ಶೀರ್ಷಿಕೆ",
  professionalHeadlinePlaceholder: "ಉದಾ. ಕೃಷಿ ವಿಜ್ಞಾನಿ, KVK ವಿಸ್ತರಣಾ ಅಧಿಕಾರಿ",
  certificationsOptionalLabel: "ಪ್ರಮಾಣಪತ್ರಗಳು (ಐಚ್ಛಿಕ)",
  certificationsPlaceholder: "B.Sc. Ag, ಸಾವಯವ ತಪಾಸಣೆ ಪ್ರಮಾಣಪತ್ರ…",
  expertVerificationTitle: "ತಜ್ಞ ಪರಿಶೀಲನೆ",
  expertVerificationSubtitle:
    "ಬ್ಯಾಡ್ಜ್‌ಗಳು ಲೈವ್ ಆಗುವ ಮೊದಲು ನಾವು ಅರ್ಹತೆ ಮತ್ತು ನಮೂನೆ ವಿಷಯವನ್ನು ಪರಿಶೀಲಿಸುತ್ತೇವೆ. ಈ ಡೆಮೊ ಮುಂದುವರಿಸಿದಾಗ ಹಂತ ಪೂರ್ಣವಾಗುತ್ತದೆ.",
  submitForReviewDemo: "ಪರಿಶೀಲನೆಗೆ ಸಲ್ಲಿಸಿ (ಡೆಮೊ)",
  whatHappensNext: "ಮುಂದೆ ಏನಾಗುತ್ತದೆ",
  expertVerificationBody:
    "ಉತ್ಪಾದನೆ: ಸಂಕ್ಷಿಪ್ತ ಬೋಧನಾ ಕ್ಲಿಪ್, ಉಲ್ಲೇಖಗಳು ಮತ್ತು ಐಚ್ಛಿಕ ID ಅಪ್‌ಲೋಡ್ ಮಾಡಿ. ನಮ್ಮ ತಂಡ ಸಾಮಾನ್ಯವಾಗಿ 48 ಗಂಟೆಗಳಲ್ಲಿ ಪ್ರತಿಕ್ರಿಯಿಸುತ್ತದೆ.",
  securityVerificationTitle: "ಭದ್ರತಾ ಪರಿಶೀಲನೆ",
  securityVerificationSubtitle:
    "ಮುಖ ಜೀವಂತತೆ, ID OCR ಮತ್ತು ತೃತೀಯ-ಪಕ್ಷ KYC ಇಲ್ಲಿ ಸಂಪರ್ಕಗೊಳ್ಳುತ್ತದೆ. ಯಶಸ್ವಿ ಪರಿಶೀಲನೆ ಅನುಕರಿಸಲು ಕೆಳಗೆ ಟ್ಯಾಪ್ ಮಾಡಿ.",
  completeVerificationDemo: "ಪರಿಶೀಲನೆ ಪೂರ್ಣಗೊಳಿಸಿ (ಡೆಮೊ)",
  checksTitle: "ಪರಿಶೀಲನೆಗಳು",
  checkFaceLiveness: "• ಮುಖ ಜೀವಂತತೆ (ಆಂಟಿ-ಸ್ಪೂಫ್)",
  checkGovIdOcr: "• ಸರ್ಕಾರಿ ID ಕ್ಯಾಪ್ಚರ್ & OCR",
  checkVendorKyc: "• ಐಚ್ಛಿಕ ಮಾರಾಟಗಾರ KYC ಹೊಂದಾಣಿಕೆ",
  buyerWalkthroughTitle: "ತ್ವರಿತ ಸಲಹೆಗಳು",
  buyerWalkthroughSubtitle: "ಸಂಕ್ಷಿಪ್ತ ಪರಿಚಯ — ಅಪ್ಲಿಕೇಶನ್‌ನಲ್ಲಿ ನಾವು ಮೃದು ನೆನಪೊಲೆಗಳೊಂದಿಗೆ ನೆನಪಿಸುತ್ತೇವೆ.",
  buyerWalkthroughNudge1: "ಫೀಡ್ ರಿಫ್ರೆಶ್ ಮಾಡಲು ಹೋಮ್‌ನಲ್ಲಿ ಕೆಳಗೆ ಎಳೆಯಿರಿ.",
  buyerWalkthroughNudge2: "ಫಸಲು ಕಥೆ ಅಥವಾ ಪ್ರಶ್ನೆ ಪೋಸ್ಟ್ ಮಾಡಲು + ಟ್ಯಾಬ್ ಬಳಸಿ.",
  buyerWalkthroughNudge3: "ಪಟ್ಟಿಗಳಲ್ಲಿ ಪರಿಶೀಲಿತ ಬ್ಯಾಡ್ಜ್ ಎಂದರೆ ಮಾರಾಟಗಾರ ಮೂಲ ಪರಿಶೀಲನೆ ಪೂರ್ಣಗೊಳಿಸಿದ್ದಾರೆ.",
  firstTimeRoleTitle: "ನೀವು ಏನು ಮಾಡುತ್ತೀರಿ?",
  firstTimeRoleSubtitle: "ಅಪ್ಲಿಕೇಶನ್‌ನಲ್ಲಿ ನಿಮ್ಮ ಪಾತ್ರ ಆಯ್ಕೆ ಮಾಡಿ.",
  firstTimeRoleFarmer: "ರೈತ",
  firstTimeRoleFarmerSub: "ನಾನು ಬೆಳೆ ಬೆಳೆಯುತ್ತೇನೆ ಮತ್ತು ನನ್ನ ಉತ್ಪನ್ನವನ್ನು ಮಾರುತ್ತೇನೆ.",
  firstTimeRoleConsumer: "ಗ್ರಾಹಕ",
  firstTimeRoleConsumerSub: "ನಾನು ಮನೆ ಮತ್ತು ವ್ಯಾಪಾರ ಬಳಕೆಗೆ ಉತ್ಪನ್ನ ಖರೀದಿಸುತ್ತೇನೆ.",
  firstTimeRoleEducator: "ಶಿಕ್ಷಕ",
  firstTimeRoleEducatorSub: "ನಾನು ಜ್ಞಾನ, ಸಾಧನಗಳು ಮತ್ತು ಉತ್ತಮ ಪದ್ಧತಿಗಳನ್ನು ಹಂಚಿಕೊಳ್ಳುತ್ತೇನೆ.",
  firstTimeRoleLogistics: "ಲಾಜಿಸ್ಟಿಕ್ಸ್",
  firstTimeRoleLogisticsSub: "ನಾನು ಕೃಷಿ ಉತ್ಪನ್ನ ಮತ್ತು ಸಾಮಗ್ರಿ ಸಾಗಿಸಲು ಸಹಾಯ ಮಾಡುತ್ತೇನೆ.",
  firstTimeCropsTitle: "ನೀವು ಏನು ಬೆಳೆಯುತ್ತೀರಿ?",
  firstTimeCropsSubtitle: "ಸಂಬಂಧಿತ ಶಿಫಾರಸುಗಳನ್ನು ಪಡೆಯಲು ನೀವು ಯಾವ ಬೆಳೆ ಬೆಳೆಯುತ್ತೀರಿ ಎಂದು ಹೇಳಿ.",
  searchByCrop: "ಬೆಳೆಯ ಮೂಲಕ ಹುಡುಕಿ",
  cropGroupGrains: "ಧಾನ್ಯಗಳು & ಸಿರಿಧಾನ್ಯಗಳು",
  cropGroupVegetables: "ತರಕಾರಿಗಳು",
  cropGroupFruits: "ಹಣ್ಣುಗಳು",
  cropGroupPulses: "ಬೇಳೆಕಾಳುಗಳು",
  cropRice: "ಅಕ್ಕಿ",
  cropWheat: "ಗೋಧಿ",
  cropJowar: "ಜೋಳ",
  cropMaize: "ಮೆಕ್ಕೆಜೋಳ",
  cropBajra: "ಸಜ್ಜೆ",
  cropTomato: "ಟೊಮೇಟೊ",
  cropPotato: "ಆಲೂಗಡ್ಡೆ",
  cropOnion: "ಈರುಳ್ಳಿ",
  cropChilli: "ಮೆಣಸಿನಕಾಯಿ",
  cropBrinjal: "ಬದನೆಕಾಯಿ",
  cropMango: "ಮಾವು",
  cropBanana: "ಬಾಳೆ",
  cropGrapes: "ದ್ರಾಕ್ಷಿ",
  cropOrange: "ಕಿತ್ತಳೆ",
  cropApple: "ಸೇಬು",
  cropTur: "ತೊಗರಿ",
  cropMoong: "ಹೆಸರು",
  cropUrad: "ಉದ್ದು",
  cropMasoor: "ಮಸೂರ",
  cropChana: "ಕಡಲೆ",
  locationLabel: "ಸ್ಥಳ",
  idLast4Placeholder: "••••"
};

export const COMMON_UI_ML: typeof COMMON_UI_EN = {
  loginRequired: "ലോഗിൻ ആവശ്യമാണ്",
  loginRequiredChat: "ചാറ്റിൽ റീൽ അയയ്ക്കാൻ ലോഗിൻ ചെയ്യുക.",
  loginRequiredSave: "റീൽ സേവ് ചെയ്യാൻ ലോഗിൻ ചെയ്യുക.",
  loginRequiredReport: "പോസ്റ്റ് റിപ്പോർട്ട് ചെയ്യാൻ ലോഗിൻ ചെയ്യുക.",
  loginRequiredDelete: "പോസ്റ്റ് ഡിലീറ്റ് ചെയ്യാൻ ലോഗിൻ ചെയ്യുക.",
  chatUnavailableSend: "ഈ ഉപയോക്താവിന് ഇതുവരെ സന്ദേശങ്ങൾ സ്വീകരിക്കാൻ കഴിയില്ല.",
  sentTitle: "അയച്ചു",
  reelSentTo: "റീൽ {{name}} ലേക്ക് അയച്ചു.",
  shareFailedSystem: "സിസ്റ്റം ഷെയർ തുറക്കാൻ കഴിഞ്ഞില്ല.",
  noMediaTitle: "മീഡിയ ഇല്ല",
  noMediaStory: "ഈ റീലിന് സ്റ്റോറിയിലേക്ക് മീഡിയ ഇല്ല.",
  addedTitle: "ചേർത്തു",
  addedToStory: "റീൽ നിങ്ങളുടെ സ്റ്റോറിയിലേക്ക് ചേർത്തു.",
  copiedPostLink: "പോസ്റ്റ് ലിങ്ക് ക്ലിപ്പ്ബോർഡിലേക്ക് കോപ്പി ചെയ്തു.",
  copyFailedTitle: "കോപ്പി പരാജയം",
  copyFailed: "ലിങ്ക് കോപ്പി ചെയ്യാൻ കഴിഞ്ഞില്ല.",
  gotItHidePost: "മനസ്സിലായി",
  gotItHidePostMsg: "ഈ പോസ്റ്റ് മറയ്ക്കുകയും ഈ ഉപകരണത്തിൽ നിങ്ങൾക്ക് കാണിക്കുന്നത് ക്രമീകരിക്കുകയും ചെയ്യും.",
  thanksReport: "നന്ദി",
  thanksReportMsg: "നിങ്ങളുടെ റിപ്പോർട്ട് ലഭിച്ചു, ഉടൻ പരിശോധിക്കും.",
  reportFailed: "റിപ്പോർട്ട് പരാജയം",
  notAllowedTitle: "അനുവാദമില്ല",
  notAllowedDeleteOwn: "നിങ്ങളുടെ സ്വന്തം പോസ്റ്റുകൾ മാത്രമേ ഡിലീറ്റ് ചെയ്യാൻ കഴിയൂ.",
  deleteFailed: "ഡിലീറ്റ് പരാജയം",
  deletePostTitle: "ഈ പോസ്റ്റ് ഡിലീറ്റ് ചെയ്യണോ?",
  deletePostBody: "ഇത് പഴയപടിയാക്കാൻ കഴിയില്ല.",
  deleteConfirm: "ഡിലീറ്റ്",
  reportSpam: "സ്പാം അല്ലെങ്കിൽ തെറ്റിദ്ധരിപ്പിക്കുന്നത്",
  reportHarassment: "ഉപദ്രവം അല്ലെങ്കിൽ ഭീഷണി",
  reportHate: "വിദ്വേഷ പ്രസംഗം അല്ലെങ്കിൽ ചിഹ്നങ്ങൾ",
  reportNudity: "നഗ്നത അല്ലെങ്കിൽ ലൈംഗിക ഉള്ളടക്കം",
  reportViolence: "അക്രമം അല്ലെങ്കിൽ അപകടകരമായ പ്രവൃത്തികൾ",
  reportScam: "തട്ടിപ്പ് അല്ലെങ്കിൽ വഞ്ചന",
  reportIp: "ബൗദ്ധിക സ്വത്ത് ലംഘനം",
  reportOther: "മറ്റെന്തെങ്കിലും",
  myFarm: "എന്റെ കൃഷിയിടം",
  unknownLocation: "അജ്ഞാതം",
  liveStream: "ലൈവ് സ്ട്രീം",
  liveNow: "ഇപ്പോൾ ലൈവ്",
  goLive: "ലൈവ് ആകുക",
  liveBadge: "ലൈവ്",
  noOneLive: "ഇപ്പോൾ ആരും ലൈവിൽ ഇല്ല",
  popularLive: "ജനപ്രിയ ലൈവ്",
  noLiveStreamsYet: "ഇതുവരെ ലൈവ് സ്ട്രീമുകൾ ഇല്ല",
  noLiveStreamsSub: "ക്രിയേറ്റർമാർ ലൈവ് ആകുമ്പോൾ ഇവിടെ കാണാം.",
  startLive: "ലൈവ് ആരംഭിക്കുക",
  publicAccount: "പൊതു അക്കൗണ്ട്",
  messageBtn: "സന്ദേശം",
  tryAgainMoment: "കുറച്ച് സമയത്തിന് ശേഷം വീണ്ടും ശ്രമിക്കുക.",
  viewProfilePhoto: "പ്രൊഫൈൽ ഫോട്ടോ കാണുക",
  cannotOpenChat: "ഈ ഉപയോക്താവിന് ഇതുവരെ ചാറ്റ് തുറക്കാൻ കഴിയില്ല.",
  createModePost: "പോസ്റ്റ്",
  createModeStory: "സ്റ്റോറി",
  createModeReel: "റീൽ",
  createModeLive: "ലൈവ്",
  filterNormal: "സാധാരണ",
  filterWarm: "ഊഷ്മള",
  filterCool: "തണുത്ത",
  filterBw: "കറുപ്പ്-വെള്ള",
  filterVivid: "തിളക്കമുള്ള",
  filterSunset: "സൂര്യാസ്തമയം",
  filterNoir: "നോയർ",
  createPreviewReel: "റീൽ",
  createPreviewPost: "പുതിയ പോസ്റ്റ്",
  createPreviewStory: "സ്റ്റോറി",
  createPreviewTitle: "സൃഷ്ടിക്കുക",
  tagPeople: "ആളുകളെ ടാഗ് ചെയ്യുക",
  addLocation: "സ്ഥലം ചേർക്കുക",
  locationPrefix: "സ്ഥലം: {{place}}",
  addAudio: "ഓഡിയോ ചേർക്കുക",
  audioPrefix: "ഓഡിയോ: {{title}}",
  audience: "പ്രേക്ഷകർ",
  audienceSoon: "പ്രേക്ഷക നിയന്ത്രണങ്ങൾ ഉടൻ വരും.",
  scheduleLiveTitle: "ലൈവ് ഷെഡ്യൂൾ",
  scheduleLiveBody: "ഷെഡ്യൂളിംഗ് ഭാവി അപ്ഡേറ്റിൽ ലഭ്യമാകും.",
  shareBtn: "ഷെയർ",
  nextBtn: "അടുത്തത്",
  writeReelCaptionPh: "റീൽ ക്യാപ്ഷൻ എഴുതുക...",
  writeCaptionPh: "ക്യാപ്ഷൻ എഴുതുക...",
  typeTextPlaceholder: "ടെക്സ്റ്റ് ടൈപ്പ് ചെയ്യുക",
  recents: "സമീപകാല",
  unknownArtist: "അജ്ഞാത കലാകാരൻ",
  unknownTitle: "അജ്ഞാതം",
  createErrSelectPhoto: "ഒരു ഫോട്ടോയെങ്കിലും തിരഞ്ഞെടുക്കുക.",
  createErrCarouselPhotos: "കറൗസലിൽ ഫോട്ടോകൾ മാത്രം. വീഡിയോ പോസ്റ്റിന് ഒരു വീഡിയോ തിരഞ്ഞെടുക്കുക.",
  createErrPostPhotosOnly: "പോസ്റ്റ് ഗ്രിഡിൽ ഫോട്ടോകൾ മാത്രം. വീഡിയോയ്ക്ക് റീൽ തിരഞ്ഞെടുക്കുക.",
  createErrCameraPerm: "ക്യാമറ അനുമതി ആവശ്യമാണ്.",
  createErrReelVideoOnly: "റീലുകൾക്ക് വീഡിയോ മാത്രം. വീഡിയോ തിരഞ്ഞെടുക്കുക അല്ലെങ്കിൽ റെക്കോർഡ് ചെയ്യുക.",
  createErrCapturePhoto: "ഫോട്ടോ ക്യാപ്ചർ ചെയ്യാൻ കഴിഞ്ഞില്ല.",
  createErrReelVideoOnlyShort: "റീലുകൾക്ക് വീഡിയോ മാത്രം.",
  createErrMediaPerm: "മീഡിയ ലൈബ്രറി അനുമതി ആവശ്യമാണ്.",
  createErrChooseOption: "തുടരാൻ ഒരു ഓപ്ഷൻ തിരഞ്ഞെടുക്കുക.",
  createErrStoryMedia: "സ്റ്റോറി മീഡിയ റെക്കോർഡ് അല്ലെങ്കിൽ അപ്‌ലോഡ് ചെയ്യുക.",
  createErrCaptionRequired: "ക്യാപ്ഷൻ ആവശ്യമാണ്.",
  createErrReelMedia: "റീൽ വീഡിയോ റെക്കോർഡ് അല്ലെങ്കിൽ അപ്‌ലോഡ് ചെയ്യുക.",
  createErrPostMedia: "നിങ്ങളുടെ പോസ്റ്റിലേക്ക് മീഡിയ ചേർക്കുക.",
  createErrReelSingleVideo: "ഒരു റീലിൽ ഒരു വീഡിയോ മാത്രമേ ആകാവൂ.",
  createErrUploadReel: "ഒരു വീഡിയോ റീൽ അപ്‌ലോഡ് ചെയ്യുക.",
  createErrMixedMedia: "ഒരു വീഡിയോ അല്ലെങ്കിൽ ഒന്നിലധികം ഫോട്ടോകൾ — രണ്ടും അല്ല.",
  createErrOneVideo: "ഓരോ പോസ്റ്റിലും ഒരു വീഡിയോ മാത്രം.",
  createErrUploadImages: "ചിത്രങ്ങൾ അപ്‌ലോഡ് ചെയ്യാൻ കഴിഞ്ഞില്ല.",
  createErrPublish: "വീഡിയോ പ്രസിദ്ധീകരിക്കാൻ കഴിഞ്ഞില്ല.",
  createErrAudioPreview: "ഓഡിയോ പ്രിവ്യൂ ചെയ്യാൻ കഴിഞ്ഞില്ല.",
  createErrAudioFetch: "പാട്ടുകൾ ലോഡ് ചെയ്യാൻ കഴിഞ്ഞില്ല. ഇന്റർനെറ്റ് പരിശോധിക്കുക.",
  createToolAudio: "ഓഡിയോ",
  createToolText: "ടെക്സ്റ്റ്",
  createToolOverlay: "ഓവർലേ",
  createToolFilter: "ഫിൽട്ടർ",
  createToolEdit: "എഡിറ്റ്",
  openGallery: "ഫോട്ടോ ഗാലറി തുറക്കുക",
  videoSizeLimit: "വീഡിയോ {{size}}MB ആണ്. {{max}}MB-ൽ കുറവ് തിരഞ്ഞെടുക്കുക.",
  languageNoteTitle: "ഭാഷയെ കുറിച്ച്",
  languageNoteBody:
    "ബട്ടണുകൾ, മെനുകൾ, സന്ദേശങ്ങൾ നിങ്ങളുടെ ഭാഷയിലേക്ക് മാറും. നിങ്ങൾ ടൈപ്പ് ചെയ്ത പോസ്റ്റുകൾ അതേപടി തുടരും — ഞങ്ങളുടെ നിഘണ്ടുവിലെ വിള പദങ്ങൾ മാത്രം മാറും.",
  back: "പിന്നോട്ട്",
  continue: "തുടരുക",
  roleSelectionTitle: "നിങ്ങൾ ക്രോപ്‌വൈബ് എങ്ങനെ ഉപയോഗിക്കും?",
  roleSelectionSub: "ഒന്ന് തിരഞ്ഞെടുക്കുക — എപ്പോൾ വേണമെങ്കിലും മറ്റ് മേഖലകൾ പര്യവേക്ഷണം ചെയ്യാം.",
  roleBuyerTitle: "വാങ്ങുന്നയാൾ",
  roleBuyerDesc: "ഉൽപ്പന്നങ്ങൾ, യന്ത്രങ്ങൾ, സേവനങ്ങൾ വാങ്ങുക",
  roleSellerTitle: "വിൽക്കുന്നയാൾ",
  roleSellerDesc: "നിങ്ങളുടെ കൃഷിയിടത്തിൽ നിന്ന് ലിസ്റ്റ് ചെയ്ത് ഓർഡറുകൾ നിയന്ത്രിക്കുക",
  roleExpertTitle: "വിദഗ്ധൻ",
  roleExpertDesc: "കോഴ്‌സുകൾ പഠിപ്പിക്കുകയും സമൂഹത്തിന് ഉപദേശം നൽകുകയും ചെയ്യുക",
  personalInfoTitle: "നിങ്ങളെ കുറിച്ച്",
  personalInfoSubtitle: "ക്രോപ്‌വൈബ് വ്യക്തിഗതമാക്കാൻ ഞങ്ങൾ ഇത് ഉപയോഗിക്കുന്നു. പ്രൊഫൈലിൽ എപ്പോൾ വേണമെങ്കിലും മാറ്റാം.",
  personalInfoPrimaryLabel: "അക്കൗണ്ട് സൃഷ്ടിക്കുക",
  fullNameLabel: "മുഴുവൻ പേര്",
  fullNamePlaceholder: "നിങ്ങളുടെ പേര്",
  emailLabel: "ഇമെയിൽ",
  emailPlaceholder: "you@example.com",
  dobLabel: "ജനനത്തീയതി",
  dobPlaceholder: "YYYY-MM-DD (ഐച്ഛികം)",
  languageLocationTitle: "ഭാഷയും സ്ഥലവും",
  languageLocationSub: "പ്രാദേശിക ഉള്ളടക്കത്തിനുള്ള ഐച്ഛിക കുറുക്കുവഴികൾ",
  preferredLanguageLabel: "ഇഷ്ട ഭാഷ",
  preferredLanguagePlaceholder: "ഉദാ. മലയാളം, English",
  districtOrCityPlaceholder: "ജില്ല അല്ലെങ്കിൽ നഗരം",
  addLanguageLocation: "ഭാഷയും സ്ഥലവും ചേർക്കുക",
  otpTitle: "6 അക്ക കോഡ്",
  otpSubtitle: "{{phone}} ലേക്ക് അയച്ച സ്ഥിരീകരണ കോഡ് നൽകുക",
  verifying: "സ്ഥിരീകരിക്കുന്നു...",
  verifyContinue: "സ്ഥിരീകരിച്ച് തുടരുക",
  invalidOtp: "അസാധുവായ OTP. വീണ്ടും ശ്രമിക്കുക.",
  resendCode: "കോഡ് വീണ്ടും അയയ്ക്കണോ?",
  resend: "വീണ്ടും അയയ്ക്കുക",
  sending: "അയയ്ക്കുന്നു...",
  failedResendOtp: "OTP വീണ്ടും അയയ്ക്കാൻ കഴിഞ്ഞില്ല.",
  buyerInterestsTitle: "നിങ്ങളുടെ താൽപ്പര്യങ്ങൾ",
  buyerInterestsSubtitle: "നിങ്ങൾ സാധാരണയായി എന്താണ് വാങ്ങുന്നത്? ലിസ്റ്റിംഗും നിർദേശങ്ങളും ക്രമീകരിക്കാൻ സഹായിക്കും.",
  interestsLabel: "വിളകൾ, വിഭാഗങ്ങൾ അല്ലെങ്കിൽ ലക്ഷ്യങ്ങൾ",
  interestsPlaceholder: "ഉദാ. ജൈവ പച്ചക്കറികൾ, ഡ്രിപ്പ് ഇറിഗേഷൻ, ട്രാക്ടർ ഭാഗങ്ങൾ",
  buyerDeliveryTitle: "ഡെലിവറി വിലാസം",
  buyerDeliverySubtitle: "മാർക്കറ്റ്‌പ്ലേസ് ഓർഡറുകൾക്കുള്ള ഡിഫോൾട്ട് ഡ്രോപ്-ഓഫ് (പിന്നീട് കൂടുതൽ ചേർക്കാം).",
  addressLineLabel: "വിലാസ വരി",
  addressLinePlaceholder: "ഗ്രാമം, ലാൻഡ്‌മാർക്ക്, റോഡ്",
  districtLabel: "ജില്ല",
  pinCodeOptional: "പിൻ കോഡ് (ഐച്ഛികം)",
  sellerFarmTitle: "കൃഷിയിട വിവരങ്ങൾ",
  sellerFarmSubtitle: "നിങ്ങൾ ആരാണെന്ന് വാങ്ങുന്നവരോട് പറയുക. വിൽപ്പനക്കാരന്റെ പ്രൊഫൈലിൽ പിന്നീട് മെച്ചപ്പെടുത്താം.",
  farmNameLabel: "കൃഷിയിടം അല്ലെങ്കിൽ ബിസിനസ് പേര്",
  landAcresLabel: "കൃഷി ഭൂമി (ഏക്കർ, ഐച്ഛികം)",
  acresPlaceholder: "ഉദാ. 12.5",
  primaryCropLabel: "പ്രധാന വിള അല്ലെങ്കിൽ ഉൽപ്പന്നം",
  primaryCropPlaceholder: "ഉദാ. ബാസ്മതി, ക്ഷീരം, നഴ്‌സറി",
  sellerKycTitle: "KYC അടിസ്ഥാനങ്ങൾ",
  sellerKycSubtitle: "ഡെമോ ഘട്ടം — ഉൽപാദനത്തിൽ ID ഡോക്യുമെന്റ് OCR ഉം പേര് പൊരുത്തപ്പെടുത്തലും നടക്കും.",
  legalNameLabel: "നിയമപരമായ പേര് (ID പ്രകാരം)",
  idLast4Label: "ആധാർ / ID റഫറൻസിന്റെ അവസാന 4 അക്കങ്ങൾ",
  sellerBankTitle: "ബാങ്ക് അക്കൗണ്ട്",
  sellerBankSubtitle: "വിൽക്കുന്ന ലിസ്റ്റിംഗുകളുടെ പേയ്‌മെന്റ് ഇവിടെ ജമ ചെയ്യും. ഡെമോ മാത്രം — യഥാർത്ഥ ബാങ്ക് വിവരങ്ങൾ നൽകരുത്.",
  continueToSecurity: "സുരക്ഷയിലേക്ക് തുടരുക",
  accountHolderLabel: "അക്കൗണ്ട് ഉടമയുടെ പേര്",
  ifscLabel: "IFSC",
  accountNumberLabel: "അക്കൗണ്ട് നമ്പർ",
  expertDomainTitle: "നിങ്ങളുടെ മേഖല",
  expertDomainSubtitle: "നിങ്ങൾ ഏത് വിഷയങ്ങളിൽ അല്ലെങ്കിൽ വിളകളിൽ ഉപദേശം നൽകുന്നു? നിങ്ങളുടെ വിദഗ്ധ പ്രൊഫൈലിൽ കാണിക്കും.",
  specializationsLabel: "സ്പെഷ്യലൈസേഷനുകൾ",
  specializationsPlaceholder: "ഉദാ. മണ്ണിന്റെ ആരോഗ്യം, പോളിഹൗസ് തക്കാളി, ജൈവ സർട്ടിഫിക്കേഷൻ",
  yearsExperienceLabel: "അനുഭവ വർഷങ്ങൾ (ഐച്ഛികം)",
  yearsPlaceholder: "ഉദാ. 8",
  expertCredentialsTitle: "യോഗ്യതകൾ",
  expertCredentialsSubtitle: "പഠിതാക്കൾ അറിഞ്ഞിരിക്കേണ്ട ബിരുദങ്ങൾ, സർട്ടിഫിക്കറ്റുകൾ അല്ലെങ്കിൽ സ്ഥാപന ബന്ധങ്ങൾ.",
  professionalHeadlineLabel: "പ്രൊഫഷണൽ തലക്കെട്ട്",
  professionalHeadlinePlaceholder: "ഉദാ. കാർഷിക ശാസ്ത്രജ്ഞൻ, KVK എക്സ്റ്റൻഷൻ ഓഫീസർ",
  certificationsOptionalLabel: "സർട്ടിഫിക്കറ്റുകൾ (ഐച്ഛികം)",
  certificationsPlaceholder: "B.Sc. Ag, ജൈവ പരിശോധനാ സർട്ടിഫിക്കറ്റ്…",
  expertVerificationTitle: "വിദഗ്ധ സ്ഥിരീകരണം",
  expertVerificationSubtitle:
    "ബാഡ്ജുകൾ ലൈവ് ആകുന്നതിന് മുമ്പ് ഞങ്ങൾ യോഗ്യതയും സാമ്പിൾ ഉള്ളടക്കവും പരിശോധിക്കും. ഈ ഡെമോ തുടരുമ്പോൾ ഘട്ടം പൂർത്തിയാകും.",
  submitForReviewDemo: "അവലോകനത്തിന് സമർപ്പിക്കുക (ഡെമോ)",
  whatHappensNext: "അടുത്തത് എന്ത് സംഭവിക്കും",
  expertVerificationBody:
    "ഉൽപാദനം: ചെറിയ ബോധന ക്ലിപ്, റഫറൻസുകൾ, ഐച്ഛിക ID അപ്‌ലോഡ് ചെയ്യുക. ഞങ്ങളുടെ ടീം സാധാരണയായി 48 മണിക്കൂറിനുള്ളിൽ പ്രതികരിക്കും.",
  securityVerificationTitle: "സുരക്ഷാ സ്ഥിരീകരണം",
  securityVerificationSubtitle:
    "മുഖ ജീവനം, ID OCR, മൂന്നാം കക്ഷി KYC ഇവിടെ ബന്ധിപ്പിക്കും. വിജയകരമായ പരിശോധന അനുകരിക്കാൻ താഴെ ടാപ്പ് ചെയ്യുക.",
  completeVerificationDemo: "സ്ഥിരീകരണം പൂർത്തിയാക്കുക (ഡെമോ)",
  checksTitle: "പരിശോധനകൾ",
  checkFaceLiveness: "• മുഖ ജീവനം (ആന്റി-സ്പൂഫ്)",
  checkGovIdOcr: "• സർക്കാർ ID ക്യാപ്ചർ & OCR",
  checkVendorKyc: "• ഐച്ഛിക വെണ്ടർ KYC പൊരുത്തം",
  buyerWalkthroughTitle: "ദ്രുത നുറുങ്ങുകൾ",
  buyerWalkthroughSubtitle: "ഒരു ചെറിയ പരിചയപ്പെടുത്തൽ — ആപ്പിനുള്ളിൽ ഞങ്ങൾ മൃദുവായ ഓർമ്മപ്പെടുത്തലുകൾ നൽകും.",
  buyerWalkthroughNudge1: "ഫീഡ് റിഫ്രഷ് ചെയ്യാൻ ഹോമിൽ താഴേക്ക് വലിക്കുക.",
  buyerWalkthroughNudge2: "വിള കഥ അല്ലെങ്കിൽ ചോദ്യം പോസ്റ്റ് ചെയ്യാൻ + ടാബ് ഉപയോഗിക്കുക.",
  buyerWalkthroughNudge3: "ലിസ്റ്റിംഗുകളിലെ സ്ഥിരീകരിച്ച ബാഡ്ജ് എന്നാൽ വിൽപ്പനക്കാരൻ അടിസ്ഥാന പരിശോധനകൾ പൂർത്തിയാക്കി.",
  firstTimeRoleTitle: "നിങ്ങൾ എന്ത് ചെയ്യുന്നു?",
  firstTimeRoleSubtitle: "ആപ്പിൽ നിങ്ങളുടെ പങ്ക് തിരഞ്ഞെടുക്കുക.",
  firstTimeRoleFarmer: "കർഷകൻ",
  firstTimeRoleFarmerSub: "ഞാൻ വിളകൾ കൃഷി ചെയ്ത് എന്റെ ഉൽപ്പന്നം വിൽക്കുന്നു.",
  firstTimeRoleConsumer: "ഉപഭോക്താവ്",
  firstTimeRoleConsumerSub: "ഞാൻ വീട്ടിലേക്കും ബിസിനസിനും ഉൽപ്പന്നം വാങ്ങുന്നു.",
  firstTimeRoleEducator: "അധ്യാപകൻ",
  firstTimeRoleEducatorSub: "ഞാൻ അറിവ്, ഉപകരണങ്ങൾ, മികച്ച രീതികൾ പങ്കിടുന്നു.",
  firstTimeRoleLogistics: "ലോജിസ്റ്റിക്സ്",
  firstTimeRoleLogisticsSub: "ഞാൻ കാർഷിക ഉൽപ്പന്നവും സാമഗ്രികളും കൊണ്ടുപോകാൻ സഹായിക്കുന്നു.",
  firstTimeCropsTitle: "നിങ്ങൾ എന്ത് കൃഷി ചെയ്യുന്നു?",
  firstTimeCropsSubtitle: "പ്രസക്തമായ ശുപാർശകൾ ലഭിക്കാൻ നിങ്ങൾ ഏത് വിളകൾ കൃഷി ചെയ്യുന്നു എന്ന് പറയുക.",
  searchByCrop: "വിള അനുസരിച്ച് തിരയുക",
  cropGroupGrains: "ധാന്യങ്ങൾ & സിറിയലുകൾ",
  cropGroupVegetables: "പച്ചക്കറികൾ",
  cropGroupFruits: "പഴങ്ങൾ",
  cropGroupPulses: "പയറുവർഗങ്ങൾ",
  cropRice: "അരി",
  cropWheat: "ഗോതമ്പ്",
  cropJowar: "ചോളം",
  cropMaize: "മക്കച്ചോളം",
  cropBajra: "കമ്പം",
  cropTomato: "തക്കാളി",
  cropPotato: "ഉരുളക്കിഴങ്ങ്",
  cropOnion: "ഉള്ളി",
  cropChilli: "മുളക്",
  cropBrinjal: "വഴുതന",
  cropMango: "മാവ്",
  cropBanana: "വാഴ",
  cropGrapes: "മുന്തിരി",
  cropOrange: "ഓറഞ്ച്",
  cropApple: "ആപ്പിൾ",
  cropTur: "തുവര",
  cropMoong: "ചെറുപയർ",
  cropUrad: "ഉഴുന്ന്",
  cropMasoor: "മസൂർ",
  cropChana: "കടല",
  locationLabel: "സ്ഥലം",
  idLast4Placeholder: "••••"
};

export const COMMON_UI_TA: typeof COMMON_UI_EN = {
  loginRequired: "உள்நுழைவு தேவை",
  loginRequiredChat: "சாட்டில் ரீல் அனுப்ப உள்நுழையவும்.",
  loginRequiredSave: "ரீல் சேமிக்க உள்நுழையவும்.",
  loginRequiredReport: "இடுகையைப் புகாரளிக்க உள்நுழையவும்.",
  loginRequiredDelete: "இடுகையை நீக்க உள்நுழையவும்.",
  chatUnavailableSend: "இந்தப் பயனர் இன்னும் செய்திகளைப் பெற முடியாது.",
  sentTitle: "அனுப்பப்பட்டது",
  reelSentTo: "ரீல் {{name}} க்கு அனுப்பப்பட்டது.",
  shareFailedSystem: "சிஸ்டம் பகிர்வைத் திறக்க முடியவில்லை.",
  noMediaTitle: "மீடியா இல்லை",
  noMediaStory: "இந்த ரீலில் ஸ்டோரிக்கு மீடியா இல்லை.",
  addedTitle: "சேர்க்கப்பட்டது",
  addedToStory: "ரீல் உங்கள் ஸ்டோரியில் சேர்க்கப்பட்டது.",
  copiedPostLink: "இடுகை இணைப்பு கிளிப்போர்டுக்கு நகலெடுக்கப்பட்டது.",
  copyFailedTitle: "நகல் தோல்வி",
  copyFailed: "இணைப்பை நகலெடுக்க முடியவில்லை.",
  gotItHidePost: "சரி",
  gotItHidePostMsg: "இந்த இடுகையை மறைத்து, இந்தச் சாதனத்தில் உங்களுக்குக் காண்பிப்பதை மாற்றுவோம்.",
  thanksReport: "நன்றி",
  thanksReportMsg: "உங்கள் புகார் பெறப்பட்டது, விரைவில் ஆய்வு செய்யப்படும்.",
  reportFailed: "புகார் தோல்வி",
  notAllowedTitle: "அனுமதி இல்லை",
  notAllowedDeleteOwn: "உங்கள் சொந்த இடுகைகளை மட்டுமே நீக்க முடியும்.",
  deleteFailed: "நீக்குதல் தோல்வி",
  deletePostTitle: "இந்த இடுகையை நீக்கவா?",
  deletePostBody: "இதை மீட்க இயலாது.",
  deleteConfirm: "நீக்கு",
  reportSpam: "ஸ்பேம் அல்லது தவறான தகவல்",
  reportHarassment: "தொல்லை அல்லது மிரட்டல்",
  reportHate: "வெறுப்புப் பேச்சு அல்லது சின்னங்கள்",
  reportNudity: "நிர்வாணம் அல்லது பாலியல் உள்ளடக்கம்",
  reportViolence: "வன்முறை அல்லது ஆபத்தான செயல்கள்",
  reportScam: "மோசடி அல்லது ஏமாற்று",
  reportIp: "அறிவுசார் சொத்து மீறல்",
  reportOther: "வேறு ஏதாவது",
  myFarm: "எனது பண்ணை",
  unknownLocation: "தெரியாத",
  liveStream: "லைவ் ஸ்ட்ரீம்",
  liveNow: "இப்போது லைவ்",
  goLive: "லைவ் செல்க",
  liveBadge: "லைவ்",
  noOneLive: "இப்போது யாரும் லைவில் இல்லை",
  popularLive: "பிரபலமான லைவ்",
  noLiveStreamsYet: "இன்னும் லைவ் ஸ்ட்ரீம்கள் இல்லை",
  noLiveStreamsSub: "படைப்பாளர்கள் லைவ் வரும்போது இங்கே தெரியும்.",
  startLive: "லைவ் தொடங்கு",
  publicAccount: "பொது கணக்கு",
  messageBtn: "செய்தி",
  tryAgainMoment: "சிறிது நேரம் கழித்து மீண்டும் முயற்சிக்கவும்.",
  viewProfilePhoto: "சுயவிவர புகைப்படத்தைக் காண்க",
  cannotOpenChat: "இந்தப் பயனருக்கு இன்னும் சாட் திறக்க முடியாது.",
  createModePost: "இடுகை",
  createModeStory: "ஸ்டோரி",
  createModeReel: "ரீல்",
  createModeLive: "லைவ்",
  filterNormal: "சாதாரண",
  filterWarm: "வெப்பமான",
  filterCool: "குளிர்ச்சி",
  filterBw: "கருப்பு-வெள்ளை",
  filterVivid: "தெளிவான",
  filterSunset: "சூரிய அஸ்தமனம்",
  filterNoir: "நோயர்",
  createPreviewReel: "ரீல்",
  createPreviewPost: "புதிய இடுகை",
  createPreviewStory: "ஸ்டோரி",
  createPreviewTitle: "உருவாக்கு",
  tagPeople: "நபர்களைக் குறியிடு",
  addLocation: "இடம் சேர்க்கவும்",
  locationPrefix: "இடம்: {{place}}",
  addAudio: "ஆடியோ சேர்க்கவும்",
  audioPrefix: "ஆடியோ: {{title}}",
  audience: "பார்வையாளர்கள்",
  audienceSoon: "பார்வையாளர் கட்டுப்பாடுகள் விரைவில் வரும்.",
  scheduleLiveTitle: "லைவ் திட்டமிடு",
  scheduleLiveBody: "திட்டமிடல் எதிர்கால புதுப்பிப்பில் கிடைக்கும்.",
  shareBtn: "பகிர்",
  nextBtn: "அடுத்து",
  writeReelCaptionPh: "ரீல் தலைப்பு எழுதுக...",
  writeCaptionPh: "தலைப்பு எழுதுக...",
  typeTextPlaceholder: "உரை தட்டச்சு செய்க",
  recents: "சமீபத்திய",
  unknownArtist: "அறியாத கலைஞர்",
  unknownTitle: "தெரியாத",
  createErrSelectPhoto: "குறைந்தது ஒரு புகைப்படமாவது தேர்ந்தெடுக்கவும்.",
  createErrCarouselPhotos: "கரோசலில் புகைப்படங்கள் மட்டும். வீடியோ இடுகைக்கு ஒரு வீடியோ தேர்ந்தெடுக்கவும்.",
  createErrPostPhotosOnly: "இடுகை கிரிடில் புகைப்படங்கள் மட்டும். வீடியோவிற்கு ரீல் தேர்ந்தெடுக்கவும்.",
  createErrCameraPerm: "கேமரா அனுமதி தேவை.",
  createErrReelVideoOnly: "ரீல்களுக்கு வீடியோ மட்டும். வீடியோ தேர்ந்தெடுக்கவும் அல்லது பதிவு செய்யவும்.",
  createErrCapturePhoto: "புகைப்படம் எடுக்க முடியவில்லை.",
  createErrReelVideoOnlyShort: "ரீல்களுக்கு வீடியோ மட்டும்.",
  createErrMediaPerm: "மீடியா லைப்ரரி அனுமதி தேவை.",
  createErrChooseOption: "தொடர ஒரு விருப்பத்தைத் தேர்ந்தெடுக்கவும்.",
  createErrStoryMedia: "ஸ்டோரி மீடியா பதிவு செய்யவும் அல்லது பதிவேற்றவும்.",
  createErrCaptionRequired: "தலைப்பு தேவை.",
  createErrReelMedia: "ரீல் வீடியோ பதிவு செய்யவும் அல்லது பதிவேற்றவும்.",
  createErrPostMedia: "உங்கள் இடுகைக்கு மீடியா சேர்க்கவும்.",
  createErrReelSingleVideo: "ரீலில் ஒரே ஒரு வீடியோ இருக்க வேண்டும்.",
  createErrUploadReel: "ஒரு வீடியோ ரீல் பதிவேற்றவும்.",
  createErrMixedMedia: "ஒரு வீடியோ அல்லது பல புகைப்படங்கள் — இரண்டும் அல்ல.",
  createErrOneVideo: "ஒரு இடுகைக்கு ஒரு வீடியோ மட்டும்.",
  createErrUploadImages: "படங்களைப் பதிவேற்ற முடியவில்லை.",
  createErrPublish: "வீடியோ வெளியிட முடியவில்லை.",
  createErrAudioPreview: "ஆடியோ முன்னோட்டம் காட்ட முடியவில்லை.",
  createErrAudioFetch: "பாடல்கள் ஏற்ற முடியவில்லை. இணையத்தைச் சரிபாருங்கள்.",
  createToolAudio: "ஆடியோ",
  createToolText: "உரை",
  createToolOverlay: "மேலடுக்கு",
  createToolFilter: "வடிகட்டி",
  createToolEdit: "திருத்து",
  openGallery: "புகைப்பட தொகுப்பைத் திற",
  videoSizeLimit: "வீடியோ {{size}}MB உள்ளது. {{max}}MB க்குக் குறைவாகத் தேர்ந்தெடுக்கவும்.",
  languageNoteTitle: "மொழி குறித்து",
  languageNoteBody:
    "பொத்தான்கள், மெனுக்கள், செய்திகள் உங்கள் மொழிக்கு மாறும். நீங்கள் எழுதிய இடுகைகள் நீங்கள் தட்டச்சு செய்தபடியே இருக்கும் — எங்கள் அகராதியிலுள்ள பயிர் சொற்கள் மட்டும் மாறும்.",
  back: "பின்செல்",
  continue: "தொடரவும்",
  roleSelectionTitle: "நீங்கள் கிராப்வைபை எப்படிப் பயன்படுத்துவீர்கள்?",
  roleSelectionSub: "ஒன்றைத் தேர்ந்தெடுக்கவும் — எப்போது வேண்டுமானாலும் மற்ற பகுதிகளை ஆராயலாம்.",
  roleBuyerTitle: "வாங்குபவர்",
  roleBuyerDesc: "பொருட்கள், இயந்திரங்கள், சேவைகளை வாங்குங்கள்",
  roleSellerTitle: "விற்பனையாளர்",
  roleSellerDesc: "உங்கள் பண்ணையிலிருந்து பட்டியலிட்டு ஆர்டர்களை நிர்வகிக்கவும்",
  roleExpertTitle: "நிபுணர்",
  roleExpertDesc: "பாடங்கள் கற்பித்து சமூகத்திற்கு ஆலோசனை வழங்கவும்",
  personalInfoTitle: "உங்களைப் பற்றி",
  personalInfoSubtitle: "கிராப்வைபை தனிப்பயனாக்க இதைப் பயன்படுத்துகிறோம். சுயவிவரத்தில் எப்போது வேண்டுமானாலும் மாற்றலாம்.",
  personalInfoPrimaryLabel: "கணக்கு உருவாக்கு",
  fullNameLabel: "முழு பெயர்",
  fullNamePlaceholder: "உங்கள் பெயர்",
  emailLabel: "மின்னஞ்சல்",
  emailPlaceholder: "you@example.com",
  dobLabel: "பிறந்த தேதி",
  dobPlaceholder: "YYYY-MM-DD (விரும்பினால்)",
  languageLocationTitle: "மொழி & இடம்",
  languageLocationSub: "பிராந்திய உள்ளடக்கத்திற்கான விருப்ப குறுக்குவழிகள்",
  preferredLanguageLabel: "விருப்பமான மொழி",
  preferredLanguagePlaceholder: "எ.கா. தமிழ், English",
  districtOrCityPlaceholder: "மாவட்டம் அல்லது நகரம்",
  addLanguageLocation: "மொழி & இடம் சேர்க்கவும்",
  otpTitle: "6 இலக்க குறியீடு",
  otpSubtitle: "{{phone}} க்கு அனுப்பிய சரிபார்ப்புக் குறியீட்டை உள்ளிடவும்",
  verifying: "சரிபார்க்கிறது...",
  verifyContinue: "சரிபார்த்துத் தொடரவும்",
  invalidOtp: "தவறான OTP. மீண்டும் முயற்சிக்கவும்.",
  resendCode: "குறியீட்டை மீண்டும் அனுப்பவா?",
  resend: "மீண்டும் அனுப்பு",
  sending: "அனுப்புகிறது...",
  failedResendOtp: "OTP மீண்டும் அனுப்ப முடியவில்லை.",
  buyerInterestsTitle: "உங்கள் ஆர்வங்கள்",
  buyerInterestsSubtitle: "நீங்கள் வழக்கமாக என்ன வாங்குவீர்கள்? பட்டியல்களையும் குறிப்புகளையும் வரிசைப்படுத்த உதவும்.",
  interestsLabel: "பயிர்கள், வகைகள் அல்லது இலக்குகள்",
  interestsPlaceholder: "எ.கா. இயற்கை காய்கறிகள், சொட்டு நீர்ப்பாசனம், டிராக்டர் பாகங்கள்",
  buyerDeliveryTitle: "டெலிவரி முகவரி",
  buyerDeliverySubtitle: "சந்தை ஆர்டர்களுக்கான இயல்புநிலை டிராப்-ஆஃப் (பின்னர் மேலும் சேர்க்கலாம்).",
  addressLineLabel: "முகவரி வரி",
  addressLinePlaceholder: "கிராமம், அடையாளம், தெரு",
  districtLabel: "மாவட்டம்",
  pinCodeOptional: "பின் குறியீடு (விரும்பினால்)",
  sellerFarmTitle: "பண்ணை விவரங்கள்",
  sellerFarmSubtitle: "நீங்கள் யாரென்று வாங்குபவர்களுக்குச் சொல்லுங்கள். விற்பனையாளர் சுயவிவரத்தில் பின்னர் மேம்படுத்தலாம்.",
  farmNameLabel: "பண்ணை அல்லது வணிகப் பெயர்",
  landAcresLabel: "பயிர் நிலம் (ஏக்கர், விரும்பினால்)",
  acresPlaceholder: "எ.கா. 12.5",
  primaryCropLabel: "முதன்மை பயிர் அல்லது பொருள்",
  primaryCropPlaceholder: "எ.கா. பாசுமதி, பால், நர்சரி",
  sellerKycTitle: "KYC அடிப்படைகள்",
  sellerKycSubtitle: "டெமோ படி — உற்பத்தியில் ID ஆவண OCR மற்றும் பெயர் பொருத்தம் நடைபெறும்.",
  legalNameLabel: "சட்டப்பூர்வ பெயர் (ID படி)",
  idLast4Label: "ஆதார் / ID குறிப்பின் கடைசி 4 இலக்கங்கள்",
  sellerBankTitle: "வங்கிக் கணக்கு",
  sellerBankSubtitle: "விற்ற பட்டியல்களின் பணம் இங்கே வரவு வைக்கப்படும். டெமோ மட்டும் — உண்மையான வங்கி விவரங்களை உள்ளிடாதீர்கள்.",
  continueToSecurity: "பாதுகாப்புக்குத் தொடரவும்",
  accountHolderLabel: "கணக்கு வைத்திருப்பவர் பெயர்",
  ifscLabel: "IFSC",
  accountNumberLabel: "கணக்கு எண்",
  expertDomainTitle: "உங்கள் துறை",
  expertDomainSubtitle: "எந்த தலைப்புகள் அல்லது பயிர்களில் ஆலோசனை வழங்குகிறீர்கள்? உங்கள் நிபுணர் சுயவிவரத்தில் காட்டப்படும்.",
  specializationsLabel: "நிபுணத்துவங்கள்",
  specializationsPlaceholder: "எ.கா. மண் ஆரோக்கியம், பாலிஹவுஸ் தக்காளி, இயற்கை சான்றிதழ்",
  yearsExperienceLabel: "அனுபவ ஆண்டுகள் (விரும்பினால்)",
  yearsPlaceholder: "எ.கா. 8",
  expertCredentialsTitle: "தகுதிகள்",
  expertCredentialsSubtitle: "கற்பவர்கள் தெரிந்து கொள்ள வேண்டிய பட்டங்கள், சான்றிதழ்கள் அல்லது நிறுவன இணைப்புகள்.",
  professionalHeadlineLabel: "தொழில் தலைப்பு",
  professionalHeadlinePlaceholder: "எ.கா. வேளாண் விஞ்ஞானி, KVK விரிவாக்க அதிகாரி",
  certificationsOptionalLabel: "சான்றிதழ்கள் (விரும்பினால்)",
  certificationsPlaceholder: "B.Sc. Ag, இயற்கை ஆய்வு சான்றிதழ்…",
  expertVerificationTitle: "நிபுணர் சரிபார்ப்பு",
  expertVerificationSubtitle:
    "பேட்ஜ்கள் நேரலையாவதற்கு முன் தகுதி மற்றும் மாதிரி உள்ளடக்கத்தை ஆய்வு செய்வோம். இந்த டெமோ தொடரும்போது படி நிறைவடையும்.",
  submitForReviewDemo: "ஆய்வுக்கு சமர்ப்பிக்கவும் (டெமோ)",
  whatHappensNext: "அடுத்து என்ன நடக்கும்",
  expertVerificationBody:
    "உற்பத்தி: சிறிய கற்பித்தல் கிளிப், குறிப்புகள், விருப்ப ID பதிவேற்றவும். எங்கள் குழு பொதுவாக 48 மணி நேரத்தில் பதிலளிக்கும்.",
  securityVerificationTitle: "பாதுகாப்பு சரிபார்ப்பு",
  securityVerificationSubtitle:
    "முக உயிர்த்தன்மை, ID OCR, மூன்றாம் தரப்பு KYC இங்கே இணைக்கப்படும். வெற்றிகரமான சோதனையை உருவகப்படுத்த கீழே தட்டவும்.",
  completeVerificationDemo: "சரிபார்ப்பை நிறைவு செய்க (டெமோ)",
  checksTitle: "சோதனைகள்",
  checkFaceLiveness: "• முக உயிர்த்தன்மை (ஆன்ட்டி-ஸ்பூஃப்)",
  checkGovIdOcr: "• அரசு ID பிடிப்பு & OCR",
  checkVendorKyc: "• விருப்ப விற்பனையாளர் KYC பொருத்தம்",
  buyerWalkthroughTitle: "விரைவு குறிப்புகள்",
  buyerWalkthroughSubtitle: "சிறு அறிமுகம் — செயலியில் மென்மையான நினைவூட்டல்களுடன் உதவுவோம்.",
  buyerWalkthroughNudge1: "ஃபீடை புதுப்பிக்க முகப்பில் கீழே இழுக்கவும்.",
  buyerWalkthroughNudge2: "அறுவடை கதை அல்லது கேள்வி இடுகையிட + டேப் பயன்படுத்தவும்.",
  buyerWalkthroughNudge3: "பட்டியல்களில் சரிபார்க்கப்பட்ட பேட்ஜ் என்றால் விற்பனையாளர் அடிப்படை சோதனைகளை நிறைவு செய்துள்ளார்.",
  firstTimeRoleTitle: "நீங்கள் என்ன செய்கிறீர்கள்?",
  firstTimeRoleSubtitle: "செயலியில் உங்கள் பங்கைத் தேர்ந்தெடுக்கவும்.",
  firstTimeRoleFarmer: "விவசாயி",
  firstTimeRoleFarmerSub: "நான் பயிர்களை வளர்த்து என் விளைபொருளை விற்கிறேன்.",
  firstTimeRoleConsumer: "நுகர்வோர்",
  firstTimeRoleConsumerSub: "நான் வீடு மற்றும் வணிகத்திற்கு விளைபொருள் வாங்குகிறேன்.",
  firstTimeRoleEducator: "கல்வியாளர்",
  firstTimeRoleEducatorSub: "நான் அறிவு, கருவிகள், சிறந்த நடைமுறைகளைப் பகிர்கிறேன்.",
  firstTimeRoleLogistics: "லாஜிஸ்டிக்ஸ்",
  firstTimeRoleLogisticsSub: "நான் பண்ணை விளைபொருள் மற்றும் பொருட்களை கொண்டு செல்ல உதவுகிறேன்.",
  firstTimeCropsTitle: "நீங்கள் என்ன வளர்க்கிறீர்கள்?",
  firstTimeCropsSubtitle: "பொருத்தமான பரிந்துரைகள் பெற நீங்கள் எந்த பயிர்கள் வளர்க்கிறீர்கள் என்று சொல்லுங்கள்.",
  searchByCrop: "பயிர் மூலம் தேடு",
  cropGroupGrains: "தானியங்கள் & சிறுதானியங்கள்",
  cropGroupVegetables: "காய்கறிகள்",
  cropGroupFruits: "பழங்கள்",
  cropGroupPulses: "பருப்பு வகைகள்",
  cropRice: "அரிசி",
  cropWheat: "கோதுமை",
  cropJowar: "சோளம்",
  cropMaize: "மக்காச்சோளம்",
  cropBajra: "கம்பு",
  cropTomato: "தக்காளி",
  cropPotato: "உருளைக்கிழங்கு",
  cropOnion: "வெங்காயம்",
  cropChilli: "மிளகாய்",
  cropBrinjal: "கத்திரிக்காய்",
  cropMango: "மாம்பழம்",
  cropBanana: "வாழை",
  cropGrapes: "திராட்சை",
  cropOrange: "ஆரஞ்சு",
  cropApple: "ஆப்பிள்",
  cropTur: "துவரை",
  cropMoong: "பாசிப்பயிறு",
  cropUrad: "உளுந்து",
  cropMasoor: "மசூர்",
  cropChana: "கொண்டைக்கடலை",
  locationLabel: "இடம்",
  idLast4Placeholder: "••••"
};

export const COMMON_UI_MR: typeof COMMON_UI_EN = {
  loginRequired: "लॉगिन आवश्यक",
  loginRequiredChat: "चॅटमध्ये रील पाठवण्यासाठी लॉगिन करा.",
  loginRequiredSave: "रील सेव्ह करण्यासाठी लॉगिन करा.",
  loginRequiredReport: "पोस्ट रिपोर्ट करण्यासाठी लॉगिन करा.",
  loginRequiredDelete: "पोस्ट हटवण्यासाठी लॉगिन करा.",
  chatUnavailableSend: "हा वापरकर्ता अद्याप संदेश घेऊ शकत नाही.",
  sentTitle: "पाठवले",
  reelSentTo: "रील {{name}} ला पाठवली.",
  shareFailedSystem: "सिस्टम शेअर उघडता आले नाही.",
  noMediaTitle: "मीडिया नाही",
  noMediaStory: "या रीलमध्ये स्टोरीसाठी मीडिया नाही.",
  addedTitle: "जोडले",
  addedToStory: "रील तुमच्या स्टोरीत जोडली.",
  copiedPostLink: "पोस्ट लिंक क्लिपबोर्डवर कॉपी झाली.",
  copyFailedTitle: "कॉपी अयशस्वी",
  copyFailed: "लिंक कॉपी होऊ शकली नाही.",
  gotItHidePost: "ठीक आहे",
  gotItHidePostMsg: "आम्ही ही पोस्ट लपवू आणि या डिव्हाइसवर तुम्हाला दाखवायचं ते सुधारू.",
  thanksReport: "धन्यवाद",
  thanksReportMsg: "तुमचा रिपोर्ट मिळाला, लवकरच तपासू.",
  reportFailed: "रिपोर्ट अयशस्वी",
  notAllowedTitle: "परवानगी नाही",
  notAllowedDeleteOwn: "तुम्ही फक्त तुमच्या स्वतःच्या पोस्ट हटवू शकता.",
  deleteFailed: "हटवणे अयशस्वी",
  deletePostTitle: "ही पोस्ट हटवायची?",
  deletePostBody: "हे पूर्ववत होऊ शकत नाही.",
  deleteConfirm: "हटवा",
  reportSpam: "स्पॅम किंवा भ्रामक",
  reportHarassment: "छळ किंवा धमकी",
  reportHate: "द्वेषपूर्ण भाषण किंवा चिन्हे",
  reportNudity: "नग्नता किंवा लैंगिक मजकूर",
  reportViolence: "हिंसा किंवा धोकादायक कृत्ये",
  reportScam: "फसवणूक किंवा घोटाळा",
  reportIp: "बौद्धिक संपदा उल्लंघन",
  reportOther: "इतर काही",
  myFarm: "माझे शेत",
  unknownLocation: "अज्ञात",
  liveStream: "लाइव्ह स्ट्रीम",
  liveNow: "आता लाइव्ह",
  goLive: "लाइव्ह जा",
  liveBadge: "लाइव्ह",
  noOneLive: "सध्या कोणी लाइव्ह नाही",
  popularLive: "लोकप्रिय लाइव्ह",
  noLiveStreamsYet: "अद्याप लाइव्ह स्ट्रीम नाहीत",
  noLiveStreamsSub: "क्रिएटर लाइव्ह आल्यावर ते इथे दिसतील.",
  startLive: "लाइव्ह सुरू करा",
  publicAccount: "सार्वजनिक खाते",
  messageBtn: "संदेश",
  tryAgainMoment: "थोड्या वेळाने पुन्हा प्रयत्न करा.",
  viewProfilePhoto: "प्रोफाइल फोटो पहा",
  cannotOpenChat: "या वापरकर्त्यासाठी अद्याप चॅट उघडता येत नाही.",
  createModePost: "पोस्ट",
  createModeStory: "स्टोरी",
  createModeReel: "रील",
  createModeLive: "लाइव्ह",
  filterNormal: "सामान्य",
  filterWarm: "उबदार",
  filterCool: "थंड",
  filterBw: "काळा-पांढरा",
  filterVivid: "चमकदार",
  filterSunset: "सूर्यास्त",
  filterNoir: "नोयर",
  createPreviewReel: "रील",
  createPreviewPost: "नवीन पोस्ट",
  createPreviewStory: "स्टोरी",
  createPreviewTitle: "तयार करा",
  tagPeople: "लोकांना टॅग करा",
  addLocation: "स्थान जोडा",
  locationPrefix: "स्थान: {{place}}",
  addAudio: "ऑडिओ जोडा",
  audioPrefix: "ऑडिओ: {{title}}",
  audience: "प्रेक्षक",
  audienceSoon: "प्रेक्षक नियंत्रणे लवकरच येतील.",
  scheduleLiveTitle: "लाइव्ह शेड्यूल",
  scheduleLiveBody: "शेड्यूलिंग भविष्यातील अपडेटमध्ये उपलब्ध होईल.",
  shareBtn: "शेअर",
  nextBtn: "पुढे",
  writeReelCaptionPh: "रील कॅप्शन लिहा...",
  writeCaptionPh: "कॅप्शन लिहा...",
  typeTextPlaceholder: "मजकूर टाइप करा",
  recents: "अलीकडील",
  unknownArtist: "अज्ञात कलाकार",
  unknownTitle: "अज्ञात",
  createErrSelectPhoto: "कमीत कमी एक फोटो निवडा.",
  createErrCarouselPhotos: "कॅरोसेलमध्ये फक्त फोटो. व्हिडिओ पोस्टसाठी एक व्हिडिओ निवडा.",
  createErrPostPhotosOnly: "पोस्ट ग्रिडमध्ये फक्त फोटो. व्हिडिओसाठी रील निवडा.",
  createErrCameraPerm: "कॅमेरा परवानगी आवश्यक आहे.",
  createErrReelVideoOnly: "रीलसाठी फक्त व्हिडिओ. व्हिडिओ निवडा किंवा रेकॉर्ड करा.",
  createErrCapturePhoto: "फोटो कॅप्चर होऊ शकला नाही.",
  createErrReelVideoOnlyShort: "रीलसाठी फक्त व्हिडिओ.",
  createErrMediaPerm: "मीडिया लायब्ररी परवानगी आवश्यक आहे.",
  createErrChooseOption: "पुढे जाण्यासाठी एक पर्याय निवडा.",
  createErrStoryMedia: "स्टोरी मीडिया रेकॉर्ड किंवा अपलोड करा.",
  createErrCaptionRequired: "कॅप्शन आवश्यक आहे.",
  createErrReelMedia: "रील व्हिडिओ रेकॉर्ड किंवा अपलोड करा.",
  createErrPostMedia: "तुमच्या पोस्टसाठी मीडिया जोडा.",
  createErrReelSingleVideo: "रीलमध्ये एकच व्हिडिओ असावा.",
  createErrUploadReel: "एक व्हिडिओ रील अपलोड करा.",
  createErrMixedMedia: "एक व्हिडिओ किंवा अनेक फोटो — दोन्ही नाही.",
  createErrOneVideo: "प्रत्येक पोस्टमध्ये एकच व्हिडिओ.",
  createErrUploadImages: "चित्रे अपलोड होऊ शकली नाहीत.",
  createErrPublish: "व्हिडिओ प्रकाशित होऊ शकला नाही.",
  createErrAudioPreview: "ऑडिओ पूर्वावलोकन होऊ शकले नाही.",
  createErrAudioFetch: "गाणी लोड होऊ शकली नाहीत. इंटरनेट तपासा.",
  createToolAudio: "ऑडिओ",
  createToolText: "मजकूर",
  createToolOverlay: "ओव्हरले",
  createToolFilter: "फिल्टर",
  createToolEdit: "संपादन",
  openGallery: "फोटो गॅलरी उघडा",
  videoSizeLimit: "व्हिडिओ {{size}}MB आहे. {{max}}MB पेक्षा कमी निवडा.",
  languageNoteTitle: "भाषेबद्दल",
  languageNoteBody:
    "बटणे, मेनू आणि संदेश तुमच्या भाषेत बदलतात. तुम्ही लिहिलेल्या पोस्ट तुम्ही टाइप केल्याप्रमाणेच राहतात — आमच्या शब्दकोशातील पीक शब्दच बदलतात.",
  back: "मागे",
  continue: "पुढे चालू ठेवा",
  roleSelectionTitle: "तुम्ही क्रॉपवाइब कसे वापराल?",
  roleSelectionSub: "एक निवडा — तुम्ही कधीही इतर क्षेत्रे पाहू शकता.",
  roleBuyerTitle: "खरेदीदार",
  roleBuyerDesc: "उत्पादने, यंत्रे आणि सेवा खरेदी करा",
  roleSellerTitle: "विक्रेता",
  roleSellerDesc: "तुमच्या शेतातून सूची तयार करा आणि ऑर्डर व्यवस्थापित करा",
  roleExpertTitle: "तज्ज्ञ",
  roleExpertDesc: "अभ्यासक्रम शिकवा आणि समुदायाला सल्ला द्या",
  personalInfoTitle: "तुमच्याबद्दल",
  personalInfoSubtitle: "क्रॉपवाइब वैयक्तिक करण्यासाठी आम्ही हे वापरतो. प्रोफाइलमध्ये कधीही बदलता येते.",
  personalInfoPrimaryLabel: "खाते तयार करा",
  fullNameLabel: "पूर्ण नाव",
  fullNamePlaceholder: "तुमचे नाव",
  emailLabel: "ईमेल",
  emailPlaceholder: "you@example.com",
  dobLabel: "जन्मतारीख",
  dobPlaceholder: "YYYY-MM-DD (ऐच्छिक)",
  languageLocationTitle: "भाषा आणि स्थान",
  languageLocationSub: "प्रादेशिक मजकुरासाठी ऐच्छिक शॉर्टकट",
  preferredLanguageLabel: "पसंतीची भाषा",
  preferredLanguagePlaceholder: "उदा. मराठी, English",
  districtOrCityPlaceholder: "जिल्हा किंवा शहर",
  addLanguageLocation: "भाषा आणि स्थान जोडा",
  otpTitle: "6 अंकी कोड",
  otpSubtitle: "कृपया {{phone}} वर पाठवलेला सत्यापन कोड प्रविष्ट करा",
  verifying: "सत्यापित होत आहे...",
  verifyContinue: "सत्यापित करा आणि पुढे जा",
  invalidOtp: "अवैध OTP. कृपया पुन्हा प्रयत्न करा.",
  resendCode: "कोड पुन्हा पाठवायचा?",
  resend: "पुन्हा पाठवा",
  sending: "पाठवत आहे...",
  failedResendOtp: "OTP पुन्हा पाठवता आला नाही.",
  buyerInterestsTitle: "तुमची आवड",
  buyerInterestsSubtitle: "तुम्ही सहसा काय खरेदी करता? सूची आणि सल्ले क्रमवारी लावण्यास मदत होते.",
  interestsLabel: "पिके, श्रेणी किंवा उद्दिष्टे",
  interestsPlaceholder: "उदा. सेंद्रिय भाजीपाला, ठिबक सिंचन, ट्रॅक्टर भाग",
  buyerDeliveryTitle: "वितरण पत्ता",
  buyerDeliverySubtitle: "मार्केटप्लेस ऑर्डरसाठी डीफॉल्ट ड्रॉप-ऑफ (नंतर आणखी जोडता येतात).",
  addressLineLabel: "पत्ता ओळ",
  addressLinePlaceholder: "गाव, खूण, रस्ता",
  districtLabel: "जिल्हा",
  pinCodeOptional: "पिन कोड (ऐच्छिक)",
  sellerFarmTitle: "शेताचे तपशील",
  sellerFarmSubtitle: "तुम्ही कोण आहात ते खरेदीदारांना सांगा. नंतर विक्रेता प्रोफाइलमध्ये सुधारता येतो.",
  farmNameLabel: "शेत किंवा व्यवसायाचे नाव",
  landAcresLabel: "लागवडीखालील जमीन (एकर, ऐच्छिक)",
  acresPlaceholder: "उदा. 12.5",
  primaryCropLabel: "मुख्य पीक किंवा उत्पादन",
  primaryCropPlaceholder: "उदा. बासमती, दुग्धव्यवसाय, रोपवाटिका",
  sellerKycTitle: "KYC मूलभूत गोष्टी",
  sellerKycSubtitle: "डेमो टप्पा — उत्पादनात ID दस्तऐवज OCR आणि नाव जुळणी होईल.",
  legalNameLabel: "कायदेशीर नाव (ID नुसार)",
  idLast4Label: "आधार / ID संदर्भाचे शेवटचे 4 अंक",
  sellerBankTitle: "बँक खाते",
  sellerBankSubtitle: "विकलेल्या सूचीचे पेमेंट इथे जमा होईल. फक्त डेमो — खरी बँक माहिती प्रविष्ट करू नका.",
  continueToSecurity: "सुरक्षेकडे पुढे जा",
  accountHolderLabel: "खातेधारकाचे नाव",
  ifscLabel: "IFSC",
  accountNumberLabel: "खाते क्रमांक",
  expertDomainTitle: "तुमचे क्षेत्र",
  expertDomainSubtitle: "तुम्ही कोणत्या विषयांवर किंवा पिकांवर सल्ला देता? तुमच्या तज्ज्ञ प्रोफाइलवर दाखवले जाईल.",
  specializationsLabel: "विशेषीकरणे",
  specializationsPlaceholder: "उदा. मृदा आरोग्य, पॉलीहाउस टोमॅटो, सेंद्रिय प्रमाणन",
  yearsExperienceLabel: "अनुभवाची वर्षे (ऐच्छिक)",
  yearsPlaceholder: "उदा. 8",
  expertCredentialsTitle: "पात्रता",
  expertCredentialsSubtitle: "शिकणाऱ्यांना माहित असाव्यात अशा पदव्या, प्रमाणपत्रे किंवा संस्थात्मक संबंध.",
  professionalHeadlineLabel: "व्यावसायिक शीर्षक",
  professionalHeadlinePlaceholder: "उदा. कृषी शास्त्रज्ञ, KVK विस्तार अधिकारी",
  certificationsOptionalLabel: "प्रमाणपत्रे (ऐच्छिक)",
  certificationsPlaceholder: "B.Sc. Ag, सेंद्रिय तपासणी प्रमाणपत्र…",
  expertVerificationTitle: "तज्ज्ञ सत्यापन",
  expertVerificationSubtitle:
    "बॅज लाइव्ह होण्यापूर्वी आम्ही पात्रता आणि नमुना मजकूर तपासतो. हा डेमो पुढे गेल्यावर टप्पा पूर्ण होतो.",
  submitForReviewDemo: "पुनरावलोकनासाठी सादर करा (डेमो)",
  whatHappensNext: "पुढे काय होईल",
  expertVerificationBody:
    "उत्पादन: लहान शिकवण क्लिप, संदर्भ आणि ऐच्छिक ID अपलोड करा. आमचा संघ सहसा 48 तासांत प्रतिसाद देतो.",
  securityVerificationTitle: "सुरक्षा सत्यापन",
  securityVerificationSubtitle:
    "चेहऱ्याची जीवंतता, ID OCR आणि तृतीय-पक्ष KYC इथे जोडले जाईल. यशस्वी तपासणीचे अनुकरण करण्यासाठी खाली टॅप करा.",
  completeVerificationDemo: "सत्यापन पूर्ण करा (डेमो)",
  checksTitle: "तपासण्या",
  checkFaceLiveness: "• चेहरा जीवंतता (अँटी-स्पूफ)",
  checkGovIdOcr: "• सरकारी ID कॅप्चर & OCR",
  checkVendorKyc: "• ऐच्छिक विक्रेता KYC जुळणी",
  buyerWalkthroughTitle: "द्रुत टिप्स",
  buyerWalkthroughSubtitle: "एक संक्षिप्त परिचय — अॅपमध्ये आम्ही सौम्य स्मरणपत्रांसह मदत करू.",
  buyerWalkthroughNudge1: "फीड रिफ्रेश करण्यासाठी होमवर खाली ओढा.",
  buyerWalkthroughNudge2: "पीक कथा किंवा प्रश्न पोस्ट करण्यासाठी + टॅब वापरा.",
  buyerWalkthroughNudge3: "सूचीवरील सत्यापित बॅज म्हणजे विक्रेत्याने मूलभूत तपासण्या पूर्ण केल्या.",
  firstTimeRoleTitle: "तुम्ही काय करता?",
  firstTimeRoleSubtitle: "अॅपमध्ये तुमची भूमिका निवडा.",
  firstTimeRoleFarmer: "शेतकरी",
  firstTimeRoleFarmerSub: "मी पिके पिकवतो आणि माझी उत्पादने विकतो.",
  firstTimeRoleConsumer: "ग्राहक",
  firstTimeRoleConsumerSub: "मी घर आणि व्यवसायासाठी उत्पादने खरेदी करतो.",
  firstTimeRoleEducator: "शिक्षक",
  firstTimeRoleEducatorSub: "मी ज्ञान, साधने आणि सर्वोत्तम पद्धती सामायिक करतो.",
  firstTimeRoleLogistics: "लॉजिस्टिक्स",
  firstTimeRoleLogisticsSub: "मी शेतमाल आणि सामग्री वाहतुकीत मदत करतो.",
  firstTimeCropsTitle: "तुम्ही काय पिकवता?",
  firstTimeCropsSubtitle: "संबंधित शिफारसी मिळवण्यासाठी तुम्ही कोणती पिके पिकवता ते सांगा.",
  searchByCrop: "पिकानुसार शोधा",
  cropGroupGrains: "धान्ये आणि तृणधान्ये",
  cropGroupVegetables: "भाजीपाला",
  cropGroupFruits: "फळे",
  cropGroupPulses: "कडधान्ये",
  cropRice: "तांदूळ",
  cropWheat: "गहू",
  cropJowar: "ज्वारी",
  cropMaize: "मका",
  cropBajra: "बाजरी",
  cropTomato: "टोमॅटो",
  cropPotato: "बटाटा",
  cropOnion: "कांदा",
  cropChilli: "मिरची",
  cropBrinjal: "वांगे",
  cropMango: "आंबा",
  cropBanana: "केळे",
  cropGrapes: "द्राक्षे",
  cropOrange: "संत्रे",
  cropApple: "सफरचंद",
  cropTur: "तूर",
  cropMoong: "मूग",
  cropUrad: "उडीद",
  cropMasoor: "मसूर",
  cropChana: "हरभरा",
  locationLabel: "स्थान",
  idLast4Placeholder: "••••"
};

export const COMMON_UI_BN: typeof COMMON_UI_EN = {
  loginRequired: "লগইন প্রয়োজন",
  loginRequiredChat: "চ্যাটে রিল পাঠাতে লগইন করুন।",
  loginRequiredSave: "রিল সেভ করতে লগইন করুন।",
  loginRequiredReport: "পোস্ট রিপোর্ট করতে লগইন করুন।",
  loginRequiredDelete: "পোস্ট মুছতে লগইন করুন।",
  chatUnavailableSend: "এই ব্যবহারকারী এখনও বার্তা গ্রহণ করতে পারছেন না।",
  sentTitle: "পাঠানো হয়েছে",
  reelSentTo: "রিল {{name}} কে পাঠানো হয়েছে।",
  shareFailedSystem: "সিস্টেম শেয়ার খোলা যায়নি।",
  noMediaTitle: "মিডিয়া নেই",
  noMediaStory: "এই রিলে স্টোরির জন্য মিডিয়া নেই।",
  addedTitle: "যোগ করা হয়েছে",
  addedToStory: "রিল আপনার স্টোরিতে যোগ করা হয়েছে।",
  copiedPostLink: "পোস্ট লিংক ক্লিপবোর্ডে কপি হয়েছে।",
  copyFailedTitle: "কপি ব্যর্থ",
  copyFailed: "লিংক কপি করা যায়নি।",
  gotItHidePost: "বুঝেছি",
  gotItHidePostMsg: "আমরা এই পোস্ট লুকাব এবং এই ডিভাইসে আপনাকে যা দেখাই তা সামঞ্জস্য করব।",
  thanksReport: "ধন্যবাদ",
  thanksReportMsg: "আপনার রিপোর্ট পেয়েছি, শীঘ্রই পর্যালোচনা করব।",
  reportFailed: "রিপোর্ট ব্যর্থ",
  notAllowedTitle: "অনুমতি নেই",
  notAllowedDeleteOwn: "আপনি শুধু নিজের পোস্ট মুছতে পারবেন।",
  deleteFailed: "মুছে ফেলা ব্যর্থ",
  deletePostTitle: "এই পোস্ট মুছবেন?",
  deletePostBody: "এটি পূর্বাবস্থায় ফেরানো যাবে না।",
  deleteConfirm: "মুছুন",
  reportSpam: "স্প্যাম বা বিভ্রান্তিকর",
  reportHarassment: "হয়রানি বা ভয়ভীতি",
  reportHate: "ঘৃণামূলক বক্তব্য বা প্রতীক",
  reportNudity: "নগ্নতা বা যৌন বিষয়বস্তু",
  reportViolence: "সহিংসতা বা বিপজ্জনক কাজ",
  reportScam: "প্রতারণা বা জালিয়াতি",
  reportIp: "বুদ্ধিবৃত্তিক সম্পত্তি লঙ্ঘন",
  reportOther: "অন্য কিছু",
  myFarm: "আমার খামার",
  unknownLocation: "অজানা",
  liveStream: "লাইভ স্ট্রিম",
  liveNow: "এখন লাইভ",
  goLive: "লাইভ যান",
  liveBadge: "লাইভ",
  noOneLive: "এখন কেউ লাইভে নেই",
  popularLive: "জনপ্রিয় লাইভ",
  noLiveStreamsYet: "এখনও কোনো লাইভ স্ট্রিম নেই",
  noLiveStreamsSub: "ক্রিয়েটররা লাইভ হলে তারা এখানে দেখা যাবে।",
  startLive: "লাইভ শুরু করুন",
  publicAccount: "পাবলিক অ্যাকাউন্ট",
  messageBtn: "বার্তা",
  tryAgainMoment: "কিছুক্ষণ পর আবার চেষ্টা করুন।",
  viewProfilePhoto: "প্রোফাইল ফটো দেখুন",
  cannotOpenChat: "এই ব্যবহারকারীর জন্য এখনও চ্যাট খোলা যাচ্ছে না।",
  createModePost: "পোস্ট",
  createModeStory: "স্টোরি",
  createModeReel: "রিল",
  createModeLive: "লাইভ",
  filterNormal: "স্বাভাবিক",
  filterWarm: "উষ্ণ",
  filterCool: "শীতল",
  filterBw: "সাদা-কালো",
  filterVivid: "উজ্জ্বল",
  filterSunset: "সূর্যাস্ত",
  filterNoir: "নোয়ার",
  createPreviewReel: "রিল",
  createPreviewPost: "নতুন পোস্ট",
  createPreviewStory: "স্টোরি",
  createPreviewTitle: "তৈরি করুন",
  tagPeople: "মানুষদের ট্যাগ করুন",
  addLocation: "অবস্থান যোগ করুন",
  locationPrefix: "অবস্থান: {{place}}",
  addAudio: "অডিও যোগ করুন",
  audioPrefix: "অডিও: {{title}}",
  audience: "দর্শক",
  audienceSoon: "দর্শক নিয়ন্ত্রণ শীঘ্রই আসছে।",
  scheduleLiveTitle: "লাইভ সূচি",
  scheduleLiveBody: "সূচি নির্ধারণ ভবিষ্যত আপডেটে পাওয়া যাবে।",
  shareBtn: "শেয়ার",
  nextBtn: "পরবর্তী",
  writeReelCaptionPh: "রিল ক্যাপশন লিখুন...",
  writeCaptionPh: "ক্যাপশন লিখুন...",
  typeTextPlaceholder: "টেক্সট টাইপ করুন",
  recents: "সাম্প্রতিক",
  unknownArtist: "অজানা শিল্পী",
  unknownTitle: "অজানা",
  createErrSelectPhoto: "অন্তত একটি ছবি নির্বাচন করুন।",
  createErrCarouselPhotos: "ক্যারোসেলে শুধু ছবি। ভিডিও পোস্টের জন্য একটি ভিডিও নির্বাচন করুন।",
  createErrPostPhotosOnly: "পোস্ট গ্রিডে শুধু ছবি। ভিডিওর জন্য রিল বেছে নিন।",
  createErrCameraPerm: "ক্যামেরা অনুমতি প্রয়োজন।",
  createErrReelVideoOnly: "রিলে শুধু ভিডিও। ভিডিও নির্বাচন করুন বা রেকর্ড করুন।",
  createErrCapturePhoto: "ছবি ক্যাপচার করা যায়নি।",
  createErrReelVideoOnlyShort: "রিলে শুধু ভিডিও।",
  createErrMediaPerm: "মিডিয়া লাইব্রেরি অনুমতি প্রয়োজন।",
  createErrChooseOption: "চালিয়ে যেতে একটি বিকল্প বেছে নিন।",
  createErrStoryMedia: "স্টোরি মিডিয়া রেকর্ড বা আপলোড করুন।",
  createErrCaptionRequired: "ক্যাপশন আবশ্যক।",
  createErrReelMedia: "রিল ভিডিও রেকর্ড বা আপলোড করুন।",
  createErrPostMedia: "আপনার পোস্টে মিডিয়া যোগ করুন।",
  createErrReelSingleVideo: "একটি রিলে একটি মাত্র ভিডিও হতে হবে।",
  createErrUploadReel: "একটি ভিডিও রিল আপলোড করুন।",
  createErrMixedMedia: "একটি ভিডিও অথবা একাধিক ছবি — দুটোই নয়।",
  createErrOneVideo: "প্রতি পোস্টে একটি ভিডিও।",
  createErrUploadImages: "ছবি আপলোড করা যায়নি।",
  createErrPublish: "ভিডিও প্রকাশ করা যায়নি।",
  createErrAudioPreview: "অডিও প্রিভিউ করা যায়নি।",
  createErrAudioFetch: "গান লোড হয়নি। ইন্টারনেট পরীক্ষা করুন।",
  createToolAudio: "অডিও",
  createToolText: "টেক্সট",
  createToolOverlay: "ওভারলে",
  createToolFilter: "ফিল্টার",
  createToolEdit: "সম্পাদনা",
  openGallery: "ফটো গ্যালারি খুলুন",
  videoSizeLimit: "ভিডিও {{size}}MB। অনুগ্রহ করে {{max}}MB এর কম নির্বাচন করুন।",
  languageNoteTitle: "ভাষা সম্পর্কে",
  languageNoteBody:
    "বোতাম, মেনু এবং বার্তা আপনার ভাষায় পরিবর্তন হয়। আপনার লেখা পোস্ট আপনি যেভাবে টাইপ করেছেন সেভাবেই থাকে — শুধু আমাদের অভিধানের ফসল শব্দগুলো পরিবর্তন হয়।",
  back: "পিছনে",
  continue: "চালিয়ে যান",
  roleSelectionTitle: "আপনি ক্রপভাইব কীভাবে ব্যবহার করবেন?",
  roleSelectionSub: "একটি বেছে নিন — আপনি যেকোনো সময় অন্য ক্ষেত্র অন্বেষণ করতে পারেন।",
  roleBuyerTitle: "ক্রেতা",
  roleBuyerDesc: "পণ্য, যন্ত্রপাতি এবং সেবা কিনুন",
  roleSellerTitle: "বিক্রেতা",
  roleSellerDesc: "আপনার খামার থেকে তালিকাভুক্ত করুন এবং অর্ডার পরিচালনা করুন",
  roleExpertTitle: "বিশেষজ্ঞ",
  roleExpertDesc: "কোর্স শেখান এবং সম্প্রদায়কে পরামর্শ দিন",
  personalInfoTitle: "আপনার সম্পর্কে",
  personalInfoSubtitle: "ক্রপভাইব ব্যক্তিগতকৃত করতে আমরা এটি ব্যবহার করি। প্রোফাইলে যেকোনো সময় পরিবর্তন করতে পারবেন।",
  personalInfoPrimaryLabel: "অ্যাকাউন্ট তৈরি করুন",
  fullNameLabel: "পুরো নাম",
  fullNamePlaceholder: "আপনার নাম",
  emailLabel: "ইমেইল",
  emailPlaceholder: "you@example.com",
  dobLabel: "জন্ম তারিখ",
  dobPlaceholder: "YYYY-MM-DD (ঐচ্ছিক)",
  languageLocationTitle: "ভাষা ও অবস্থান",
  languageLocationSub: "আঞ্চলিক বিষয়বস্তুর জন্য ঐচ্ছিক শর্টকাট",
  preferredLanguageLabel: "পছন্দের ভাষা",
  preferredLanguagePlaceholder: "যেমন বাংলা, English",
  districtOrCityPlaceholder: "জেলা বা শহর",
  addLanguageLocation: "ভাষা ও অবস্থান যোগ করুন",
  otpTitle: "৬ সংখ্যার কোড",
  otpSubtitle: "অনুগ্রহ করে {{phone}} এ পাঠানো যাচাইকরণ কোড লিখুন",
  verifying: "যাচাই হচ্ছে...",
  verifyContinue: "যাচাই করুন ও চালিয়ে যান",
  invalidOtp: "অবৈধ OTP। অনুগ্রহ করে আবার চেষ্টা করুন।",
  resendCode: "কোড আবার পাঠাবেন?",
  resend: "পুনরায় পাঠান",
  sending: "পাঠানো হচ্ছে...",
  failedResendOtp: "OTP পুনরায় পাঠানো যায়নি।",
  buyerInterestsTitle: "আপনার আগ্রহ",
  buyerInterestsSubtitle: "আপনি সাধারণত কী কেনেন? তালিকা ও পরামর্শ সাজাতে সাহায্য করে।",
  interestsLabel: "ফসল, বিভাগ বা লক্ষ্য",
  interestsPlaceholder: "যেমন জৈব সবজি, ড্রিপ সেচ, ট্রাক্টর যন্ত্রাংশ",
  buyerDeliveryTitle: "ডেলিভারি ঠিকানা",
  buyerDeliverySubtitle: "মার্কেটপ্লেস অর্ডারের জন্য ডিফল্ট ড্রপ-অফ (পরে আরও যোগ করতে পারবেন)।",
  addressLineLabel: "ঠিকানা লাইন",
  addressLinePlaceholder: "গ্রাম, ল্যান্ডমার্ক, রাস্তা",
  districtLabel: "জেলা",
  pinCodeOptional: "পিন কোড (ঐচ্ছিক)",
  sellerFarmTitle: "খামারের বিবরণ",
  sellerFarmSubtitle: "আপনি কে তা ক্রেতাদের জানান। পরে বিক্রেতা প্রোফাইলে উন্নত করতে পারবেন।",
  farmNameLabel: "খামার বা ব্যবসার নাম",
  landAcresLabel: "চাষের জমি (একর, ঐচ্ছিক)",
  acresPlaceholder: "যেমন 12.5",
  primaryCropLabel: "প্রধান ফসল বা পণ্য",
  primaryCropPlaceholder: "যেমন বাসমতি, দুগ্ধ, নার্সারি",
  sellerKycTitle: "KYC মূল বিষয়",
  sellerKycSubtitle: "ডেমো ধাপ — উৎপাদনে ID ডকুমেন্ট OCR এবং নাম মিলানো হবে।",
  legalNameLabel: "আইনি নাম (ID অনুযায়ী)",
  idLast4Label: "আধার / ID রেফারেন্সের শেষ ৪ সংখ্যা",
  sellerBankTitle: "ব্যাংক অ্যাকাউন্ট",
  sellerBankSubtitle: "বিক্রি হওয়া তালিকার পেমেন্ট এখানে জমা হবে। শুধু ডেমো — আসল ব্যাংক তথ্য দেবেন না।",
  continueToSecurity: "নিরাপত্তায় চালিয়ে যান",
  accountHolderLabel: "অ্যাকাউন্ট হোল্ডারের নাম",
  ifscLabel: "IFSC",
  accountNumberLabel: "অ্যাকাউন্ট নম্বর",
  expertDomainTitle: "আপনার ক্ষেত্র",
  expertDomainSubtitle: "আপনি কোন বিষয় বা ফসলে পরামর্শ দেন? আপনার বিশেষজ্ঞ প্রোফাইলে দেখানো হবে।",
  specializationsLabel: "বিশেষায়নসমূহ",
  specializationsPlaceholder: "যেমন মাটির স্বাস্থ্য, পলিহাউস টমেটো, জৈব সার্টিফিকেশন",
  yearsExperienceLabel: "অভিজ্ঞতার বছর (ঐচ্ছিক)",
  yearsPlaceholder: "যেমন 8",
  expertCredentialsTitle: "যোগ্যতা",
  expertCredentialsSubtitle: "শিক্ষার্থীদের জানা উচিত এমন ডিগ্রি, সার্টিফিকেট বা প্রাতিষ্ঠানিক সংযুক্তি।",
  professionalHeadlineLabel: "পেশাদার শিরোনাম",
  professionalHeadlinePlaceholder: "যেমন কৃষি বিজ্ঞানী, KVK সম্প্রসারণ কর্মকর্তা",
  certificationsOptionalLabel: "সার্টিফিকেট (ঐচ্ছিক)",
  certificationsPlaceholder: "B.Sc. Ag, জৈব পরিদর্শন সার্টিফিকেট…",
  expertVerificationTitle: "বিশেষজ্ঞ যাচাইকরণ",
  expertVerificationSubtitle:
    "ব্যাজ লাইভ হওয়ার আগে আমরা যোগ্যতা ও নমুনা বিষয়বস্তু পর্যালোচনা করি। এই ডেমো চালিয়ে গেলে ধাপ সম্পূর্ণ হয়।",
  submitForReviewDemo: "পর্যালোচনার জন্য জমা দিন (ডেমো)",
  whatHappensNext: "পরবর্তীতে কী হবে",
  expertVerificationBody:
    "উৎপাদন: সংক্ষিপ্ত শিক্ষণ ক্লিপ, রেফারেন্স এবং ঐচ্ছিক ID আপলোড করুন। আমাদের দল সাধারণত ৪৮ ঘণ্টার মধ্যে জানায়।",
  securityVerificationTitle: "নিরাপত্তা যাচাইকরণ",
  securityVerificationSubtitle:
    "মুখের জীবন্ততা, ID OCR এবং তৃতীয়-পক্ষ KYC এখানে সংযুক্ত হবে। সফল পরীক্ষা অনুকরণ করতে নিচে ট্যাপ করুন।",
  completeVerificationDemo: "যাচাইকরণ সম্পূর্ণ করুন (ডেমো)",
  checksTitle: "পরীক্ষাসমূহ",
  checkFaceLiveness: "• মুখের জীবন্ততা (অ্যান্টি-স্পুফ)",
  checkGovIdOcr: "• সরকারি ID ক্যাপচার ও OCR",
  checkVendorKyc: "• ঐচ্ছিক বিক্রেতা KYC মিলান",
  buyerWalkthroughTitle: "দ্রুত টিপস",
  buyerWalkthroughSubtitle: "একটি সংক্ষিপ্ত পরিচিতি — অ্যাপের ভেতরে আমরা মৃদু মনে করিয়ে দেব।",
  buyerWalkthroughNudge1: "ফিড রিফ্রেশ করতে হোমে নিচে টানুন।",
  buyerWalkthroughNudge2: "ফসলের গল্প বা প্রশ্ন পোস্ট করতে + ট্যাব ব্যবহার করুন।",
  buyerWalkthroughNudge3: "তালিকায় যাচাইকৃত ব্যাজ মানে বিক্রেতা মৌলিক পরীক্ষা পাস করেছেন।",
  firstTimeRoleTitle: "আপনি কী করেন?",
  firstTimeRoleSubtitle: "অ্যাপে আপনার ভূমিকা নির্বাচন করুন।",
  firstTimeRoleFarmer: "কৃষক",
  firstTimeRoleFarmerSub: "আমি ফসল চাষ করি এবং আমার উৎপাদন বিক্রি করি।",
  firstTimeRoleConsumer: "ভোক্তা",
  firstTimeRoleConsumerSub: "আমি বাড়ি ও ব্যবসার জন্য পণ্য কিনি।",
  firstTimeRoleEducator: "শিক্ষক",
  firstTimeRoleEducatorSub: "আমি জ্ঞান, সরঞ্জাম ও সেরা অনুশীলন শেয়ার করি।",
  firstTimeRoleLogistics: "লজিস্টিক্স",
  firstTimeRoleLogisticsSub: "আমি কৃষি পণ্য ও সামগ্রী পরিবহনে সাহায্য করি।",
  firstTimeCropsTitle: "আপনি কী চাষ করেন?",
  firstTimeCropsSubtitle: "প্রাসঙ্গিক সুপারিশ পেতে আপনি কোন ফসল চাষ করেন তা জানান।",
  searchByCrop: "ফসল দিয়ে খুঁজুন",
  cropGroupGrains: "শস্য ও খাদ্যশস্য",
  cropGroupVegetables: "শাকসবজি",
  cropGroupFruits: "ফলমূল",
  cropGroupPulses: "ডাল",
  cropRice: "ধান",
  cropWheat: "গম",
  cropJowar: "জোয়ার",
  cropMaize: "ভুট্টা",
  cropBajra: "বাজরা",
  cropTomato: "টমেটো",
  cropPotato: "আলু",
  cropOnion: "পেঁয়াজ",
  cropChilli: "লঙ্কা",
  cropBrinjal: "বেগুন",
  cropMango: "আম",
  cropBanana: "কলা",
  cropGrapes: "আঙুর",
  cropOrange: "কমলা",
  cropApple: "আপেল",
  cropTur: "অড়হর",
  cropMoong: "মুগ",
  cropUrad: "মাষকলাই",
  cropMasoor: "মসুর",
  cropChana: "ছোলা",
  locationLabel: "অবস্থান",
  idLast4Placeholder: "••••"
};
